### ISSUE TITLE
check number not reported in the journal entry list

### ISSUE THREAD

**Issue by fmontess** [Dolibarr/dolibarr#13118] opened 2020-02-15 11:58 UTC
# Bug
[*the check or transfer number is not included in the list of bank entries*]

## Environment
- **Version**: [*11.0.0*]
- **OS**: [*Linux*]
- **Web server**: [*Apache*]
- **PHP**: [*7.1.33*]
- **Database**: [*MariaDB-10.2.31*]
- **URL(s)**: [*compta/facture/card.php* and */compta/bank/bankentries_list.php*]

## Expected and actual behavior
[*1) In "invoicing | Payment" I create a new invoice
2) I validate it
3) I pay it by inquiring the number of check or transfer
in Banques | Caisses \ Listes écritures the reference is not present.*]

**Comment by atm-maxime** [comment] 2020-02-15 18:04
Please close if this is duplicate of #13096

**Comment by fmontess** [comment] 2020-02-15 19:55
No, it's different. in issue # 13096 the rules were entered in the members menu and it is now resolved.

Here the problem is when we pay an invoice. It's the same problem but in a different menu

**Closed as completed** 2020-02-19 23:21 UTC
Labels: Bug
