### ISSUE TITLE
Bug:Dictionaries can not choose China

### ISSUE THREAD

**Issue by leangjia** [Dolibarr/dolibarr#5736] opened 2016-09-12 11:28 UTC
Which dictionary is concerned ?

**Comment by eldy** [comment] 2016-11-03 09:31
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by grandoc** [comment] 2016-12-10 11:49
Last version displays china within dictionary countries list. We close this bug.

**Comment by eldy** [comment] 2016-12-10 11:59
It seems this PR was set with "Discussion" or "PR to fix" tag, but no answer nor correction was provided since a long time. So request is automatically closed.
Please reopened and add a comment if you think this is an error.

**Closed as completed by eldy** 2016-12-10 11:59 UTC
Labels: Bug or PR need more information
