### ISSUE TITLE
MAIN_ADD_PDF_BACKGROUND works only for the first page

### ISSUE THREAD

**Issue by jfposi** [Dolibarr/dolibarr#5622] opened 2016-08-12 12:59 UTC
# Bug

The Option MAIN_ADD_PDF_BACKGROUND only add the PDF as background on the first page. I found the error on Proposals and Invoices, maybe the error is for each standard document template.
## Environment
- **Version**: 3.9.3
- **Web server**: Remote from 1&1, Apache+Mysql... 
## Expected and actual behavior

It should add the PDF you define on MAIN_ADD_PDF_BACKGROUND as background on each page of the generated documents. But it does only for the first page, at least for the azure standard template.
## Steps to reproduce the behavior

Create a proposal with enough lines, or big descriptions  on lines, to reach the use of more than 1 page on the document.
generate it, and check the background is only used with the first page.
## Others

I'm trying to find and fix the problem on the .php file pdf_azur.modules.php (with another name), If I find a fix, I will post it.

**Comment by marcosgdf** [comment] 2016-09-07 11:38
This error can be fixed by extending `TCPDI` class and replacing AddPage to automatically use the template.

The reason is because of auto page break caused by `TCPDF::writeHTMLCell` in `pdf_writelinedesc` function.

Example:

in `pdf_getInstance` function:

``` php
class DoliPDF extends TCPDI
    {
        public function AddPage($orientation = '', $format = '', $keepmargins = false, $tocpage = false)
        {


            parent::AddPage($orientation, $format, $keepmargins, $tocpage);

            global $conf;

            $this->setSourceFile($conf->mycompany->dir_output.'/'.$conf->global->MAIN_ADD_PDF_BACKGROUND);
            $tplidx = $this->importPage(1);

            $this->useTemplate($tplidx);
        }
    }

    $pdf = new DoliPDF($pagetype, $metric, $format);

    return $pdf;
```

**Comment by dolibarr95** [comment] 2017-04-04 14:08
Hi
Why this fix is not in a pr for the next version ?

**Comment by jfposi** [comment] 2017-04-04 15:51
well, I guess because it is not considered a big problem, and not a lot of people/companies are using it. I would change it, but Im quite noob with github and didn't have time to go 100% with it.

**Comment by simnandez** [comment] 2017-12-01 22:40
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Closed as completed by simnandez** 2017-12-01 22:40 UTC
