### ISSUE TITLE
D14.0.0/ F2106020001 / Important Feature in competitions : API connect / Import of Bank Statement

### ISSUE THREAD

**Issue by riseval** [Dolibarr/dolibarr#17804] opened 2021-06-02 17:57 UTC
# Feature Request

Ability to Import Excel statements issued by Banks

## Use case

As an Accountant, I should be able to import Bank statement provided by Bank in Excel format.  This will be used to compare monthly account balance Credit (CR) / Debit (DR) with bank for reconciliation.

## Suggested implementation

Please provide an "Excel / CSV Import option" to import bank statements into the dolibarr for comparison and reconciliation.
Down the line, this can be enhanced into direct connection to Bank through API.  Now-a-days, almost all banks are providing direct connectivity to the accounts through API.

## Suggested steps
1. Please provide an option to import bank statement either in CSV or Excel format.
2. Leading Indian bank that provides international banking services provide the statement in the enclosed format.
3. Kindly check the attachment.
[Sample bank stmt.xls](https://github.com/Dolibarr/dolibarr/files/6586560/Sample.bank.stmt.xls)

**Comment by atm-maxime** [comment] 2021-06-03 05:48
Duplicate of #17798 ?

**Comment by aspangaro** [comment] 2021-06-07 20:28
An external module is present on Dolistore (there are no plans to integrate it into the core at this time) :  https://www.dolistore.com/fr/modules/1385-Suivi-Bancaire-Automatique-sans-abonnement.html?search_query=suivi&results=50

**Closed as completed** 2021-07-16 05:30 UTC
Labels: Feature request

**Comment by proofy** [comment] 2022-12-28 00:48
I'm a little shocked right now. The advertised module costs €540. Actually, one more point in the import assistant would be enough for me. The €540 module apparently cannot provide an API connection. My thoughts are racing about what I'm going to do now.

**Comment by HeneryH** [comment] 2025-04-23 18:36
This is still a deal killer for me.  Manually typing in bank transactions is not going to work in 2025.  At least be able to import OFX or CSV files.$650 USD per year is a lot for what should be a core feature.  That alone makes quickbooks cheaper.
