### ISSUE TITLE
Bug: Error Champ 't.default_vat_code' inconnu dans field list

### ISSUE THREAD

**Issue by grandoc** [Dolibarr/dolibarr#7065] opened 2017-06-27 17:42 UTC
# Bug

## Environment
- **Version**: 6.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.30-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.0.30-MariaDB-0+deb8u2
- **URL**: /product/price.php?id=98

**Comment by eldy** [comment] 2017-06-29 00:57
Can you provide the full error and original message ?

**Comment by grandoc** [comment] 2017-06-30 07:55
It is a copy-paste of the original message

**Comment by simnandez** [comment] 2017-07-06 10:32
I tested, access to price, modify default price, delete old prices without issues

**Comment by simnandez** [comment] 2017-09-28 08:44
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:44 UTC
Labels: Works for me / Can't reproduce
