### ISSUE TITLE
Email collector does not attachments of tickets

### ISSUE THREAD

**Issue by VaderD** [Dolibarr/dolibarr#19748] opened 2022-01-05 16:46 UTC
# Bug
If a email that arrives in the email account that the collector checks and has attachments the email collector does not insert them as attached files.

## Environment
- **Version**: [*14.0.4*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache 2.4.6*]
- **PHP**: [*7.4.26*]
- **Database**: [*MySQL 5.5.68*]

**Comment by ksar-ksar** [comment] 2022-01-05 21:06
Duplicate of #19569 , #19498 ,  #18049

This is not a BUG, and you already open on issue for that.

**Comment by VaderD** [comment] 2022-01-06 00:35
Anyway i forgot that is had open it...so close this

**Closed as completed** 2022-01-06 06:50 UTC
Labels: Feature request
