### ISSUE TITLE
Commande fournisseur dispatch

### ISSUE THREAD

**Issue by all3kcis** [Dolibarr/dolibarr#3118] opened 2015-06-30 09:48 UTC
Est-il normal qu'il soit possible des continuer la ventilation d'une commande fournisseur alors que son statut est "Reçue complètement" (5) ?

**Comment by rdoursenaud** [comment] 2015-07-08 18:24
Please report issues in english and read the guidelines at https://github.com/Dolibarr/dolibarr/blob/develop/CONTRIBUTING.md#bug-reports-and-feature-requests

Also specify an affected version and a way to reproduce the behavior.

Thanks!

**Comment by all3kcis** [comment] 2015-07-09 07:33
Is it normal that it is possible to continue the ventilation of a purchase order while its status is "completely Received" (5)?

Test with v3.6.1 and 3.8 (develop)

After complete receipt of the order, it is always possible to receive the command on the "receiving" tab.
This maybe a desired behavior?

**Comment by rdoursenaud** [comment] 2015-07-09 10:59
Yes, that's the expected behavior when dispatching is set to manual (in admin/stock.php).
Dispatching is done after receiving.
You can very well have received the order in full and have it stored in a buffer area before it's being dispatched in the stock.
In many facilities, this is even done by different personnel.

**Comment by all3kcis** [comment] 2015-07-09 13:32
ok, is it better to receive in a buffer warehouse, put the command "received completely" if this is true, then later make a stock transfer?
I think the workflow is well respected.

**Comment by rdoursenaud** [comment] 2015-07-09 15:02
The Dolibarr workflow does not take into account "buffer warehouse".
What's expected is:
- You receive the goods and check them (You know you're supposed to do that while the delivery guy's still there, right?)
- If the order is complete receive completely, else receive partial (That's also when you have the opportunity to make comments on the delivery slip before the delivery guy leaves.)
- Now dispatch the goods to the stock while keeping track of it in Dolibarr

**Comment by fappels** [comment] 2015-07-10 12:13
Shouldn't we add a status 'everything dispatched' to keep track of orders waiting to be dispatched to stock

**Comment by JBooze** [comment] 2015-08-17 18:28
I may be missing something in the interface, but there appears to be no easy way to filter and view orders that have been received but not yet dispatched. If an employee receives an order but forgets to execute the dispatch, it's hell on wheels to locate the offending order and get it fixed. Also, it would be very nice if the "Receive" button could be configured so that clicking it launched the same dispatch popup that the "Accept" link launches. I'd like my warehouse receivers to simply click "Receive", click through the popup, and be done. that way, they couldn't fail to complete the dispatch procedure.  

Subsequent comment: Dolibarr is an unbelievably awesome product, and I don't want the above comment (which originated out of ignorance on my part) to negatively bias potential adopters. I have since discovered that orders that have been received but not dispatched will survive on Products/Warehouses/Replenishment/Replenishment Orders _until they are dispatched_. These orders will appear on Products/Warehouses/Replenishment/Replenishment Orders with a status of "Validated" instead of "In prgress" (or whatever). So, to identify received-but-undispatched orders, simply look at Products/Warehouses/Replenishment/Replenishment Orders and look for line items tagged "Validated". Piece of cake...

**Comment by BebZ** [comment] 2015-08-17 20:34
It's not really helll on wheels you can reach referring objects and find the bad dispatched order. But a new status could be nice also :)
Especially if 100% everything dispatched to be automatic status...

**Comment by BebZ** [comment] 2015-12-03 14:20
Yes there are 2 diferent steps : one is a status, which can be updated quickly, when the delivery guy is still here... 
the other one is a manual dispatch with no control if partial/total/excendently dispatched (because it is important to be able to dispatch more or less than ordered qty, if supplier mistakes, or rounding it to a defined qty)
then the status must be updated by your warehouse guy to partial/totally delivered etc...
I think best is to add more statuses like : checked reception, totally dispatched, partially dispatched, partilaaly received, etc... no ?

Did you see in 3.9 he new statuses of each line of the supplier order to be approved or not ?

**Comment by atm-maxime** [comment] 2018-03-09 21:50
This workflow has been modified since then. I close the issue.

**Closed as completed by atm-maxime** 2018-03-09 21:50 UTC
Labels: Discussion
