### ISSUE TITLE
Php Timezone

### ISSUE THREAD

**Issue by Nicofol** [Dolibarr/dolibarr#16118] opened 2021-01-30 23:01 UTC
How is possible to solve? in Dolibarr previous version, the timezone was correct.

In dolibarr 13, the time zone is wrong (+1h). 
Php 7.1.33 version. 
The current time is now 23.59 (11.59PM)
The Dolibarr time is 00.59 (+1h)

Fuso orario attuale | +1 (+3600)       Europe/Rome       Ora legale (utente): No     (Si in estate)
-- | --
=> Orario PHP (server) | 31/01/2021 00.58
=> dol_print_date(0,"dayhourtext") | 01 gennaio 1970 01:00
=> dol_get_first_day(1970,1,false) | -3600     (=> dol_print_date() or idate() of this value = 01/01/1970 00.00)
=> dol_get_first_day(1970,1,true) | -3600     (=> dol_print_date() or idate() of this value = 01/01/1970 00.00)
TimeZone MySql (database) (database) | CEST
Fuso orario client (utente) | +1 (+3600)       Europe/Rome       Ora legale (utente): No
=> Orario client (utente) | 31/01/2021 00.58

**Comment by alyatis85** [comment] 2021-01-31 02:45
Confirmed. Got the same. +1h when you create a ticket at 2:30 it prints 3:30
All TimeZone settings are prorperly set on server : 'Europe/Paris'
Thank for help

**Comment by ptibogxiv** [comment] 2021-02-01 09:25
@eldy i confirm this bug on all objects Invoice orders tickets...

**Comment by matDOTviguier** [comment] 2021-02-01 09:46
Idem with my #16077 ?

**Comment by matDOTviguier** [comment] 2021-02-01 09:47
@eldy dangerous event ahead.

**Comment by ptibogxiv** [comment] 2021-02-01 09:47
> Idem with my #16077 ?

I Think it's the same bug

**Comment by matDOTviguier** [comment] 2021-02-01 09:51
Yes, I apologize, I found it only on ticket at first time. the fix proposed is not good.
Time is shown correctly. It's a timestamp problem. No a tzdata related one.

**Comment by jcattan** [comment] 2021-02-01 12:26
Confirmed. Got the same. +1h since upgrade dolibarr 13 version on my debian 10.7
tzdata , php and MAIN_SERVER_TZ are set Europe/Paris

**Comment by eldy** [comment] 2021-02-01 19:46
@Nicofol What do you have if you enter "date" on command line on your server ?

**Comment by Nicofol** [comment] 2021-02-01 21:20
I have not the SSH access because is a shared hosting server, not dedicated. Let me know what can I do if possible, tks. Perhaps the Php Ini can help? see attach...
![Immagine 2021-02-01 222905](https://user-images.githubusercontent.com/56766857/106520336-29a95000-64cc-11eb-90e9-eb590900e69a.png)

**Comment by eldy** [comment] 2021-02-01 23:21
I pushed a fix. Thanks to check on  demo.dolibarr.org  if you find another error.
You will probably found other similar troubles on some other pages. We will have to fix them one by one.

**Comment by jcattan** [comment] 2021-02-02 06:54
> 
> 
> @Nicofol What do you have if you enter "date" on command line on your server ?

the date in ssh is correct : Tue Feb  2 07:54:04 CET 2021

**Comment by jcattan** [comment] 2021-02-02 07:54
> 
> 
> I pushed a fix. Thanks to check on demo.dolibarr.org if you find another error.
> You will probably found other similar troubles on some other pages. We will have to fix them one by one.

the fix correct the bug for me
thanks

**Comment by matDOTviguier** [comment] 2021-02-02 08:08
@eldy are you to publish 13.0.1 in order to have a fast solution about it ? I cannot se milestones ...

**Closed as completed** 2021-02-02 09:26 UTC
Labels: Bug

**Comment by alyatis85** [comment] 2021-02-02 09:33
Bonjour,

J'ai retesté sur la demo. En faisant un up sur un ticket (passage en "lu"
du ticket à 9h42), l'heure affichée est 8h42, pour un ticket créé à 8h57 (Date de création OK)
