### ISSUE TITLE
Impossible to create a new user with PostgreSQL database

### ISSUE THREAD

**Issue by tomours** [Dolibarr/dolibarr#3346] opened 2015-08-04 15:28 UTC
Hello, I'm looking for an ERP an was trying the 3.8 beta version of Dolibarr (very interested by advanced accounting, and looking for a new software for 2016-01-01).

I was trying to create a new user when I had the following error : 

> ERROR: 23505: duplicate key value violates unique constraint 'uk_user_api_key' DETAIL: Key (api_key)=() already exists. SCHEMA NAME: public TABLE NAME: llx_user CONSTRAINT NAME: uk_user_api_key LOCATION: _bt_check_unique, nbtinsert.c:402

At this time, I only have 2 users when I look in db : "Superadmin" and the user created during installation.

As I started an installation from scratch, I have some other minor issues/improvements to report. Should I do it here (as they aren't really bugs) ?

**Comment by BebZ** [comment] 2015-08-04 15:29
Download a 3.7.2 first and then 3.8.1

PS : this message is too complicated for me, so i can't handle the solving of the problem. maybe can you try to (save them first) empty the tables related to users and see new behaviour ?
with localhost/dolibarr/phpmyadmin or localhost/phpmyadmin ;)

**Comment by tomours** [comment] 2015-08-04 15:36
I don't see any 3.8.1. Do you mean dev version ?
Do you mean that I should download and install 3.7.2 (prod version) and then upgrade to that last version to fix this ? 

(I made a mistake in my first post : there is only on user in db : Superadmin is the user created during installation)

**Comment by BebZ** [comment] 2015-08-04 15:41
Yes 3.8 is alpha-frozen for the moment, you'd better wait for 3.8.1-stable to have a cleaned-debugged version for 2016/01/01.
But you are really welcome and you are very kind to inform us about bug reports (on beta-alpha or whatever version) here with such a level of details. Great !

**Comment by rdoursenaud** [comment] 2015-08-04 16:54
Can't reproduce.
@tomours Do you have a way to reliably reproduce from a clean install ?

**Comment by tomours** [comment] 2015-08-05 08:35
Hi, here is exactly what I did :
- Copy the files on my server and add a virtual host, pointing to dolibarr htdocs directory
- Add a user "dolibarr" to my db server (postgres, almost last version) and create an empty db called "dolibarr", owned by the dolibarr user
- Go to the install url with my browser and follow the process (tables were created by the install proccess, I didn't use any other script to do that)

I don't know what kind of information I could provide to help, maybe the structure of my users table as it is now. But I can't do it now, as I'm moving to a new house and the server I did my tests on is offline for the moment. I may be able to provide this this evening or tomorrow morning (french time).

**Comment by rdoursenaud** [comment] 2015-08-05 16:32
Oh, I get it. It's a PostgreSQL related bug.
Dolibarr is developped and extensively tested on MySQL and MariaDB databases. PostgreSQL support is always lagging a bit behind.
I'll update the title. Thanks.

**Comment by tomours** [comment] 2015-08-10 12:44
Well, after #3372, it seems that #3346 is also fixed : I can now create users (there was a problem with creation date format).
Should I modify the name of my commit to refer to both issues, or is there a way to merge them into one ?

**Comment by eldy** [comment] 2015-08-20 01:47
If bug is fixed, best solution is just to close it. No need to change label, there is link to reference into comments. Just close if fixed.

**Closed as completed** 2015-08-24 07:11 UTC
Labels: Priority 1 - High / Blocking
