### ISSUE TITLE
invoice supplier bank account

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4353] opened 2016-01-07 18:01 UTC
On supplier invoice, when no bank account is selected, dolibarr choose the first bank on bank account list and related invoice to this account. (3.8.3 release)

**Comment by eldy** [comment] 2016-01-08 15:01
I can't reproduce with 3.8.3. Can you provide a screenshot ?

**Comment by simnandez** [comment] 2017-12-01 22:08
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Closed as completed by simnandez** 2017-12-01 22:08 UTC
