### ISSUE TITLE
v14.0.0. - 14.0.1 and 14.0.2 The tasks show the list of attachments, but do not allow to open or download them.

### ISSUE THREAD

**Issue by JoAnMaFe** [Dolibarr/dolibarr#18606] opened 2021-09-04 23:26 UTC
Since the update to **V14.0.0 -14.0.1 y 14.0.2** 
the tasks show the list of attachments, but do not allow to open or download them, displaying the following message
Access denied.
You are trying to access a page, area or functionality of a disabled module or without an authenticated or unauthorised session for your user.
Current login: administrator Permissions for this user can be
permissions for this user can be assigned by Dolibarr administrator through menu Start-> Users.
With previous versions (13.04) this problem did not exist.
In the end I discovered that while everything was working OK. in 13.04 when upgrading to v 14.0.0 the files attached to the tasks cannot be downloaded or displayed.
It is possible that many users do not add attachments to their tasks but if their tasks are based on JPG or PDF photo documentation, they will not be able to use it and will not be able to support their customers.  

# Bug
[the tasks show the list of attachments, but do not allow to open or download them]

## Environment
- **Version**: [14.0.0 - 14.0.1 and 14.0.2]
- **OS**: [W10 x64]
- **Web server**: [Apache/2.4.48]
- **PHP**: [7.4.23]
- **Database**: [10.5.4-MariaDB]
- **URL(s)**: [Localhost]

## Expected and actual behavior
[Restore viewing and downloading of task attachments.]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by JoAnMaFe** [comment] 2021-09-13 17:36
In v14.0.2 it doesn't work for me either.
Access denied.
You try to access a page, area or functionality of a disabled module or without an authenticated session or not allowed to your user. 
Permissions for this user can be assigned by Dolibarr administrator via menu Start-> Users. 

In addition, thumbnails of events are not visible, they can be opened, but a blank icon is displayed.

**Comment by edupulpillo** [comment] 2021-10-24 07:10
The problem persist in 14.0.3
Trying to access to any attached file to the task using the link is returning a problem of permissions, even using the admin user with all the rights enabled. The only way to be able to access to the file attached is generate a public access link, and use it.

This is the error message returned:

> Access denied.
> You try to access to a page, area or feature of a disabled module or without being in an authenticated session or that is not allowed to your user.
> Current login: admin
> Permission for this login can be defined by your Dolibarr administrator from menu Home->Users.

The problem seems to be introduced in version 13.0.4 in the file  /htdocs/dolibarr/htdocs/core/lib/files.lib.php afer that version the problem arises.
Using the file files.lib.php that belongs to 13.0.3 in the version 14.0.3, then the version 14.0.3 works fine.

**Comment by JoAnMaFe** [comment] 2021-10-24 09:40
Certainly, the problem remains for me, although the "temporary" solution of replacing the "files.lib.php" file from version 13.0.3 works fine for me in 14.03.
Note: There are already too many versions with this problem.

**Comment by edupulpillo** [comment] 2021-10-24 09:49
Yes, too much tickets opened with same problem, here the list to close all when the problem be fixed:
#18589
#18617
#18716
#18606

**Comment by edupulpillo** [comment] 2022-01-08 02:55
The problem persist in 14.0.5

**Comment by edupulpillo** [comment] 2022-01-08 04:51
I think the bug is in the line number of the file  **/htdocs/dolibarr/htdocs/core/lib/files.lib.php** in version 14.0.5, where the line number 2665 is 
`$accessallowed = checkUserAccessToObject($user, array('projet_task'), $tmptask->id, 'projet&project', '', '', 'rowid', '');
`
but instead it should be:
`$accessallowed = checkUserAccessToObject($user, array('projet_task'), $tmptask->id, 'projet_task&project_task', '', '', 'rowid', '');
`

After this small update  replacing `projet&project` by `projet_task&project_task` in the line number 2665 the problem is fixed.

PR in progress.

**Comment by edupulpillo** [comment] 2022-01-23 04:09
Problem solved with commit  5d5a219 explained in #19770 
Please close this issue

**Comment by JoAnMaFe** [comment] 2022-03-25 18:14
In 15.01 the same thing happens again. Attached files in the project tasks, when trying to access any of them, display the following message:
Access denied.
You are trying to access a page, area or functionality of a disabled module or without an authenticated or unauthorised session to your user.

Current login: admin
Permissions for this user can be assigned by Dolibarr administrator via menu Home-> Users. Note: clear your browser cookies to destroy existing sessions for this login.

**Comment by edupulpillo** [comment] 2023-02-08 01:38
I can not reproduce the problem. 
Problem solved with commit https://github.com/Dolibarr/dolibarr/commit/5d5a219b959ff7e07b8347207cd86ab855681da5 explained in https://github.com/Dolibarr/dolibarr/pull/19770
Please @JoAnMaFe kindly close this issue

**Closed as completed** 2023-02-10 19:07 UTC
Labels: Bug
