### ISSUE TITLE
Getting a Read-Error on opening an ODT file after update to 12.0.1

### ISSUE THREAD

**Issue by hussain-attari** [Dolibarr/dolibarr#14245] opened 2020-07-15 07:46 UTC
Hi,

I am getting this error after updating dolibarr to 12.0.1.

![image](https://user-images.githubusercontent.com/47553388/87517912-2f108b80-c69d-11ea-8c8f-910ed996d699.png)

This error happens when I download my ODT files and open them in Open office. I haven't changed anything in the setup and this was working fine before the update.

**Comment by hussain-attari** [comment] 2020-07-15 10:24
Getting this error only today.

Files created previously are opening fine. Even when I modify and validate a proposal they are opening fine. So I am not sure what the issue is.

**Comment by orloxgr** [comment] 2020-07-23 15:23
Same issue here

**Comment by eldy** [comment] 2020-07-29 12:57
On which object do you experience this (product, thirdparty, invoice... ?)

**Comment by orloxgr** [comment] 2020-07-29 13:39
well if you export the default invoice which has all the variables to odt and try to open it at open/libre office you will see the error.
The error does NOT happen on develop branch

**Comment by bjoern86** [comment] 2020-08-04 15:44
Same here with proposals. check also #14242 probably same issue.

**Comment by orloxgr** [comment] 2020-08-11 08:15
Same issue on 12.0.2

**Comment by orloxgr** [comment] 2020-08-11 10:23
Some more information. On a clean 12.0.2 installation, it works. The issue is only happening if you update from a previous version. If I downgrade from 12 to 11 it works again but if you try to validate the invoice you get error "Failed to insert event : Unknown column 'punctual' in 'field list'".
So right now after the update to make an invoice what we do is use files of 12 to validate the invoices and copy files from 11 to create the odts.
edit: After some reasearch the only file responsible for this is htdocs/includes/odtphp/odf.php
If you change the 12.0.2 file with the 11.0.5 everything works.

**Comment by ghost** [comment] 2020-08-31 12:19
I have the same errors some times and think it is a replacement of a special characters in the `WYSIWYG editor` like `ä`, `ü`, `ö`

The problem is that the `context.xml` file contains a extra `;` but I don't know why.
The problem only occurs when we paste a text from MS office in the `WYSIWYG editor`, but not always.

As a workaround:
Use the `source` button in the `WYSIWYG editor` and paste the text this avoid the automatic translation in a HTML entity and remove all HTML elements.

**Comment by hussain-attari** [comment] 2020-09-15 07:13
Hi,
Any update on this?

The workaround doesn't work for me. I still get the error.

**Comment by ghost** [comment] 2020-09-19 12:39
Hello, currently i can't reproduce this error, but the text in the ODT is not compelte visible when i open it with LibreOffice.

Can you upgrade you LibreOffice to 7.0 or 7.1 and check again?

**Comment by orloxgr** [comment] 2020-09-24 13:21
> Hello, currently i can't reproduce this error, but the text in the ODT is not compelte visible when i open it with LibreOffice.
> 
> Can you upgrade you LibreOffice to 7.0 or 7.1 and check again?

Same thing with 12.03 and Libre 7.0.1.2 (there isnt 7.1 vesion yet :) )

If I replace file htdocs/includes/odtphp/odf.php with 11. version file, it works.

If you like I can give you my database and files to debug it. You can find me on skype same name

**Comment by hussain-attari** [comment] 2020-09-26 10:56
Hi,

The thing is that it doesn't happen always. It happens occasionaly. probably why you aren't able to reproduce the error.

I have updated my Open office to 4.1.7

Will post a screenshot when I get the error again.

**Comment by orloxgr** [comment] 2020-09-26 11:39
For me it happens always. Tried both open office and libre. As long as I use the 11 file I mention above, it's ok. It has to do something with the database settings because on a clean install all is ok.

**Comment by hussain-attari** [comment] 2020-10-12 05:37
Got the error today.

This is how I got it.

- I created a quote.
- Set the quote to 'Accepted'
- Created Invoice
- Validated the invoice
- Clicked on the ODT and got the error.

Just to be sure I deleted and regenerated the ODT file and got the same error.

My Dolibarr Version: 12.0.1
Apache Open Office Version: 4.1.7

**Comment by hussain-attari** [comment] 2020-10-12 05:46
Just updated to Dolibarr version 12.0.3 and regenerated the ODT file and got the same error

**Comment by orloxgr** [comment] 2020-12-22 11:54
12.0.4 The issue is fixed for me.
I do not know if it is related but At some point I changed the dolibarr path inside database since it had the path of an older hosting.

**Comment by bjoern86** [comment] 2020-12-23 17:12
update 12.0.4 fixed this for me.
@orloxgr : it is not related, i did not change the path.
@h6585: please close this. thank you.

**Comment by orloxgr** [comment] 2020-12-23 17:34
> update 12.0.4 fixed this for me.
> @orloxgr : it is not related, i did not change the path.
> @h6585: please close this. thank you.

So you did something that fixed this issue or it was a random fix? :D

**Comment by bjoern86** [comment] 2020-12-23 18:34
Random fix. 🙃

**Comment by hussain-attari** [comment] 2020-12-24 07:11
I haven't got the error  yet on 12.0.4

keeping this open for another week just to make sure that I don't get an error later on.

**Closed as completed** 2021-01-12 11:56 UTC
Labels: Bug
