### ISSUE TITLE
invoice on shipping warning

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#3336] opened 2015-07-29 19:00 UTC
displays says 
 Attention, une ou plusieurs factures existent déjà
but there is no invoice for this shipping 

SH1507-0003 (Dernière facture en rapport FA1507-0003 Montant HT FA1507-0003) 
but invvoice shown is linked to another shippment  SH1507-0002 in my case

**Comment by rdoursenaud** [comment] 2015-08-03 07:52
Steps to reproduce?
Which version please?

**Comment by tiaris** [comment] 2015-08-03 17:33
dolibarr 3.8 beta
create a shippment and an invoice for this shippment
then create another shippment from same order (partial shippments) and try creating an invice on this new shippment

**Comment by marcosgdf** [comment] 2015-09-12 16:00
Can't reproduce. Probably due to bug #3515

**Comment by rdoursenaud** [comment] 2015-09-16 18:13
@tiaris , can you confirm that the issue has been resolved by the #3515 fix?

**Comment by aconits** [comment] 2016-06-30 14:34
Hi,

This comportement is normal, each invoice generate from shipment are linked to shipment and the original order
So the event message is not a bug it say to be careful because you have already one or more invoices linked to your order

**Comment by simnandez** [comment] 2017-12-01 21:47
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Closed as completed by simnandez** 2017-12-01 21:47 UTC
Labels: Bug, Priority 3 - Low
