### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Clicqueur** [Dolibarr/dolibarr#7394] opened 2017-09-14 07:17 UTC
# Bug

## Environment
- **Version**: 6.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 5.5.38
- **Database**: MySQL or MariaDB 5.5.51-MariaDB
- **URL**: /comm/index.php?mainmenu=commercial&leftmenu=

## Report
Hello,
In commercial space I see the proposals that have been made. But when I click on it is impossible to see them and I can not get my hands on them and find them.
Would you have a solution to solve my problem?
cordially

**Comment by eldy** [comment] 2017-09-26 10:11
Can you upgrade to 6.0.1
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by simnandez** [comment] 2017-09-27 16:40
Works for me in 6.0.1

**Comment by BebZ** [comment] 2017-10-01 14:06
works on 6.0.0 beta too

**Closed as completed** 2017-12-01 23:25 UTC
Labels: Works for me / Can't reproduce
