### ISSUE TITLE
Bug: BOM_SUB_BOM blank page

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#26416] opened 2023-10-31 15:08 UTC
Hello !
# Instructions
Try to use BOM_SUB_BOM blank page

# Bug
Upgrade to Dolibarr 18.0.2 use GPAO with BOM_SUB_BOM  create a bom then the fabrication order. 
Every thing is ok
![Capture](https://github.com/Dolibarr/dolibarr/assets/24292300/518a27a1-f0fa-4975-bf40-7d0c9dd5d45e)

validate and then blank page (url -> mo_card.php?id=0)
![Capture](https://github.com/Dolibarr/dolibarr/assets/24292300/eee5261c-6008-40f1-90e4-4a89f1acae87)

## Environment
- **Version**: 18.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.2.34
- **Database**: MySQL or MariaDB 5.5.5-10.6.15-MariaDB
- **URL(s)**: /dolibarr18/mrp/mo_card.php?id=0

[*Files*]

**Comment by lamrani002** [comment] 2023-11-08 16:59
I reproduce the same process and it works for me

**Comment by dolibarr95** [comment] 2023-11-09 07:32
Hello
@lamrani002 tks for this feedback are you running Dolibarr 18.0.2 ?

**Comment by lamrani002** [comment] 2023-11-09 10:48
Hello, yes

**Comment by dolibarr95** [comment] 2023-11-09 10:51
Ok tks I will re-install a fresh 18.0.2 and test again
tks ;)

**Comment by lamrani002** [comment] 2023-11-09 11:50
no problem

**Comment by dolibarr95** [comment] 2023-11-09 14:03
Test on a new Dolibarr 18.0.2
BOM_SUB_BOM activated still same bug when I select "Générer OF enfant"
![Capture](https://github.com/Dolibarr/dolibarr/assets/24292300/702f4372-f6d4-4fd2-91b7-57ccca9a22a7)

**Comment by dolibarr95** [comment] 2023-11-09 14:09
here is my log 
```
2023-11-09 14:04:43 NOTICE  myip    --- Access to POST /18TST/mrp/mo_card.php - action=add, massaction=
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT transkey, transvalue FROM llx_overwrite_trans where (lang='fr_FR' OR lang IS NULL) AND entity IN (0, 0,1) ORDER BY lang DESC
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT m.rowid, m.type, m.module, m.fk_menu, m.fk_mainmenu, m.fk_leftmenu, m.url, m.titre, m.prefix, m.langs, m.perms, m.enabled, m.target, m.mainmenu, m.leftmenu, m.position FROM llx_menu as m WHERE m.entity IN (0,1) AND m.menu_handler IN ('eldy','all') AND m.usertype IN (0,2) ORDER BY m.position, m.rowid
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT rowid, name, label, type, size, elementtype, fieldunique, fieldrequired, param, pos, alwayseditable, perms, langs, list, printable, totalizable, fielddefault, fieldcomputed, entity, enabled, help, css, cssview, csslist FROM llx_extrafields WHERE elementtype = 'mrp_mo' ORDER BY pos
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT t.rowid,t.ref,t.label,t.bomtype,t.fk_product,t.description,t.qty,t.duration,t.fk_warehouse,t.note_public,t.note_private,t.date_creation,t.tms,t.date_valid,t.fk_user_creat,t.fk_user_modif,t.fk_user_valid,t.import_key,t.model_pdf,t.status FROM llx_bom_bom as t WHERE t.rowid = 1 LIMIT 1
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT rowid, name, label, type, size, elementtype, fieldunique, fieldrequired, param, pos, alwayseditable, perms, langs, list, printable, totalizable, fielddefault, fieldcomputed, entity, enabled, help, css, cssview, csslist FROM llx_extrafields WHERE elementtype = 'bom_bom' ORDER BY pos
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT l.rowid,l.fk_bom,l.fk_product,l.fk_bom_child,l.description,l.qty,l.qty_frozen,l.disable_stock_change,l.efficiency,l.fk_unit,l.position,l.import_key,l.fk_default_workstation FROM llx_bom_bomline as l WHERE l.fk_bom = 1 ORDER BY position ASC
2023-11-09 14:04:43 DEBUG   myip    BEGIN Transaction
2023-11-09 14:04:43 DEBUG   myip      sql=SELECT t.rowid,t.ref,t.label,t.bomtype,t.fk_product,t.description,t.qty,t.duration,t.fk_warehouse,t.note_public,t.note_private,t.date_creation,t.tms,t.date_valid,t.fk_user_creat,t.fk_user_modif,t.fk_user_valid,t.import_key,t.model_pdf,t.status FROM llx_bom_bom as t WHERE t.rowid = 1 LIMIT 1
2023-11-09 14:04:43 DEBUG   myip      sql=SELECT l.rowid,l.fk_bom,l.fk_product,l.fk_bom_child,l.description,l.qty,l.qty_frozen,l.disable_stock_change,l.efficiency,l.fk_unit,l.position,l.import_key,l.fk_default_workstation FROM llx_bom_bomline as l WHERE l.fk_bom = 1 ORDER BY position ASC
2023-11-09 14:04:43 DEBUG   myip      Mo::createCommon create
2023-11-09 14:04:43 DEBUG   myip       sql=INSERT INTO llx_mrp_mo (ref, fk_bom, mrptype, fk_product, qty, label, fk_soc, fk_project, fk_warehouse, note_public, note_private, date_creation, date_valid, fk_user_creat, fk_user_modif, date_start_planned, date_end_planned, import_key, model_pdf, status, fk_parent_line) VALUES ('', 1, 0, 1, 1, NULL, NULL, NULL, 1, NULL, NULL, '2023-11-09 14:04:43', NULL, 1, NULL, NULL, NULL, NULL, NULL, 0, NULL)
2023-11-09 14:04:43 DEBUG   myip       sql=UPDATE llx_mrp_mo SET ref = '(PROV5)' WHERE (ref = '(PROV)' OR ref = '') AND rowid = 5
2023-11-09 14:04:43 DEBUG   myip       sql=DELETE FROM llx_mrp_production WHERE fk_mo = 5
2023-11-09 14:04:43 DEBUG   myip       sql=SELECT t.rowid,t.ref,t.label,t.bomtype,t.fk_product,t.description,t.qty,t.duration,t.fk_warehouse,t.note_public,t.note_private,t.date_creation,t.tms,t.date_valid,t.fk_user_creat,t.fk_user_modif,t.fk_user_valid,t.import_key,t.model_pdf,t.status FROM llx_bom_bom as t WHERE t.rowid = 1 LIMIT 1
2023-11-09 14:04:43 DEBUG   myip       sql=SELECT l.rowid,l.fk_bom,l.fk_product,l.fk_bom_child,l.description,l.qty,l.qty_frozen,l.disable_stock_change,l.efficiency,l.fk_unit,l.position,l.import_key,l.fk_default_workstation FROM llx_bom_bomline as l WHERE l.fk_bom = 1 ORDER BY position ASC
2023-11-09 14:04:43 DEBUG   myip       MoLine::createCommon create
2023-11-09 14:04:43 DEBUG   myip        sql=INSERT INTO llx_mrp_production (fk_mo, origin_id, origin_type, position, fk_product, fk_warehouse, qty, qty_frozen, disable_stock_change, batch, role, fk_mrp_production, fk_stock_movement, date_creation, fk_user_creat, fk_user_modif, import_key, fk_default_workstation) VALUES (5, NULL, NULL, 1, 1, NULL, 1, NULL, NULL, NULL, 'toproduce', NULL, NULL, '2023-11-09 14:04:43', 1, NULL, NULL, NULL)
2023-11-09 14:04:43 DEBUG   myip       MoLine::createCommon create
2023-11-09 14:04:43 DEBUG   myip        sql=INSERT INTO llx_mrp_production (fk_mo, origin_id, origin_type, position, fk_product, fk_warehouse, qty, qty_frozen, disable_stock_change, batch, role, fk_mrp_production, fk_stock_movement, date_creation, fk_user_creat, fk_user_modif, import_key, fk_default_workstation) VALUES (5, 4, 'bomline', 1, 2, NULL, 4, NULL, NULL, NULL, 'toconsume', NULL, NULL, '2023-11-09 14:04:43', 1, NULL, NULL, NULL)
2023-11-09 14:04:43 DEBUG   myip       MoLine::createCommon create
2023-11-09 14:04:43 DEBUG   myip        sql=INSERT INTO llx_mrp_production (fk_mo, origin_id, origin_type, position, fk_product, fk_warehouse, qty, qty_frozen, disable_stock_change, batch, role, fk_mrp_production, fk_stock_movement, date_creation, fk_user_creat, fk_user_modif, import_key, fk_default_workstation) VALUES (5, 5, 'bomline', 2, 5, NULL, 1, NULL, NULL, NULL, 'toconsume', NULL, NULL, '2023-11-09 14:04:43', 1, NULL, NULL, NULL)
2023-11-09 14:04:43 DEBUG   myip    COMMIT Transaction
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT t.rowid,t.fk_bom,t.fk_product,t.fk_bom_child,t.description,t.qty,t.qty_frozen,t.disable_stock_change,t.efficiency,t.fk_unit,t.position,t.import_key,t.fk_default_workstation FROM llx_bom_bomline as t WHERE t.rowid = 4 LIMIT 1
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT rowid, name, label, type, size, elementtype, fieldunique, fieldrequired, param, pos, alwayseditable, perms, langs, list, printable, totalizable, fielddefault, fieldcomputed, entity, enabled, help, css, cssview, csslist FROM llx_extrafields WHERE elementtype = 'bom_bomline' ORDER BY pos
2023-11-09 14:04:43 DEBUG   myip    MoLine::fetchAll
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT rowid,fk_mo,origin_id,origin_type,position,fk_product,fk_warehouse,qty,qty_frozen,disable_stock_change,batch,role,fk_mrp_production,fk_stock_movement,date_creation,tms,fk_user_creat,fk_user_modif,import_key,fk_default_workstation FROM llx_mrp_production as t WHERE 1 = 1 AND (origin_id LIKE '%4%') ORDER BY rowid DESC LIMIT 1
2023-11-09 14:04:43 DEBUG   myip    BEGIN Transaction
2023-11-09 14:04:43 DEBUG   myip      sql=SELECT t.rowid,t.ref,t.label,t.bomtype,t.fk_product,t.description,t.qty,t.duration,t.fk_warehouse,t.note_public,t.note_private,t.date_creation,t.tms,t.date_valid,t.fk_user_creat,t.fk_user_modif,t.fk_user_valid,t.import_key,t.model_pdf,t.status FROM llx_bom_bom as t WHERE t.rowid = 2 LIMIT 1
2023-11-09 14:04:43 DEBUG   myip      sql=SELECT l.rowid,l.fk_bom,l.fk_product,l.fk_bom_child,l.description,l.qty,l.qty_frozen,l.disable_stock_change,l.efficiency,l.fk_unit,l.position,l.import_key,l.fk_default_workstation FROM llx_bom_bomline as l WHERE l.fk_bom = 2 ORDER BY position ASC
2023-11-09 14:04:43 DEBUG   myip      Mo::createCommon create
2023-11-09 14:04:43 DEBUG   myip       sql=INSERT INTO llx_mrp_mo (ref, fk_bom, mrptype, fk_product, qty, label, fk_soc, fk_project, fk_warehouse, note_public, note_private, date_creation, date_valid, fk_user_creat, fk_user_modif, date_start_planned, date_end_planned, import_key, model_pdf, status, fk_parent_line) VALUES ('', 2, 0, 2, 4, NULL, NULL, NULL, 1, NULL, NULL, '2023-11-09 14:04:43', NULL, 1, NULL, NULL, NULL, NULL, NULL, 0, 16)
2023-11-09 14:04:43 DEBUG   myip       sql=UPDATE llx_mrp_mo SET ref = '(PROV6)' WHERE (ref = '(PROV)' OR ref = '') AND rowid = 6
2023-11-09 14:04:43 DEBUG   myip       sql=DELETE FROM llx_mrp_production WHERE fk_mo = 6
2023-11-09 14:04:43 DEBUG   myip       sql=SELECT t.rowid,t.ref,t.label,t.bomtype,t.fk_product,t.description,t.qty,t.duration,t.fk_warehouse,t.note_public,t.note_private,t.date_creation,t.tms,t.date_valid,t.fk_user_creat,t.fk_user_modif,t.fk_user_valid,t.import_key,t.model_pdf,t.status FROM llx_bom_bom as t WHERE t.rowid = 2 LIMIT 1
2023-11-09 14:04:43 DEBUG   myip       sql=SELECT l.rowid,l.fk_bom,l.fk_product,l.fk_bom_child,l.description,l.qty,l.qty_frozen,l.disable_stock_change,l.efficiency,l.fk_unit,l.position,l.import_key,l.fk_default_workstation FROM llx_bom_bomline as l WHERE l.fk_bom = 2 ORDER BY position ASC
2023-11-09 14:04:43 DEBUG   myip       MoLine::createCommon create
2023-11-09 14:04:43 DEBUG   myip        sql=INSERT INTO llx_mrp_production (fk_mo, origin_id, origin_type, position, fk_product, fk_warehouse, qty, qty_frozen, disable_stock_change, batch, role, fk_mrp_production, fk_stock_movement, date_creation, fk_user_creat, fk_user_modif, import_key, fk_default_workstation) VALUES (6, NULL, NULL, 1, 2, NULL, 4, NULL, NULL, NULL, 'toproduce', NULL, NULL, '2023-11-09 14:04:43', 1, NULL, NULL, NULL)
2023-11-09 14:04:43 DEBUG   myip       MoLine::createCommon create
2023-11-09 14:04:43 DEBUG   myip        sql=INSERT INTO llx_mrp_production (fk_mo, origin_id, origin_type, position, fk_product, fk_warehouse, qty, qty_frozen, disable_stock_change, batch, role, fk_mrp_production, fk_stock_movement, date_creation, fk_user_creat, fk_user_modif, import_key, fk_default_workstation) VALUES (6, 1, 'bomline', 1, 3, NULL, 1, NULL, NULL, NULL, 'toconsume', NULL, NULL, '2023-11-09 14:04:43', 1, NULL, NULL, NULL)
2023-11-09 14:04:43 DEBUG   myip       MoLine::createCommon create
2023-11-09 14:04:43 DEBUG   myip        sql=INSERT INTO llx_mrp_production (fk_mo, origin_id, origin_type, position, fk_product, fk_warehouse, qty, qty_frozen, disable_stock_change, batch, role, fk_mrp_production, fk_stock_movement, date_creation, fk_user_creat, fk_user_modif, import_key, fk_default_workstation) VALUES (6, 2, 'bomline', 2, 4, NULL, 1, NULL, NULL, NULL, 'toconsume', NULL, NULL, '2023-11-09 14:04:43', 1, NULL, NULL, NULL)
2023-11-09 14:04:43 DEBUG   myip    COMMIT Transaction
2023-11-09 14:04:43 DEBUG   myip    BEGIN Transaction
2023-11-09 14:04:43 DEBUG   myip     Mo::add_object_linked
2023-11-09 14:04:43 DEBUG   myip     sql=INSERT INTO llx_element_element (fk_source, sourcetype, fk_target, targettype) VALUES (5, 'mo', 6, 'mo')
2023-11-09 14:04:43 DEBUG   myip    COMMIT Transaction
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT t.rowid,t.fk_bom,t.fk_product,t.fk_bom_child,t.description,t.qty,t.qty_frozen,t.disable_stock_change,t.efficiency,t.fk_unit,t.position,t.import_key,t.fk_default_workstation FROM llx_bom_bomline as t WHERE t.rowid = 5 LIMIT 1
2023-11-09 14:04:43 DEBUG   myip    MoLine::fetchAll
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT rowid,fk_mo,origin_id,origin_type,position,fk_product,fk_warehouse,qty,qty_frozen,disable_stock_change,batch,role,fk_mrp_production,fk_stock_movement,date_creation,tms,fk_user_creat,fk_user_modif,import_key,fk_default_workstation FROM llx_mrp_production as t WHERE 1 = 1 AND (origin_id LIKE '%5%') ORDER BY rowid DESC LIMIT 1
2023-11-09 14:04:43 DEBUG   myip    BEGIN Transaction
2023-11-09 14:04:43 DEBUG   myip      sql=SELECT t.rowid,t.ref,t.label,t.bomtype,t.fk_product,t.description,t.qty,t.duration,t.fk_warehouse,t.note_public,t.note_private,t.date_creation,t.tms,t.date_valid,t.fk_user_creat,t.fk_user_modif,t.fk_user_valid,t.import_key,t.model_pdf,t.status FROM llx_bom_bom as t WHERE t.rowid = 3 LIMIT 1
2023-11-09 14:04:43 DEBUG   myip      sql=SELECT l.rowid,l.fk_bom,l.fk_product,l.fk_bom_child,l.description,l.qty,l.qty_frozen,l.disable_stock_change,l.efficiency,l.fk_unit,l.position,l.import_key,l.fk_default_workstation FROM llx_bom_bomline as l WHERE l.fk_bom = 3 ORDER BY position ASC
2023-11-09 14:04:43 DEBUG   myip      Mo::createCommon create
2023-11-09 14:04:43 DEBUG   myip       sql=INSERT INTO llx_mrp_mo (ref, fk_bom, mrptype, fk_product, qty, label, fk_soc, fk_project, fk_warehouse, note_public, note_private, date_creation, date_valid, fk_user_creat, fk_user_modif, date_start_planned, date_end_planned, import_key, model_pdf, status, fk_parent_line) VALUES ('', 3, 0, 5, 1, NULL, NULL, NULL, 1, NULL, NULL, '2023-11-09 14:04:43', NULL, 1, NULL, NULL, NULL, NULL, NULL, 0, 17)
2023-11-09 14:04:43 DEBUG   myip       sql=UPDATE llx_mrp_mo SET ref = '(PROV7)' WHERE (ref = '(PROV)' OR ref = '') AND rowid = 7
2023-11-09 14:04:43 DEBUG   myip       sql=DELETE FROM llx_mrp_production WHERE fk_mo = 7
2023-11-09 14:04:43 DEBUG   myip       sql=SELECT t.rowid,t.ref,t.label,t.bomtype,t.fk_product,t.description,t.qty,t.duration,t.fk_warehouse,t.note_public,t.note_private,t.date_creation,t.tms,t.date_valid,t.fk_user_creat,t.fk_user_modif,t.fk_user_valid,t.import_key,t.model_pdf,t.status FROM llx_bom_bom as t WHERE t.rowid = 3 LIMIT 1
2023-11-09 14:04:43 DEBUG   myip       sql=SELECT l.rowid,l.fk_bom,l.fk_product,l.fk_bom_child,l.description,l.qty,l.qty_frozen,l.disable_stock_change,l.efficiency,l.fk_unit,l.position,l.import_key,l.fk_default_workstation FROM llx_bom_bomline as l WHERE l.fk_bom = 3 ORDER BY position ASC
2023-11-09 14:04:43 DEBUG   myip       MoLine::createCommon create
2023-11-09 14:04:43 DEBUG   myip        sql=INSERT INTO llx_mrp_production (fk_mo, origin_id, origin_type, position, fk_product, fk_warehouse, qty, qty_frozen, disable_stock_change, batch, role, fk_mrp_production, fk_stock_movement, date_creation, fk_user_creat, fk_user_modif, import_key, fk_default_workstation) VALUES (7, NULL, NULL, 1, 5, NULL, 1, NULL, NULL, NULL, 'toproduce', NULL, NULL, '2023-11-09 14:04:43', 1, NULL, NULL, NULL)
2023-11-09 14:04:43 DEBUG   myip       MoLine::createCommon create
2023-11-09 14:04:43 DEBUG   myip        sql=INSERT INTO llx_mrp_production (fk_mo, origin_id, origin_type, position, fk_product, fk_warehouse, qty, qty_frozen, disable_stock_change, batch, role, fk_mrp_production, fk_stock_movement, date_creation, fk_user_creat, fk_user_modif, import_key, fk_default_workstation) VALUES (7, 3, 'bomline', 1, 6, NULL, 50, NULL, NULL, NULL, 'toconsume', NULL, NULL, '2023-11-09 14:04:43', 1, NULL, NULL, NULL)
2023-11-09 14:04:43 DEBUG   myip    COMMIT Transaction
2023-11-09 14:04:43 DEBUG   myip    BEGIN Transaction
2023-11-09 14:04:43 DEBUG   myip     Mo::add_object_linked
2023-11-09 14:04:43 DEBUG   myip     sql=INSERT INTO llx_element_element (fk_source, sourcetype, fk_target, targettype) VALUES (5, 'mo', 7, 'mo')
2023-11-09 14:04:43 DEBUG   myip    COMMIT Transaction
2023-11-09 14:04:43 INFO    myip    --- End access to /18TST/mrp/mo_card.php
2023-11-09 14:04:43 DEBUG   myip    - This is an already logged session. _SESSION['dol_login']=MyLogin _SESSION['dol_entity']=1
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT u.rowid, u.lastname, u.firstname, u.employee, u.gender, u.civility as civility_code, u.birth, u.email, u.personal_email, u.job, u.socialnetworks, u.signature, u.office_phone, u.office_fax, u.user_mobile, u.personal_mobile, u.address, u.zip, u.town, u.fk_state as state_id, u.fk_country as country_id, u.admin, u.login, u.note_private, u.note_public, u.pass, u.pass_crypted, u.pass_temp, u.api_key, u.fk_soc, u.fk_socpeople, u.fk_member, u.fk_user, u.ldap_sid, u.fk_user_expense_validator, u.fk_user_holiday_validator, u.statut as status, u.lang, u.entity, u.datec as datec, u.tms as datem, u.datelastlogin as datel, u.datepreviouslogin as datep, u.flagdelsessionsbefore, u.iplastlogin, u.ippreviouslogin, u.datelastpassvalidation, u.datestartvalidity, u.dateendvalidity, u.photo as photo, u.openid as openid, u.accountancy_code, u.thm, u.tjm, u.salary, u.salaryextra, u.weeklyhours, u.color, u.dateemployment, u.dateemploymentend, u.fk_warehouse, u.ref_ext, u.default_range, u.default_c_exp_tax_cat, u.national_registration_number, u.ref_employee, c.code as country_code, c.label as country, d.code_departement as state_code, d.nom as state FROM llx_user as u LEFT JOIN llx_c_country as c ON u.fk_country = c.rowid LEFT JOIN llx_c_departements as d ON u.fk_state = d.rowid WHERE u.entity IN (0, 1) AND u.login = 'MyLogin' ORDER BY u.entity ASC
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT rowid, name, label, type, size, elementtype, fieldunique, fieldrequired, param, pos, alwayseditable, perms, langs, list, printable, totalizable, fielddefault, fieldcomputed, entity, enabled, help, css, cssview, csslist FROM llx_extrafields WHERE elementtype = 'user' ORDER BY pos
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT param, value FROM llx_user_param WHERE fk_user = 1 AND entity = 1
2023-11-09 14:04:43 DEBUG   myip    DefaultValues::fetchAll
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT rowid,type,user_id,page,param,value FROM llx_default_values as t WHERE 1 = 1 AND (t.user_id IN (0,1) AND entity IN (0,1))
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT DISTINCT r.module, r.perms, r.subperms FROM llx_user_rights as ur, llx_rights_def as r WHERE r.id = ur.fk_id AND r.entity = 1 AND ur.entity = 1 AND ur.fk_user= 1 AND r.perms IS NOT NULL
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT DISTINCT r.module, r.perms, r.subperms FROM llx_usergroup_rights as gr, llx_usergroup_user as gu, llx_rights_def as r WHERE r.id = gr.fk_id AND gr.entity = 1 AND gu.entity IN (0,1) AND r.entity = 1 AND gr.fk_usergroup = gu.fk_usergroup AND gu.fk_user = 1 AND r.perms IS NOT NULL
2023-11-09 14:04:43 NOTICE  myip    --- Access to GET /18TST/mrp/mo_card.php - action=, massaction=
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT transkey, transvalue FROM llx_overwrite_trans where (lang='fr_FR' OR lang IS NULL) AND entity IN (0, 0,1) ORDER BY lang DESC
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT m.rowid, m.type, m.module, m.fk_menu, m.fk_mainmenu, m.fk_leftmenu, m.url, m.titre, m.prefix, m.langs, m.perms, m.enabled, m.target, m.mainmenu, m.leftmenu, m.position FROM llx_menu as m WHERE m.entity IN (0,1) AND m.menu_handler IN ('eldy','all') AND m.usertype IN (0,2) ORDER BY m.position, m.rowid
2023-11-09 14:04:43 DEBUG   myip    sql=SELECT rowid, name, label, type, size, elementtype, fieldunique, fieldrequired, param, pos, alwayseditable, perms, langs, list, printable, totalizable, fielddefault, fieldcomputed, entity, enabled, help, css, cssview, csslist FROM llx_extrafields WHERE elementtype = 'mrp_mo' ORDER BY pos
2023-11-09 14:04:43 INFO    myip    --- End access to /18TST/mrp/mo_card.php

```

**Comment by dolibarr95** [comment] 2023-11-09 14:27
Hello
@eldy or @lamrani002 can you please reopen this issue?

**Comment by dolibarr95** [comment] 2023-11-09 14:33
@lamrani002 tks 😎

**Comment by lamrani002** [comment] 2023-11-09 14:33
I'll check that and get back to you

**Comment by dolibarr95** [comment] 2023-11-09 14:35
tks again.
https://www.dolibarr.fr/forum/t/bom-sub-bom-generer-of-enfant/44683

**Comment by atm-thibaultf** [comment] 2023-11-09 15:45
@dolibarr95 
I think I find the problem and propose a fix to correct it.

**Comment by eldy** [comment] 2023-12-28 12:42
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by AlbanDurrheimer** [comment] 2024-01-11 10:49
Hello,  
I am currently testing the sub BOM with the develop version (20.0.0-alpha), and I can confirm that the issue still persists.  
Url: `/mrp/mo_card.php?id=0`  
![Screenshot 2024-01-11 at 11-45-37 Ordre de fabrication - Fiche](https://github.com/Dolibarr/dolibarr/assets/21126730/6be223e7-4f27-4b92-9728-87b59dfa28d8)

**Closed as completed** 2024-01-31 18:20 UTC
Labels: Works for me / Can't reproduce
