### ISSUE TITLE
no email sent when proposal is signed online

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#20204] opened 2022-02-25 20:51 UTC
### Bug

On the bottom of validated proposal (/comm/propal/card.php?id=xxx) there is a link that you can send to the customer to sign online:

There's no email sent when the proposal has been signed online (/public/onlinesign/newonlinesign.php?source=proposal&ref=), even if the template of "Customer proposal closed signed" is setup in the notification module.
It works well when you click on "set accepted/refused -> signed" in the proposal screen (/comm/propal/card.php?id=xxx)

**Comment by RANDOMLY-OBFUSCATED** [comment] 2022-03-19 13:40
Hello,
I confirm that and it would be a really (realy) useful feature.
As I can understand:
- the event  notification  on "online signing" does not exist (not present  as event in notification's list)
- "validated" and "closed/signed" are other object than online signing
So it's not a bug, it's a missing feature.
Thanks @Arre8

**Comment by matDOTviguier** [comment] 2022-03-22 13:25
I confirm, and close my #20432 as a duplicated.

**Comment by Arre8** [comment] 2022-03-22 13:29
@18info you're right, it's a feature request, not a bug, how can i update the label ?

Tested on 15.0.1: same

**Comment by matDOTviguier** [comment] 2022-03-22 14:00
I apologize, but letting a proposal closed signed without any notification _**is a bug**_. Because once the notification is set, it _**should not**_ be triggered without notifying something.

@18info, @Arr8, I hardly disagree, because a proposal cannot be signed online and not closed signed. It's a bug because, here on 15.0.1, the online signature -**implies**- closed/signed state to be triggered.

Being a regression (now our system can validate proposal without notification while notification is set on "event") I up vote for the _bug_ tag. I think it is the triggered event that has just been forgotten.

**Comment by Arre8** [comment] 2022-03-22 14:06
either a bug or a feature request ... it's a **problem** :)

**Comment by BebZ** [comment] 2022-03-22 17:23
Hello
the bug is that it is not closed signed (so it should trigger a notification if activated) 
the feature request is to have an email to receive the notification it was signed online 
;)

**Comment by matDOTviguier** [comment] 2022-03-22 17:31
The feature request is to receive a notifation when the online signing website is visited, and not signed in 5 min or less when it's raining. Otherwise, it is a bug !

**Comment by Arre8** [comment] 2022-03-22 17:36
@BebZ so : i'll ask to add a label "Bug request" : everybody will be happy 😄

**Comment by RANDOMLY-OBFUSCATED** [comment] 2022-03-22 20:22
> The feature request is to receive a notifation when the online signing website is visited, and not signed in 5 min or less when it's raining. Otherwise, it is a bug !

nop, receive a mail when a propal is signed. This notification does not exist in the notification's list.

Again, really better when the propal become "signed/closed/ready to invoice" after online signing but it's a side "bug|request|problem".

**Comment by RANDOMLY-OBFUSCATED** [comment] 2022-03-22 20:28
> @18info you're right, it's a feature request, not a bug, how can i update the label ?
> 
> Tested on 15.0.1: same

If you can't, maybe a "rights issue". knock-knock an admin?
I just found https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#editing-a-label :-/

**Comment by RANDOMLY-OBFUSCATED** [comment] 2023-02-23 13:11
Hi!
close to a year after, is there something new here? Thanks.

**Comment by freechelmi** [comment] 2023-02-23 14:19
Did you reproduce the problem on v16 ?

**Comment by RANDOMLY-OBFUSCATED** [comment] 2023-02-23 14:35
Does the feature's added? (nothing in change logs)
I can't find some new switch in /admin/notification.php on 16.0.4.

**Comment by ksar-ksar** [comment] 2023-10-18 19:19
Hello,

Is it still the case on V18 ?

**Comment by RANDOMLY-OBFUSCATED** [comment] 2023-10-24 18:52
Hello,
I 'm going to check it asap. Thanks for the follow-up.

**Comment by RANDOMLY-OBFUSCATED** [comment] 2023-11-14 11:21
It stills… No new function on that

**Comment by freechelmi** [comment] 2023-11-14 12:35
Indeed very important feature because client calls to ask why the invoice was not sent although he validate the quote ....

**Comment by RANDOMLY-OBFUSCATED** [comment] 2023-11-15 07:56
> Indeed very important feature because client calls to ask why the invoice was not sent although he validate the quote ....
@freechelmi 
Maybe because the invoice is another process than quote? :)

**Comment by freechelmi** [comment] 2023-11-15 10:33
> > Indeed very important feature because client calls to ask why the invoice was not sent although he validate the quote ....
> > @freechelmi
> > Maybe because the invoice is another process than quote? :)

I meant that as a was not notified of the signature , I did not send the invoice :-)

**Comment by RANDOMLY-OBFUSCATED** [comment] 2023-11-15 11:14
So, that's the point… ;)

**Comment by apio-sys** [comment] 2023-11-30 17:10
I confirm, with notifications module enabled with PROPAL_VALIDATE set with a valid email recipient, no email is triggered when a client signed online a proposal. This is somewhat disturbing as Michel @freechelmi indicated, you get a phone call asking you to follow up on a signed proposal and you don't look at them all all the time... Or should it be "Validation proposition commerciale client" above in the notifications section that a template should be implemented to make it work ? But I wonder, that won't send to admin but to client right ? Running latest stable 18.0.3.

**Comment by apio-sys** [comment] 2024-01-10 21:17
@18info I don't think issue #26596 is directly related. This issue was/is about the fact of getting an email notification if a customer signed a proposal online (which you wouldn't know about unless going to check manually the status of your current proposals). From my end I notice this now works, running latest stable 18.04. Not sure when this started working or if we all on this ticket missed out the correct configuration option.

Just to clarify I have:
- Notifications module enabled;
- Configure a "from" email address;
- In the bottom list of fixed emails, go to PROPAL_CLOSE_SIGNED and enter a recipient email address to receive the alert eventually depending on the amount.

Sign a proposal (or better sell something ;-) ) and you will get the email notification so you know you have something pending to deliver/invoice/whatever. I think this can now be closed if all agree.

**Comment by RANDOMLY-OBFUSCATED** [comment] 2024-01-11 11:02
Hello!
about #26596, it's just to indicate there is already an issue here about notification sending.

I just tested and it works. I never seen any information in change logs, do you?

Is it normal that __THIRDPARTY_NAME__ is not replaced in e-mail models (online signing notification)?

I think yes, we can close this issue. Many thanks!

**Comment by apio-sys** [comment] 2024-01-11 11:19
No I didn't see any referral to this in the ChangeLog. It just works now (I think since 18.0.4). Somebody just fixed it which is already great. Since the online signing notification is in the section of fixed notifications, I don't think you can use vars here. I just noticed this was also a duplicate of #21941 which was closed in September 2022 already. So let's close here. If the use of variables in such notifications is something wanted, I think you need to raise a separate issue to avoid confusion.

**Comment by apio-sys** [comment] 2024-01-11 11:19
@Arre8 can you also confirm and close the issue if working OK for you?

**Comment by PascalB67** [comment] 2024-01-27 18:01
Hello, I came across this thread.
The companies I work for are very interested in this module. A simple signature, without a token. I implemented it by modifying the code a little so that the signature goes at the bottom right of the contract, which is not the case. Another point, the name of the signatory is not included (I didn't look too hard either).
Just for this to be perfect, it would be necessary for the signed contract event to be able to be intercepted in order to trigger a notification.
By the way, it's always a pleasure, congratulations for 18.04 if you want beta testers for the signature, I have installations at different levels and I can devote some time to you.
Best regards

**Comment by apio-sys** [comment] 2024-01-27 18:47
Hi @PascalB67 I think the issue (no email sent when proposal is signed online) in this post has been solved. Any additions should be logged separately to avoid confusion. From my end this works perfectly as designed now. But could maybe be improved, but it's no longer a "bug" which it was previously. @eldy I think this is closed here for now.

**Comment by eldy** [comment] 2024-01-27 18:58
> Hi @PascalB67 I think the issue (no email sent when proposal is signed online) in this post has been solved. Any additions should be logged separately to avoid confusion. From my end this works perfectly as designed no. But could maybe be improved, but it's no longer a "bug" which it was previously. @eldy I think this is closed here for now.

Thanks for this feedback.

**Closed as completed** 2024-01-27 18:59 UTC
Labels: Bug

**Comment by PascalB67** [comment] 2024-01-28 08:58
Hi @eldy, thank you for your time.

I'm taking the time to clarify a few things,

When a contract is signed
The signature is at the bottom left, instead of at the bottom right (Name of the signatory)
The free text (name of the signatory for example, is not included in the pdf)
The implementation of electronic signatures in contracts has probably not yet been done.

For commercial proposals (we're almost there)
When a commercial proposal is signed
The signature is correctly aligned at the bottom right
The free text (name of the signatory for example, is correctly placed)
Email received during testing (Address of Sales Representative provided)
Closed customer proposal signed AND Validation of customer commercial proposal
In both cases the emails are sent, but the attached PDF is not the signed one

Well then what I want is just an email for validation of the contract by the customer 😊
