### ISSUE TITLE
FEATURE REQUEST: Do not allow Supplier invoice creation if thirdparty has no country set

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2498] opened 2015-03-29 13:37 UTC
Type: Feature request

When we create a supplier invoice of a supplier that has no country set, we will see this warning in objectline_create.

It would be better if we warn the user before creating the invoice.

![captura de pantalla 2015-03-29 a las 15 37 05](https://cloud.githubusercontent.com/assets/168744/6885634/7e96ebb4-d629-11e4-9097-140a8212215b.png)

**Comment by eldy** [comment] 2015-03-29 16:18
Duplicate of #2499, so closed

**Closed as completed by eldy** 2015-03-29 16:18 UTC
Labels: Feature request
