### ISSUE TITLE
BUG: API REST Project PUT /projects/{id} don't work

### ISSUE THREAD

**Issue by ludini17** [Dolibarr/dolibarr#11447] opened 2019-07-02 18:06 UTC
# Bug
When try to update any field, do nothing. no error but no update.

## Environment
- **Version**: 10.0
- **OS**: Ubuntu 18.04
- **Web server**: Apache/2.4.29 (Ubuntu)
- **PHP**: 7.2.19-0ubuntu0.18.04.1
- **Database**: MySQL or MariaDB 5.7.26-0ubuntu0.18.04.1
- **URL(s)**: /api/index.php/explorer/#!/projects/updateProjects
- **Multicompany**: Yes

## Steps to reproduce the behavior

- Create a project (if don't have any)
- go to api explorer and insert the user api key, with all the permisions for all the modules.
- go to /api/index.php/explorer/#!/projects/updateProjects and insert the project id
- in the field updateProjectsModel write:

**{
  "title": "newtitle","description":"newdescription" 
}**

This must change the two values, the response code is 200, all ok, but nothing change in the database.

I tryed with the multicompany module disabled and dolibarr have the same behavior.

**Comment by eldy** [comment] 2019-08-01 11:05
I can't reproduce. Can you enable module syslog and tell if you see someting strange into the dolibarr.log file ?

**Comment by pstructures** [comment] 2019-08-13 10:58
Hi, I am having the same trouble eldy.  I have posted in the forum with the issue, although mine is based on the agendaevent, and I had to edit the api.class file.  I have copied and pasted my issue below including my environment data.

DOLIBARR ENVIRONMENT
- Version: 10.0.1
- Operating System: [Server OS type and version]
- Web Server: Litespeed, Linux varda.uksrv.co.uk 3.10.0-962.3.2.lve1.5.24.5.el7.x86_64 #1 SMP Thu Nov 22 09:42:49 EST 2018 x86_64
- PHP: 7.3.8
- Database: MySQL or MariaDB 5.5.5-10.2.26-MariaDB-log-cll-lve
- URL(s): pstructures.com/doli/api/index.php/agendaevents/

Hi all.

I am having some trouble with the API when related to Agendaevents. I can create, fetch and delete through the API, but when I use the PUT method (Update) the object is returned unchanged. It is also worth noting that I have uncommented the update section in the file (api_agendaevents.class.php) in order to get the section to show anythign at all for the PUT method in the API explorer.

Please can someone advise as to the issue and whether or not that this is a bug that will be rectified in a later release.

**Comment by ludini17** [comment] 2019-08-26 15:53
hi, sorry for late reply, hollidays :-)

The dolibarr log does not provide more information, but  the API works in some fields, but not all.

fields that works:
title
description
lines

fieds that **NOT WORK**:
note_public
note_private

when I opened the bug, I got confused from the list and put the ones that worked. Sorry.

I don't tested all the fields.

**Comment by pstructures** [comment] 2019-08-26 15:58
Hi there,

No problem with the delay. I have managed to get the fields working in the api having modified the api class and the project class files.

I was also having a problem with the interventions api, as there wasn't many routes set up to work. I have since added various routes such as updating lines and updating the intervention. I will shortly be creating a pull request with the updated code. Hope that's ok.

I am very happy with dolibarr and am keen to do what I can to help with the project.

Matt



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by ludini17** [comment] 2019-12-03 15:32
hi!! Any news about this? it's solved in 10.3? i don't see anything about this in the changelog, and the bug it's still open...

Anyone can reproduce the bug?

BR

**Comment by egils-consulting** [comment] 2020-08-02 08:57
related to #14342

**Comment by dpriskorn** [comment] 2020-08-13 20:52
This is still a bug IMO. I have also had problems in v12 with the notes. We really should fix this and make good unit tests that catches this kind of bugs.

**Comment by ksar-ksar** [comment] 2021-02-19 09:43
Hello,

Should be fixed in V13 : https://github.com/Dolibarr/dolibarr/commit/7149cbb532bf516ebeee4cfecdde7c56a205a61b

Could you confirm ?

**Comment by ksar-ksar** [comment] 2021-03-11 21:24
Hi,

You can re-open the issue if it is still relevant

**Closed as completed by ksar-ksar** 2021-03-11 21:24 UTC
Labels: Works for me / Can't reproduce, Bug
