### ISSUE TITLE
mysqldump shows a warning since MySQL 5.6

### ISSUE THREAD

**Issue by ab-distrib** [Dolibarr/dolibarr#6049] opened 2016-11-28 12:48 UTC
# Environment
- **Version**: 3.9.3
- **OS**: Windows NT
- **Web server**: Apache/2.4.23 (Win64) PHP/7.0.10
- **PHP**: apache2handler 7.0.10
- **Database**: MySQL or MariaDB 5.7.14
- **URL**: /dolibarr/htdocs/admin/tools/dolibarr_export.php

# Report
Saving Dolibarr's Database

1. When trying to save database, warning appears:
Using a password on the common line interface can be insecure.
Backup used to work before upgrade to 3.9.3

2. Dolibarr keeps in mind the old installation path: 
c:\dolibarr\bin\mysql\mysql5.0.45\/bin/mysqldump
whereas it is currently 
C:\wamp64\bin\mysql\mysql5.7.14\bin
![capture](https://cloud.githubusercontent.com/assets/22303438/20668841/335fe32a-b571-11e6-9343-2a2903a41e76.PNG)

**Comment by rdoursenaud** [comment] 2017-01-20 15:45
This is not a bug. It's a feature of mysqldump since MySQL 5.6.
I don't think It can be fixed on our side.

Plus since it's just a warning, it can be ignored and shouldn't impede the dump's creation.

**Comment by atm-maxime** [comment] 2019-05-18 23:40
Too old version, please upgrade and reopen if needed.

**Closed as completed by atm-maxime** 2019-05-18 23:40 UTC
