### ISSUE TITLE
Bug:  A non-numeric value encountered

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#14219] opened 2020-07-11 19:49 UTC
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]
Warning: A non-numeric value encountered in /.../.../.../htdocs/compta/paiement.php on line 139

Warning: Cannot modify header information - headers already sent by (output started at /.../.../.../htdocs/compta/paiement.php:139) in /.../.../.../htdocs/main.inc.php on line 1110

## Environment
- **Version**: 12.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /compta/paiement.php

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Capture](https://user-images.githubusercontent.com/52134143/87232580-85a66d00-c3f2-11ea-8558-1fc00d04019f.PNG)

**Comment by eldy** [comment] 2020-08-23 16:58
Duplicate of #14352

**Closed as completed** 2020-08-23 16:58 UTC
Labels: Bug
