### ISSUE TITLE
Bug: members section it is not possible to send an email.

### ISSUE THREAD

**Issue by FeliceCor** [Dolibarr/dolibarr#13513] opened 2020-04-06 17:25 UTC
# Bug
from the members section it is not possible to send an email, it is not possible to cancel sending email.

## Environment
- **Version**: 11.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.16
- **Database**: MySQL or MariaDB 5.5.5-10.3.22-MariaDB
- **URL(s)**: /htdocs/adherents/card.php?id=1&action=presend&mode=init

## Expected and actual behavior
In the third party tab the sending of emails works regularly, while from the members section, member tab it is not possible to send an email and the "cancel" sending email function does not work.
the click produces error 403 as an attached screenshot

![Selezione_035](https://user-images.githubusercontent.com/25404180/78586637-00804a80-783c-11ea-959e-28914596aaef.jpg)

**Comment by atm-maxime** [comment] 2020-04-12 08:27
Hi.
Sorry can't reproduce. Can you add a screenshot of the page just before your 403 error ?

**Comment by dpriskorn** [comment] 2020-08-07 18:54
Something is wrong with your file permissions or apache setup. This is not related to core. Ask help in the forums or hire someone to investigate your installation. Closing.

**Closed as completed by dpriskorn** 2020-08-07 18:54 UTC
Labels: Works for me / Can't reproduce
