### ISSUE TITLE
Search societe screen blank

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#16186] opened 2021-02-05 22:58 UTC
# Bug
when searching the third shows blank page 

## Environment
- **Version**: 13.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /societe/list.php?sall=corbrand

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![page blank](https://user-images.githubusercontent.com/53640168/107097754-a6de0900-67db-11eb-9050-15b7339cd722.jpg)

**Comment by eldy** [comment] 2021-02-05 23:42
Do you have something suspicious on your error.log file ?

**Comment by leninrivas** [comment] 2021-02-06 03:50
Hello.
En the error_log nothing suspicious.  It happens with some societes. Atach video. For example Corbra

https://user-images.githubusercontent.com/53640168/107108232-6ba40000-6804-11eb-85cf-ce1580f19a88.mp4

**Comment by eldy** [comment] 2021-02-10 01:30
Did you install external modules ? Can you disables them all and retry ?

**Comment by jfchadeyron** [comment] 2021-02-10 09:28
I had exactly same issue. Resolved with disabling the "process" module (version 10.0.+2.2.0)

**Comment by jfchadeyron** [comment] 2021-02-10 13:35
Same issue from clean install dolibarr 13 and activate almost modules (no external modules).
Try with firefox and safari : same problem

**Comment by leninrivas** [comment] 2021-02-11 05:23
All external modules disabled y the same problem. Some searches fail.

**Comment by TheTrueTom** [comment] 2021-02-11 07:24
Same problem here on two different installs, no external module installed.
The problem is very inconsistent and I don't anything in the logs.

**Comment by jfchadeyron** [comment] 2021-02-11 13:30
Having "htdocs" folder as root folder of web server causing this bug ?

**Comment by leninrivas** [comment] 2021-02-11 14:11
Another symptom. If the search has fewer characters, it works normally.

![111_2](https://user-images.githubusercontent.com/53640168/107647393-1d9a5c80-6c49-11eb-9984-cc424c95d5ce.jpg)

When the search characters are increased, the blank screen appears.

![2](https://user-images.githubusercontent.com/53640168/107647557-4a4e7400-6c49-11eb-8a21-4c5a9fe7df73.jpg)

**Comment by TheTrueTom** [comment] 2021-02-11 14:17
This bug has found a workaround and maybe a solution here : #16125 
The solution proposed worked for me.

**Comment by jfchadeyron** [comment] 2021-02-11 14:23
Fixed too for me with this same workaround :  https://github.com/Dolibarr/dolibarr/issues/16125

**Comment by leninrivas** [comment] 2021-02-11 17:47
Thankyou. Solved, Tested Dolibarr 13.0.0

**Closed as completed** 2021-02-11 17:49 UTC
Labels: Bug or PR need more information
