### ISSUE TITLE
Product error not inserting nothing button

### ISSUE THREAD

**Issue by mariamanc28** [Dolibarr/dolibarr#3677] opened 2015-10-06 09:22 UTC
hi, with updated to v erssion 3.8, the section product not run correctly: i cannot insert a new product because the mask finished on product cost and not there is nothing button for confirm insert, in other thebar for paging appear not inloine the number but all number with br, then at the head i have attached for that problem, but the product problem is more urgent. i cannot add nothing more. i have oblyon_menu menu installed in use
![cattura](https://cloud.githubusercontent.com/assets/12257498/10304771/72a16b34-6c1c-11e5-9ace-09a7309abe88.JPG)

**Comment by rdoursenaud** [comment] 2015-10-15 09:12
I think the problem is in the external unsupported theme.
Could you please retry using the supported eldy theme.
If there's no issue, contact the theme developer for an update.
Anyhow, please let us know.

**Comment by marcosgdf** [comment] 2017-04-09 11:31
Hi, can you please close this issue? It is about a 3.8 version, which is not supported anymore. Please try latest version and open a new bug if it still does not work

**Closed as completed** 2017-04-14 10:54 UTC
Labels: Works for me / Can't reproduce
