### ISSUE TITLE
3.9.2 No control to avoid billing an order twice

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#5356] opened 2016-06-16 06:41 UTC
# Bug

you can bill an order several times, no controll is made
## Environment
- **Version**: 3.9
## Expected and actual behavior

An order can be billed several times without any controll or warning. This is a functionnal issue.
At least user should be warned that ther are allready invoices (with the total amount of them) to avoid creating a second (or more) invoice for a billed order (may be also true for proposals ...)
## Steps to reproduce the behavior

On a validated order create a bill from order validate it, and than create a second and validate, a third ...
## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)

[_Files_]
# Feature Request

[_Short description_]
## Use case

[_Verbose description_]
## Suggested implementation

[_Verbose description_]
## Suggested steps

[_List of tasks to achieve goal_]

**Comment by atm-gauthier** [comment] 2016-06-30 12:43
Hi,
I just made a test about what you said.
If you create a new bill from an order which already has at least one bill, you will see message "Warning, one or more invoice already exist".
Gauthier.

**Comment by atm-gauthier** [comment] 2016-06-30 12:44
![image](https://cloud.githubusercontent.com/assets/5585819/16488497/1a3d914c-3ed1-11e6-95d0-92ae4c037a3f.png)

**Comment by simnandez** [comment] 2017-09-28 08:12
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:12 UTC
Labels: Works for me / Can't reproduce
