### ISSUE TITLE
Product images management

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#4080] opened 2015-11-23 15:34 UTC
Can somebody explain what it tthe goal and idea in the new product pictures management ?

in 3.8 : to get images on products (from a 3.6 install) I put the constant PRODUCT_USE_OLD_PATH_FOR_PHOTO. ) No image is shown on product card
I add a photo on a product : picture is store in the new path system even if I use PRODUCT_USE_OLD_PATH_FOR_PHOTO. : nothing shown.

Before we had photos and documents separated, since 3.8 we only have attached files and no way to distinguish.

A common case is : 
A product has serveal images, and some pdf docs (product specifications, installation directives....), How do youplan managing this ?
Was correctly managed until 3.6, problems in 3.7 (solved by PRODUCT_USE_OLD_PATH_FOR_PHOTO constant), does no more work ?

Please Developper explain the way this system is intended to work on a wiki page. So people can correctly test this function instead of changing plans with each release. 

How can a user of dolibarr with old filesystem for pîctures migrate to 3.8 without loosing his products pictures ?

**Comment by tiaris** [comment] 2015-11-23 21:09
correcting get_exdir : adding 'product' foir working with PRODUCT_USE_OLD_PATH_FOR_PHOTO constant
pull request #4086

**Comment by vegorevegore** [comment] 2015-12-17 09:33
Hello @tiaris 

we are facing the same problem here, did you solve this issue?

**Comment by eldy** [comment] 2015-12-19 18:54
Still can't reproduce the problem. Can someone provide a complete use case to reproduce the bug. What i need is:
The full path into "documents" diretory where pictures of a product are stored, name of picture file and url of page where image is not visible when it should.

**Comment by tiaris** [comment] 2015-12-22 08:44
i did not find any problem when applying the proposed patch ( get_exdir : adding 'product' ) in 3.8 in production with PRODUCT_USE_OLD_PATH_FOR_PHOTO.
You reject the PR because it creates problems in other places, but where ? 
cf https://github.com/Dolibarr/dolibarr/pull/4086

**Comment by eldy** [comment] 2015-12-27 17:13
The images of products are just not more visible when patch is applied.
On the opposite, i can't reproduce any bug currently. Can you provide a use case to reproduce the bug when patch is not merged. What I need is :
The full path into "documents" diretory where pictures of a product are stored, name of picture file and url of page where image is not visible when it should.

**Comment by eldy** [comment] 2016-02-03 01:44
Commit fedf1f3288addbc32ad6b0de1492058ceaea9ee5 into 3.8 branch should fix this

**Closed as completed** 2016-02-03 01:45 UTC
Labels: Discussion, Priority 1 - High / Blocking
