### ISSUE TITLE
Bug: buttons to create the categories are not there

### ISSUE THREAD

**Issue by shokkky8808** [Dolibarr/dolibarr#8014] opened 2018-01-02 21:07 UTC
# Bug

## Environment
- **Version**: 7.0.0-beta
- **OS**: Linux
- **Web server**: Apache/2
- **PHP**: fpm-fcgi 7.1.9
- **Database**: MySQL or MariaDB 5.6.36
- **URL**: /ERP/categories/card.php?action=create&type=6&leftmenu=

## Report
buttons to create the etiquette are not there,  let me know if i bother you, i just like to help constructing Dolibarr

![image](https://user-images.githubusercontent.com/35044384/34500052-55bc63c0-f009-11e7-8659-021005c1fca8.png)

**Comment by atm-maxime** [comment] 2018-01-16 12:12
Hello !
You don't bother at all, we like to have feedbacks !
Can you update your beta and check again please. I can't reproduce this in mine.

**Comment by shokkky8808** [comment] 2018-01-16 12:19
Is there a new release. I have the last update is on the web to download 7.0.0.2 from 9/12.
I will be glad to contribute as much as I can with your proyect what is certainly great for us. 
If any time you line to have access to our enviroment I wouldnt mind to provide a user with full privileges to try it out. 
Kind regards and many thanks again in advance. 


Javier Fernández M.+34 607 785 485
-------- Mensaje original --------De: Maxime Kohlhaas <notifications@github.com> Fecha: 16/1/18  13:12  (GMT+01:00) Para: Dolibarr/dolibarr <dolibarr@noreply.github.com> Cc: shokkky8808 <javiercfm@gmail.com>, Author <author@noreply.github.com> Asunto: Re: [Dolibarr/dolibarr] Bug: buttons to create the categories are not there (#8014) 
Hello !

You don't bother at all, we like to have feedbacks !

Can you update your beta and check again please. I can't reproduce this in mine.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Dolibarr/dolibarr","title":"Dolibarr/dolibarr","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Dolibarr/dolibarr"}},"updates":{"snippets":[{"icon":"PERSON","message":"@atm-maxime in #8014: Hello !\r\nYou don't bother at all, we like to have feedbacks !\r\nCan you update your beta and check again please. I can't reproduce this in mine."}],"action":{"name":"View Issue","url":"https://github.com/Dolibarr/dolibarr/issues/8014#issuecomment-357941816"}}}

**Comment by atm-gauthier** [comment] 2018-04-10 15:05
Hi @shokkky8808 now we are in 7.0.2, is your dolibarr up to date ?
Can't reproduce too.

**Comment by shokkky8808** [comment] 2018-04-10 15:48
I will update later on. Thx

**Comment by hregis** [comment] 2018-04-11 07:01
@shokkky8808 
disable/enable category module

**Comment by atm-gauthier** [comment] 2018-04-11 07:13
Please don't forget to close this issue if everything's ok for you ;)

**Comment by shokkky8808** [comment] 2018-04-11 08:47
Cpunt on it :-) 


Javier Fernández M.+34 607 785 485
-------- Mensaje original --------De: atm-gauthier <notifications@github.com> Fecha: 11/4/18  9:13  (GMT+01:00) Para: Dolibarr/dolibarr <dolibarr@noreply.github.com> Cc: shokkky8808 <javiercfm@gmail.com>, Mention <mention@noreply.github.com> Asunto: Re: [Dolibarr/dolibarr] Bug: buttons to create the categories are not there (#8014) 
Please don't forget to close this issue if everything's ok for you ;)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Dolibarr/dolibarr","title":"Dolibarr/dolibarr","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Dolibarr/dolibarr"}},"updates":{"snippets":[{"icon":"PERSON","message":"@atm-gauthier in #8014: Please don't forget to close this issue if everything's ok for you ;)"}],"action":{"name":"View Issue","url":"https://github.com/Dolibarr/dolibarr/issues/8014#issuecomment-380351355"}}}

**Comment by shokkky8808** [comment] 2018-04-11 09:53
I only see  verssion 701 to download as stable, can you send me the link to
702?

let me know if you like my contribution to trasnlate to spanish, it will be
a pleasure to contribute.

regards,

2018-04-11 9:13 GMT+02:00 atm-gauthier <notifications@github.com>:

**Comment by atm-maxime** [comment] 2019-06-01 15:10
Sorry we didn't catch up. I close this one now, the issue has been long fixed :)

**Closed as completed by atm-maxime** 2019-06-01 15:10 UTC
Labels: Works for me / Can't reproduce
