### ISSUE TITLE
Problem in societe/project.php. Blank page from thirparty to projects or projects to thirdparty

### ISSUE THREAD

**Issue by xbloq** [Dolibarr/dolibarr#28505] opened 2024-02-28 17:07 UTC
### Bug

Users, not administrators, have a blank page to open project from third

### Environment Version

19.0

### Environment PHP

8.2

### Expected and actual behavior

PHP Warning:  Undefined variable $arrayofmassactions in /dolibarr/htdocs/societe/project.php on line 105
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /dolibarr/htdocs/core/class/html.form.class.php:833
Stack trace:
#0 /dolibarr/htdocs/societe/project.php(105): Form->selectMassAction()
#1 {main}
  thrown in /dolibarr/htdocs/core/class/html.form.class.php on line 833

I can work if I put $arrayofmassactions = array(); in line 105 before $massactionbutton = $form->selectMassAction('', $arrayofmassactions); of /htdocs/societe/project.php

**Comment by mathieu-rossignol** [comment] 2024-04-03 09:36
Hi guys, got exactly the same problem with 19.0.0, is it fixed in 19.0.1 ?

**Comment by leonbrehme** [comment] 2024-04-12 15:00
Nope. The problem is also present in 19.0.1

**Comment by nicolasponthus** [comment] 2024-04-17 13:28
The issue seems to be linked to user permission: adding thirdparty suppression to user permission seems to solve it. Not ideal though...

**Closed as completed** 2024-11-06 12:26 UTC
Labels: Bug
