### ISSUE TITLE
Bug: Impossible to delete import files

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#5339] opened 2016-06-11 06:42 UTC
Version: 3.9.2
Browser: Firefox 43.0.1

=> New ticket because I can't reopen ticket #5213 which has been wrongly closed,  the problem is not solved

Hello,
I can upload import files (Tools) but when I click on the trashbin in order to delete the file it doesn't work.
To reproduce the problem upload an import file and try to delete it using the trashbin
It doesn't work for any import file, at least Tiers and Coordonnees bancaires.

Please don't close tickets without asking if the problem is not really solved, it's not the good way to solve problems...I have 2 tickets to reopen like that...

**Comment by mikygee** [comment] 2016-06-11 07:05
I tried with another browser IE. It works.
But I noticed there a popup asking me if I want to delete RIB, which I don't see when I use Firefox.
I've disabled all Firefox modules, the popup doesn't appear, the page reloads and that's all.
There is this same problem with all the trashbins and Firefox 43.0.1

**Comment by atm-maxime** [comment] 2016-06-11 07:06
Hello @mikygee,

The issue system on github is not where people do technical support for a specific installation. It's where issues are declared for the global project in order to have it fixed in the master branch of the project.

We are 2 to tell you that we can't reproduce your issue, so it's more likely that your issue is not coming from the project code, but from your installation environnement.

**Comment by atm-maxime** [comment] 2016-06-11 07:10
I tried again, Dolibarr 3.9.2, Firefox 46.0.1, and all trashbins are working.
My firefox has no extension installed.
The only difference I see is that you have 43.0.1 version of firefox.

**Comment by mikygee** [comment] 2016-06-11 07:10
Hello @atm-maxime,
I'm not talking about technical support for a specific installation.
As you can notice, I've made many tests in order to qualify the problem.
So if you consider Firefox is not a supported browser (I don't know what market share it has, but quite relevant) you can consider it's technical support.
But if you consider Firefox is a supported browser then there's a problem in the code.
When you replied, I'm not even sure you used firefox to reproduce the problem...

**Comment by mikygee** [comment] 2016-06-11 07:13
So if your recommandation is to test with the latest Firefox version I can do it. But I can't guess what were the conditions that you used to successfully do the tests. You didn't mention before.

**Comment by atm-maxime** [comment] 2016-06-11 07:16
Yes sorry I didn't told how I did the tests. But by convention, if you declare an issue for Dolibarr 3.9.2 and using Firefox, my tests will be with these configurations. Only not exactly the same firefox version for this example. It would make no sense if I say "works for me" on a 4.0 version of Dolibarr and using Chrome...

**Comment by mikygee** [comment] 2016-06-30 05:37
Hello,

I did the test with Firefox 47.0.1 which is the last version and get the same issue.

When I look at the source code "Modifier" is between <a> tags
`<div class="inline-block divButAction"><a class="butAction" href="/societe/soc.php?socid=291&amp;action=edit">Modifier</a></div>`

But supprimer is not between <a> tags
`<div class="inline-block divButAction"><span id="action-delete" class="butActionDelete">Supprimer</span></div>`

So I feel like my browser is not asked to open a new link

And if I look the id="action-delete" in
`_<span id="action-delete" class="butActionDelete">Supprimer</span>_`
Something in the code looks like it but the id is different

```
<div id="dialog-confirm-action-delete" title="Supprimer une soci&eacute;t&eacute;" style="display: none;"><div class="confirmmessage"><img src="/theme/eldy/img/info.png" border="0" alt="" title="" style="vertical-align: middle;"> &Ecirc;tes-vous s&ucirc;r de vouloir supprimer cette soci&eacute;t&eacute; et toutes les informations qui en d&eacute;pendent ?</div></div>
<!-- begin ajax form_confirm page=/societe/soc.php?socid=291 -->
```

**Comment by atm-maxime** [comment] 2016-06-30 12:46
Thanks for these informations. It seems like javascript is disabled in your browser. The "Modifier" link works because this is a direct link, the "Supprimer" is not a direct link but uses javascript to be launched.

**Comment by mikygee** [comment] 2016-06-30 23:14
Hello,
I think javascript is enabled on my browser
I went to this page
`http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onmouseover`
When I rollover the smiley it becomes bigger
I also checked in about:config the value is true

**Comment by marcosgdf** [comment] 2017-04-13 14:10
Any update on this issue?

**Comment by atm-maxime** [comment] 2018-12-01 00:13
This issue is old and has probably been fixed since then. Please reopen if needed and give us more details.

**Closed as completed by atm-maxime** 2018-12-01 00:13 UTC
