### ISSUE TITLE
Bug: /htdocs/fourn/card.php?socid=xxx   not showing boxes 

### ISSUE THREAD

**Issue by lucanot** [Dolibarr/dolibarr#3531] opened 2015-09-16 08:22 UTC
# Environment
- **Version**: 3.8.0
- **OS**: Linux
- **Web server**: Apache/2.2.15
- **PHP**: apache2handler 5.5.29
- **Database**: MySQL or MariaDB 5.5.45
- **URL**: /dolibarr/htdocs/fourn/card.php?socid=323
# Report

I upgrade to version 3.8.0 from 3.7.1,  but unfortuntely when opening the mask of a supplier, /htdocs/fourn/card.php?socid=xxx  ,  the boxes about last proposals, orders, invoices  are not showing any more...  it's strange because when the third party is a customer, it works /htdocs/comm/card.php?socid=xxx
![image](https://cloud.githubusercontent.com/assets/7040465/9899832/be32263a-5c5c-11e5-8d18-f55edbe04494.png)

**Comment by rdoursenaud** [comment] 2015-09-16 19:21
Can't reproduce. Looks like you have a fatal error somewhere. Can you take a peek at the logs?

**Comment by rdoursenaud** [comment] 2015-09-16 19:22
Mmm looking a bit better into it, it looks very similar to #3529

**Comment by eldy** [comment] 2015-09-16 19:26
Fixed with e36928f

**Closed as completed** 2015-09-16 19:26 UTC
Labels: Works for me / Can't reproduce, Bug
