### ISSUE TITLE
Existing ticket file attachment issue while replying

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#22941] opened 2022-11-23 14:02 UTC
### Bug

While trying to reply to an existing message on ticket reply page at the URL[https://HOST/ticket/card.php?track_id=qk2tkpvgv5s5bxld&action=presend_addmessage&mode=init&backtopage=%2Fticket%2Fmessaging.php%3Ftrack_id%3Dqk2tkpvgv5s5bxld](url), we are getting issue at the time of file attachment. After selecting a file uploading it successfully, **the file is not shown in the uploaded file list beside the browse button**.

### Environment Version

16.0.2

### Environment OS

AlmaLinux 8.6

### Environment Web server

Apache 2.4.37

### Environment PHP

8.1.12

### Environment Database

MySQL 8.0.30

### Environment URL(s)

https://HOST/ticket/card.php?track_id=qk2tkpvgv5s5bxld&action=presend_addmessage&mode=init&backtopage=%2Fticket%2Fmessaging.php%3Ftrack_id%3Dqk2tkpvgv5s5bxld

### Steps to reproduce the behavior

Just try to reply to an existing ticket with attachment.

### Attached files

![File-upload-error](https://user-images.githubusercontent.com/1249577/203565965-21c33da8-0e08-492a-b59f-65a25398b0bc.png)

**Comment by eldy** [comment] 2022-11-24 14:35
There is 2 var trackid:  "trackid" and "track_id"
trackid is used to store an id for email tracking (this is used everywhere in app) and what we must have in action_sendmail.inc.php
track_id is a ref for a ticket. So i don't think your fix is good. Did you experience the trouble on develop ? It seems it is ok already on current (develop). Do you reproduce the bug on develop or only v16 ?

**Comment by alsoft10** [comment] 2022-11-25 11:10
@eldy  you were correct. I updated pull request. The problem is fixed now in 16.0 branch as per the Dolibarr ticket coding structure. Yeah this problem also persist in develop branch as well. In the develop branch attachment are uploaded successful but it is not submitted upon form submit. I solved that problem as well. Will send another pull request regarding that after merging this one.

**Comment by Hystepik** [comment] 2022-11-25 21:23
It seems to be fixed so I close the issue.
Feel free to reopen if not.

**Comment by alsoft10** [comment] 2022-11-26 06:19
I have checked and it not fixed. I have doubt, when will you fix this? Why not your merging my fix?

**Comment by Hystepik** [comment] 2022-11-26 09:17
Sorry, I reopen the issue

**Comment by alsoft10** [comment] 2022-11-26 11:42
@Hystepik check my pull request #22947 regarding this fix

**Comment by ksar-ksar** [comment] 2023-10-18 20:47
Hello,

It is still the case with V18 ?

**Closed as completed** 2023-12-19 06:19 UTC
Labels: Bug or PR need more information
