### ISSUE TITLE
impossible to input quantity lesser than 1 when adding free service line in supplier order

### ISSUE THREAD

**Issue by altairis-tof** [Dolibarr/dolibarr#4504] opened 2016-01-27 10:44 UTC

**Comment by altairis-tof** [comment] 2016-01-27 10:45
version 3.8.3

**Comment by eldy** [comment] 2016-02-03 00:12
I tested with 3.9 and it works. Is it ko for you on 3.9 ?

**Comment by altairis-tof** [comment] 2016-02-03 08:15
i will test asap; none of my customer neither us work with this release, but i will try. thanks

**Comment by simnandez** [comment] 2017-09-28 08:50
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:50 UTC
