### ISSUE TITLE
Bug when generating PDF from ODT template in Propals still in 5.0

### ISSUE THREAD

**Issue by Skitprat** [Dolibarr/dolibarr#6524] opened 2017-03-14 12:36 UTC
Hello,
I'm coming back on this bug that I get since 4.0 version. I already opened an issue on the old version but it got marked as unsupported as dolibarr got new versions since then. But the issue is still there !

When I try to generate a PDF from an ODT file of a proposal in Dolibarr 5.0 , I get an error message.
My templates work fine (they do everywhere else and I use almost the same), as I have no issue in orders / shipment / invoces with the same file.

In the proposal section, it generates the ODT file, it's perfectly fine, but it fails when converting it to PDF

I've tried this on a completely fresh install too, same stuff.

Here is the error log : 

Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic:
Date: 20170314132646
Dolibarr: 5.0.0
Niveau de fonctionnalités: 0
PHP: 5.4.45-0+deb7u4
Server: Apache
OS: Linux vds2732.sivit.org 2.6.38.4 #1 SMP PREEMPT Thu Apr 28 11:05:01 CEST 2011 i686
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

Url sollicitée: /htdocs/comm/propal/card.php?id=1
Referer: http://***/htdocs/comm/propal/card.php?id=1
Gestionnaire de menu: eldy_menu.php

Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: Aucune requête en erreur
Code retour dernier accès en base en erreur: Aucune requête en erreur
Information sur le dernier accès en base en erreur: Aucune requête en erreur

Message: Error generating document for CommonObject. Error: ODT to PDF convert fail :

**Comment by nicolas-it** [comment] 2017-03-18 18:26
Hi @Skitprat,
had the same error today. 
I used "[!-- IF ... --]" conditions in the .odt
When I removed the conditions (copy/paste to some notepad or anything without format) and pasted it back in worked fine for me.
Seemed to be formatting issue with odt-templates.

https://wiki.dolibarr.org/index.php/Create_an_ODT_document_template#Conditional_substitution
The second warning gave me the essential hint.

Maybe it helps...

**Comment by Skitprat** [comment] 2017-03-20 08:49
Hi Nicos,
Thanks for answering on this issue !
I have checked on my ODT Template, I'm not using any condition and I get this error.
I tried and removed every tags from my document and I get the error....
Maybe the issue is linked to the [!-- BEGIN xxx --] and [!-- END xxx --] tags, I really don't know... It's only on this section so that's gotta be a bug anyway...

If you find more, please feel free to post it here :)

Thank you Nicos !

Skitprat

**Comment by marcosgdf** [comment] 2017-04-13 14:19
Duplicate of #5930.

Please do not open new bugs that talk about the same thing. The bug is reported for the lowest version where the error happens, so your previous bug report was correct and this one is not

**Comment by atm-maxime** [comment] 2018-12-01 14:58
Duplicate of #5930

**Closed as completed by atm-maxime** 2018-12-01 14:58 UTC
