### ISSUE TITLE
Bug: Module Ticket. Initial message and subject are replaced when adding message

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#22439] opened 2022-09-27 19:39 UTC
# Bug
initial message and subject are replaced by the message when adding message with check send message by email

## Environment
- **Version**: 16.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.1.33
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /ticket/card.php?action=view&track_id=fuzzidzdwsbf4h6n

**Comment by hregis** [comment] 2022-09-28 07:59
@leninrivas i can't reproduce your problem, can you describe your procedure ?

**Comment by leninrivas** [comment] 2022-09-28 16:09
Hi @hregis.
When active checkbox email and send to the message then the fields subject and initial messaje of the ticket are replaced by email information.

![Screenshot_1](https://user-images.githubusercontent.com/53640168/192830609-1530c660-b10d-4a86-80a5-fc126817c78a.png)
![Screenshot_2](https://user-images.githubusercontent.com/53640168/192830634-361e1d66-3931-4cba-b7d4-4a4ce880eeb5.png)

**Comment by hregis** [comment] 2022-09-29 06:58
@leninrivas it's fixed with this PR https://github.com/Dolibarr/dolibarr/pull/22454

**Closed as completed** 2022-10-10 20:54 UTC
Labels: Bug
