### ISSUE TITLE
Bug regression in V14.0.0: Impossible to export and import data 

### ISSUE THREAD

**Issue by blftpe** [Dolibarr/dolibarr#18189] opened 2021-07-21 04:06 UTC
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*When doing a data Export from the tools tab -for any type of export- , after completing the parameters *]

## Environment
- **Version**: [*14.0.0*]
- **OS**: [*Linux DS218play 4.4.180+ #41890 SMP Fri Jun 25 02:40:26 CST 2021 aarch64*]
- **Web server**: [*nginx/1.17.10*]
- **PHP**: [*PHP 7.3.2.4*]
- **Database**: [*MariaDB 10*]
- **URL(s)**: [*XXX/dolibarr/htdocs/exports/export.php?step=5&datatoexport=facture_1*]

## Expected and actual behavior
[*There should be a download button, next step or something, but instead I only see a summary fo the parameters, without the possibility to really export the data. This is a quite severe problem because it makes it impossible to work on the product. Besides, it is also impossible to import data, as it's not possible to choose a file format*]

## Steps to reproduce the behavior
[*Go to tools, choose any data export, and follow steps until it's impossible to download
<img width="1435" alt="Screen Shot 2021-07-20 at 6 01 51 PM" src="https://user-images.githubusercontent.com/4622001/126429294-c63d30c4-2f28-41cd-bbe9-a0fffec4d322.png">
<img width="1435" alt="Screen Shot 2021-07-20 at 6 01 51 PM" src="https://user-images.githubusercontent.com/4622001/126429316-e79e38f8-c980-4e2f-9a90-0a5d90d1762f.png">
*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by daraelmin** [comment] 2021-07-21 06:58
Duplicate of #16091 ans #16148

**Comment by blftpe** [comment] 2021-07-21 07:24
Hi Daraelmin, I understand it's a duplicate, but the issue is mentioned as closed on V13.X.X (and things were fine on my 13.X.X), and now it appeared on 14.0.0 again, so for me it's a new bug - please correct me if I'm wrong : should I rather answer in the closed bug? (on peut parler en Francais aussi si tu préfères).

**Comment by daraelmin** [comment] 2021-07-21 07:37
@blftpe 
Please edit title and to "bug regression".

**Comment by blftpe** [comment] 2021-07-21 07:53
@daraelmin added "Bug Regression" in the title, but couldn't find how to update the "bug" tag.
Thanks for your explanation!

**Comment by daraelmin** [comment] 2021-07-21 13:18
> @daraelmin added "Bug Regression" in the title, but couldn't find how to update the "bug" tag.
> Thanks for your explanation!
 The tag doesn't need to be changed.

**Comment by ksar-ksar** [comment] 2021-07-27 13:44
Hello,

Most probably an error 500 => Could you check the nginx logs ?

**Comment by blftpe** [comment] 2021-07-27 13:59
@ksar-ksar Sure, where can I find them?

**Comment by ksar-ksar** [comment] 2021-07-27 14:04
> 
> 
> @ksar-ksar Sure, where can I find them?

On your Synology go to : /var/log/nginx/error.log

**Comment by blftpe** [comment] 2021-07-27 14:14
@ksar-ksar Sorry, I can't find this file, I saw with a google search it should be in dolibarr/documents, but there's no thing there, and I don't have any /var file either of the NAS. I must be missing something, can you help me?

I still don't understand if this bug is just for me or a bug of Dolibarr 14.0.0. I didn't manage to regress to 13.X and really need to export my data, so would like to make progress on this!

**Comment by blftpe** [comment] 2021-08-23 06:47
Solved with v14.0.1

**Closed as completed** 2021-08-23 06:47 UTC
Labels: Bug, Bug or PR need more information
