### ISSUE TITLE
Since upgrade to v15 The Documents tab in the project tasks shows nothing, completely blank screen.

### ISSUE THREAD

**Issue by JoAnMaFe** [Dolibarr/dolibarr#20202] opened 2022-02-25 16:58 UTC
### Bug

Since upgrade to v15.
The Documents tab in the project tasks shows nothing, completely blank screen.

### Environment Version

V15

### Environment OS

Windows

### Environment Web server

Apache/2.4.48 (Win64) PHP/7.4.23

### Environment PHP

 7.4.23

### Environment Database

10.6.4-MariaDB

### Environment URL(s)

Localhost

### Expected and actual behavior

The Documents tab in the project tasks must allow the attachment of documents.

**Comment by atm-maxime** [comment] 2022-02-25 20:40
I think it has been fixed by #20172

**Comment by edupulpillo** [comment] 2022-03-12 07:31
The problem is already fixed  
You need to wait to version 15.0.1 or fix manually the file 77 of the file /projet/tasks/document.php
This bug need to be closed as it has been fixed already by [atm-maxime](https://github.com/atm-maxime) with the commit https://github.com/Dolibarr/dolibarr/pull/20172

**Comment by lmag** [comment] 2022-11-25 21:05
I just test on 16.0.2 it is ok for me to (thank to @atm-maxime and @rycks )

**Closed as completed by lmag** 2022-11-25 21:05 UTC
Labels: Bug
