### ISSUE TITLE
But: Fatal error - class CategoryApi in api_deprecated_category.class.php

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#7004] opened 2017-06-13 19:50 UTC
# Bug
I'am using Dolibarr 5.0.3. Today I tried to activate and use the API (REST Server) Module. After activating it, I am introduced within the settings to get a token to use the API with an link like:
`https://[…]/api/index.php/login?login=username&password=yourpassword[&reset=1]`

I tried to open this link, without "rest=1" and with it. But the only message I got is an PHP Error
> Fatal error: Cannot redeclare class CategoryApi in /[…]/categories/class/api_deprecated_category.class.php on line 490

Maybe I tried to activate it some time ago within an older version of Dolibarr. Maybe this could be the reason?

## Environment
- **Version**: 5.0.3
- **OS**: Linux
- **Web server**: Apache
- **Database**: MySQL

## Steps to reproduce the behavior
see above

**Comment by eldy** [comment] 2017-06-20 08:39
Take a look into categories/class
directory may contains files from previous version. Be sure to have ONLY file of 5.0.3

**Comment by simnandez** [comment] 2017-09-28 08:52
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:52 UTC
