### ISSUE TITLE
Export Final Step Unavailable

### ISSUE THREAD

**Issue by jonamsler** [Dolibarr/dolibarr#16148] opened 2021-02-02 16:31 UTC
# Instructions
Reference URL: https://www.mydomain.com/glgerp/exports/export.php?step=5&datatoexport=facture_1

# Bug
Using Tools>New Export, when finishing process, Step 5 has no way to export result.

## Environment
- **Version**: 13.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: [*PHP version*]
- **Database**: MySQL
- **URL(s)**: https://www.mydomain.com/glgerp/exports/export.php?step=5&datatoexport=facture_1

## Expected and actual behavior
Expect a selection of file formats and 'save' button.

## Steps to reproduce the behavior
Tools>New Export>Invoices>

## Screenshot
<img width="1070" alt="screenshot" src="https://user-images.githubusercontent.com/2604123/106630796-25bc1300-654a-11eb-8541-7c51a33e6746.png">

**Comment by daraelmin** [comment] 2021-02-02 21:24
Same as  #16091

**Comment by eldy** [comment] 2021-02-03 18:39
Duplicate of #16091

**Closed as completed by eldy** 2021-02-03 18:39 UTC
Labels: Bug
