### ISSUE TITLE
Impossible to enable invoices (field llx_cronjob.params not nullable)

### ISSUE THREAD

**Issue by tomours** [Dolibarr/dolibarr#5952] opened 2016-11-03 19:13 UTC
# Bug
Impossible to enable invoices (field llx_cronjob.params not nullable)

## Environment
- **Version**: 4.0.2
- **OS**: Ubuntu 14.04 LTS
- **Web server**: Apache 2.4.7
- **PHP**: 5.X
- **Database**: Postgres 9.3.14
- **URL(s)**: modules.php

## Expected and actual behavior
When trying to enable the invoices module, I have the following error : 
ERROR: 23502: **null value in column 'params' violates not-null constraint** DETAIL: Failing row contains (8, 2016-11-03 20:08:24.946397, 2016-11-03 20:08:24, method, RecurringInvoices, null, compta/facture/class/facture-rec.class.php, FactureRec, createRecurringInvoices, null, null, facture, 0, null, null, 2016-11-03 20:08:24, null, null, null, null, 86400, 1, null, 1, null, null, Generate recurring invoices, null, 1, 0, 0, null, ). SCHEMA NAME: public **TABLE NAME: llx_cronjob COLUMN NAME: params** LOCATION: ExecConstraints, execMain.c:1634

In fact, the column llx_cronjob.params has the NOT NULL parameter.
When unsetting NOT NULL, I can enable the module, but I have no idea if this field should be nullable or not and what could be the consequences of setting in nullable.

## Steps to reproduce the behavior
Enable invoices module

**Comment by eldy** [comment] 2016-11-11 14:42
Removing the NOT NULL seems to hav no side effect.

**Comment by eldy** [comment] 2016-11-11 14:44
What is strange is that the creation of table llx_cronjob does not contains the not null.

CREATE TABLE llx_cronjob 
(
    rowid           integer AUTO_INCREMENT PRIMARY KEY,
    tms             timestamp,
    datec           datetime,
    jobtype         varchar(10) NOT NULL,
    label           text NOT NULL,
    command         varchar(255),
    classesname     varchar(255),
    objectname      varchar(255),
    methodename     varchar(255),
    params          text,
    md5params       varchar(32),
    module_name     varchar(255),
    priority        integer DEFAULT 0,
    datelastrun     datetime,                   -- date last run start (see datelastresult for end with a result)
    datenextrun     datetime,                   -- job will be run if current date higher that this date
    datestart       datetime,                       -- before this date no jobs will be run
    dateend         datetime,                       -- after this date, no more jobs will be run
    datelastresult  datetime,                       -- date last run end
    lastresult      text,
    lastoutput      text,
    unitfrequency   varchar(255) NOT NULL DEFAULT '3600',
    frequency       integer NOT NULL DEFAULT 0,
    maxrun          integer NOT NULL DEFAULT 0,     -- set this to 1 for a job queued for on run only
    nbrun           integer,                        -- nb of run complete (failed or not)
    autodelete      integer DEFAULT 0,              -- 0=Job is kept unchanged once nbrun > maxrun or date > dateend, 2=Job must be archived (archive = status 2) once nbrun > maxrun or date > dateend 
    status          integer NOT NULL DEFAULT 1,     -- 0=disabled, 1=enabled, 2=archived
    test            varchar(255) DEFAULT '1',
    fk_user_author  integer DEFAULT NULL,
    fk_user_mod     integer DEFAULT NULL,
    fk_mailing      integer DEFAULT NULL,       -- id of emailing if job was queued to send mass emailing
    note            text,
    libname         varchar(255),
    entity          integer DEFAULT 0
)ENGINE=innodb;

**Comment by tomours** [comment] 2016-11-14 12:45
Maybe it was in an old installation package : my initial version was 3.7.1. I performed some updates to get to 4.0.2 (but didn't ever make any manual change in the database).

**Comment by simnandez** [comment] 2017-09-28 08:18
I close this issue, because is not reproducible

**Closed as completed by simnandez** 2017-09-28 08:18 UTC
Labels: Works for me / Can't reproduce
