### ISSUE TITLE
Import Module does not display option to proceed to Step-3

### ISSUE THREAD

**Issue by NHC390** [Dolibarr/dolibarr#16295] opened 2021-02-15 08:46 UTC
![import](https://user-images.githubusercontent.com/79080211/107922944-2ca34680-6f8a-11eb-9539-adf277638529.JPG)
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[Import Module does not display the any option for proceeding to next step after Step-2]

## Environment
- **Version**: [13.0.0]
- **OS**: [Windows 10 64bit]
- **Web server**: [Apache2.4.46]
- **PHP**: [7.4.15-Win32-vc15-x64]
- **Database**: [*mariadb-10.4.17-winx64*]
- **URL(s)**: [http://192.20.20.6/dolibarr/imports/import.php?step=2&datatoimport=produit_1&excludefirstline=1&separator=%2C&enclosure=%22]

## Expected and actual behavior
['File to import must have one of following formats' is displayed but there is no option to select any format, there is no links available to select. The steps outlined in the online procedure shows many options but in actual nothing is visible in my page.]

## Steps to reproduce the behavior
[Please guide where I might have made any mistakes during the setup and what is the procedure to rectify this problem.]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by daraelmin** [comment] 2021-02-16 14:15
Duplicate of #16091 ?

**Comment by ksar-ksar** [comment] 2021-02-16 17:53
Yes duplicated of #16235, #16091, #16187, #16148 and fixed

**Closed as completed by ksar-ksar** 2021-02-16 17:53 UTC
Labels: Bug

**Comment by NHC390** [comment] 2021-02-18 16:54
I have tried to install 13.0.1 and even 14.0 alpha still the same issue. Tried in 12.0.5 version and tat is displaying this options.
