### ISSUE TITLE
v11.x Vendor invoice not linked to Purchase order automatically

### ISSUE THREAD

**Issue by jrgonzalezrios** [Dolibarr/dolibarr#13147] opened 2020-02-19 20:31 UTC
## Bug
Creating a invoice to a validated Purchase Order, from the Commerce module, does not automatically links to the origin Purchase Order. This was made automatically before version 11.0.0

## Environment
- **Version**: 11.0.0 and 11.0.1
- **OS**: Linux
- **Web server**: Nginx/1.15.8
- **PHP**:  7.3.9
- **Database**: MySql 7.7.27

## Expected and actual behavior
New Purchase's order Invoce automatically links to it. Currently it does not link and needs a manual select of Purchase Order 

## Steps to reproduce the behavior
Create a Vendor's purchase order.
Validate order
Create invoice to order
Validate invoce: invoice will not be linked to Purchase Order

**Comment by ndaccesswebservice** [comment] 2020-02-22 03:39
I also notice this issue as well. I hope that it will be fixed soon.

**Comment by eldy** [comment] 2020-02-24 22:47
Do you succeed in making the link after the creation ?

**Comment by WebAuxilium** [comment] 2020-02-25 10:04
Eldy
Yes we could link manually from invoice to order and order from invoice.
The problem is only when you create invoice from order. Before V11, the link between order and invoice was done automatically.

**Comment by eldy** [comment] 2020-02-25 14:14
Fixed by bb64d2d3530bbb0aa0fa86a3896bb423d70b8451

**Closed as completed by eldy** 2020-02-25 14:14 UTC
Labels: Bug
