### ISSUE TITLE
Line attributes whose type is "date" for an invoice return 1/01/1970

### ISSUE THREAD

**Issue by verbatime** [Dolibarr/dolibarr#9474] opened 2018-09-11 19:40 UTC
# Bug
Line attributes whose type is "date" for an invoice do not work. The date returned after saving the line is 1/01/1970.
## Environment
- **Version**: 8.0.1
- **OS**: CentOS 6.9
- **Web server**: APACHE
- **PHP**: 5
- **Database**: Mysqli

## Steps to reproduce the behavior
- Add a line attribute whose type is "date"
- Create an invoice
- Set a date for a line and save the line
-> Date is 1/01/1970

## [Attached files]
https://ibb.co/nMvnfU

**Comment by verbatime** [comment] 2018-10-08 11:41
If you encode it in "Timestamp UNIX" it works.

**Comment by nlc-bb** [comment] 2018-10-18 11:00
Same issue in 8.0.2 and possible duplicate of #9641 

Found that problem is coming from function `getOptionalsFromPost` in `/htdocs/core/class/extrafields.class.php`, where $object is not available.

Maybe solved in 8.0.3 but cannot test as it's not available now.

**Comment by verbatime** [comment] 2018-11-07 12:28
Not solved in 8.0.3. Did you find a manual patch @nlc-bb ?

**Comment by nlc-bb** [comment] 2018-11-07 19:45
Yes, I made some change to make it work.
Changed function getOptionalsFromPost in /core/class/extrafields.class.php (line 1915 in 8.0.2 version)
and the call in /compta/facture/card.php (line 1657)

[1970.zip](https://github.com/Dolibarr/dolibarr/files/2558926/1970.zip)

**Comment by atm-maxime** [comment] 2019-03-11 20:32
Fixed in #10803 but not in 8.0 branch yet

**Comment by atm-maxime** [comment] 2019-03-16 08:05
Coud you confirm it's fixed please ?

**Closed as completed** 2019-03-26 14:33 UTC
