### ISSUE TITLE
New module Expense Report - Email is not translated

### ISSUE THREAD

**Issue by aspangaro** [Dolibarr/dolibarr#2741] opened 2015-05-01 05:28 UTC
In the new module Expense Report (Dolibarr Develop), email is not translated. Still in French language.

It is hard-coded here : /expensereport/card.php

Example :

// SUBJECT
$subject = "' ERP - Note de frais validée";

// CONTENT
$message = "Bonjour {$destinataire->firstname},\n\n";
$message.= "Votre note de frais \"{$object->ref}\" vient d'être approuvé!\n";
$message.= "- Approbateur : {$expediteur->firstname} {$expediteur->lastname}\n";
$message.= "- Lien : {$dolibarr_main_url_root}/expensereport/card.php?id={$object->id}\n\n";
$message.= "Bien cordialement,\n' SI";

**Comment by rdoursenaud** [comment] 2015-05-05 14:44
Fixing this bug might be a good time to leverage the new email templating system IMHO.

**Comment by eldy** [comment] 2015-07-16 08:44
This is not a bug but a feature that does not exist yet.
No email are sent for the moment. There is a constant DEPLACEMENT_TO_CLEAN that make this part of code never executed. I kept it because it is a future dev for the feature to send email after validation of an expense report, but this dev is not finished yet.

**Comment by rdoursenaud** [comment] 2015-07-16 22:05
@eldy Should we remove it from the 3.8.0 milestone or do you plan finishing the feature before the release?

**Comment by rdoursenaud** [comment] 2015-08-26 17:37
I take no answer as a no. Moving to 3.9.0 milestone…

**Comment by eldy** [comment] 2017-09-26 10:43
This bug seems to be fixed into last recent stable version, so I close the bug

**Closed as completed by eldy** 2017-09-26 10:43 UTC
Labels: Feature request
