### ISSUE TITLE
Bug: Bill "fournisseur" + service: rate=20% instead of 0%

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#23371] opened 2022-12-30 03:58 UTC
### Bug

Bug

Version 15.0.3

Hello,
I created a service which has a VAT rate of 0% (that's how some banks bill their services)
![image](https://user-images.githubusercontent.com/2222550/210033022-9b2effd9-6c56-4bca-a6e0-be544f98f5e1.png)

I create it with
Tiers > Fournisseur > Créer une facture
NB: The third party is in France.
When I select « Services prédéfinis à acheter », the price that I had previously written is correct but after adding the line I can see a 20% VAT which is wrong.
![image](https://user-images.githubusercontent.com/2222550/210033028-7790bc1d-e4ea-4d69-8aba-ee1549d6bc82.png)
As a workaround I need to reedit it and type 0% but that's not how it should work.

When I change the thirdparty from France to Panama for example, the rate is now 0%

So, the problem is that the bill takes into account the location of the thirdparty and applies a default VAT rate and doesn't take into account that VAT rate I indicated in the service.

French translation here
https://www.dolibarr.fr/forum/t/facture-fournisseur-service-taux-a-20-au-lieu-de-0/41243

Regards

### Environment Version

15.0.3

**Comment by AurelienBISOTTI** [comment] 2023-06-10 15:53
Could not reproduce in v18
![Capture d’écran du 2023-06-10 17-52-40](https://github.com/Dolibarr/dolibarr/assets/12530585/b9e830d8-50fc-4c3a-a21f-5fabd31af6e1)
![Capture d’écran du 2023-06-10 17-53-04](https://github.com/Dolibarr/dolibarr/assets/12530585/ed5e7f1d-25a8-45ef-a809-f60cf027a8d1)

**Comment by mikygee** [comment] 2023-06-11 10:51
Bonjour Aurelien,
Il va falloir que j'installe la version 18 pour refaire le test.
Je n'aurai pas le temps de le faire avant début juillet.
Cdt

**Comment by mikygee** [comment] 2024-06-11 05:53
I'm going to test it again.

**Comment by eldy** [comment] 2024-07-21 11:09
This bug or the feature request seems to be fixed or included into last recent stable version, so I close the issue.

**Closed as completed by eldy** 2024-07-21 11:09 UTC
Labels: Bug, Event: DevCamp 2023 Bordeaux

**Comment by mikygee** [comment] 2024-10-06 20:26
I tested it on Dolibarr 20.0.0 and I think it works on my side.
Thank you
