### ISSUE TITLE
Clarify checkboxes from PDF merge

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2971] opened 2015-06-05 15:19 UTC
# Environment
- **Version**: 3.8.0-alpha
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.9
- **Database**: MySQL 5.5.5-10.0.18-MariaDB-log
- **URL**: /compta/facture/mergepdftool.php?sortfield=f.date_lim_reglement&sortorder=ASC
# Report

Checkboxes are missing from the PDF merge page making the feature unusable.

**Comment by marcosgdf** [comment] 2015-07-07 07:10
Can't reproduce.

![captura de pantalla 2015-07-07 a las 9 10 51](https://cloud.githubusercontent.com/assets/168744/8540661/143be03c-2488-11e5-9f42-ba113a911899.png)

**Comment by rdoursenaud** [comment] 2015-07-08 18:15
Just reproduced with fresh develop and dev/initdata

![capture d ecran de 2015-07-08 20-12-47](https://cloud.githubusercontent.com/assets/1210367/8578218/bf026c5e-25ad-11e5-837e-5a34414b2747.png)

The weird thing is that there's now one checkbox… but most are missing.
Is this expected? A condition I'm not aware of?

**Comment by rdoursenaud** [comment] 2015-07-08 18:19
Ok, I just figured it out.
It's a trap!
You can only merge PDFs that are already generated!

Let's transform this to a feature request:

Either make the user aware he can't merge that document because it's not generated (A disabled checkbox with an hover would be quite fit).

Or, allow any document to be selected and generate the missing ones.

**Comment by eldy** [comment] 2020-03-12 15:35
This bug or the feature request seems to be fixed or included into last recent stable version, so I close the issue.

**Closed as completed by eldy** 2020-03-12 15:35 UTC
Labels: Feature request, Priority 2 - Medium
