### ISSUE TITLE
Mysql error on edit time (project/task)

### ISSUE THREAD

**Issue by adiatis** [Dolibarr/dolibarr#9416] opened 2018-09-05 10:44 UTC
# Instructions
Go to the list 'List of time consumed on task'.
Go to the preferences of this list and hide the column 'By'.
Create time spent
Fill in all the fields and save. (ok)
Modify this line and save
You get a Mysql error.

# Bug
If you hide the user, the mysql query to update record is wrong. user is empty:
fk_user = ,

## Environment
- Multiple affected Dolibarr versions. 
- URL: /projet/tasks/time.php?id=9999&action=editline&lineid=...

**Comment by eldy** [comment] 2018-09-05 12:40
Which version of Dolibarr ?

**Comment by adiatis** [comment] 2018-09-05 12:43
8.0.0 and 8.0.1

I think also in 7.x

**Comment by eldy** [comment] 2018-09-07 08:01
I can't reproduce with 8.0.2

**Comment by adiatis** [comment] 2018-09-07 08:22
Last stable release is 8.0.1. I can't try on 8.0.2.

I tried also on demo.dolibarr.org. See video how I can reproduce the error. See screen recorder in zip.

https://demo.dolibarr.org/projet/tasks/time.php?id=38

[dolibarr-error-task-time-edit.zip](https://github.com/Dolibarr/dolibarr/files/2360203/dolibarr-error-task-time-edit.zip)

**Comment by atm-maxime** [comment] 2019-05-18 13:34
Do you still have the issue ? Otherwise can you close it ?

**Closed as completed** 2019-06-01 15:23 UTC
