### ISSUE TITLE
Zipcode Auto search for City & State/Province not working since update to 5.0

### ISSUE THREAD

**Issue by bharatkaushik1** [Dolibarr/dolibarr#6545] opened 2017-03-19 05:38 UTC
# Bug
Zipcode Auto search for City & State/Province not working since update to 5.0

## Environment
- **Version**: 5.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.6.30
- **Database**: MySQL or MariaDB 5.6.33-log
- **URL(s)**: htdocs/societe/soc.php

## Expected and actual behavior
Previously when we enter a zipcode it Auto search for City & State/Province, now its not working since update to 5.0 I am using this for Country India.

## Steps to reproduce the behavior
Create a new third party.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
None

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by gschratzer** [comment] 2017-03-20 11:38
i think that is the same topic i wrote already in #6541

there you can find a workaround

**Comment by marcosgdf** [comment] 2017-06-19 17:13
Duplicate of #6541

**Closed as completed** 2017-12-01 23:08 UTC
