### ISSUE TITLE
Upgrade code should be compatible with legacy systems to warn users of unsupported platform

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#3727] opened 2015-10-13 11:43 UTC
Lots of posts about this php error message T_PAAMAYIM_NEKUDOTAYM
"Parse error : syntax error, unexpected T_PAAMAYIM_NEKUDOTAYM, expecting',' or')' in /home/creativeyn/www/dolibarr-3.4.0/htdocs/core/lib/functions.lib.phpo on line 76"

In our source we heve methods call like
$class->method()  and some developpers write $class::method().
But some older php versions doen't accept the second form of method calls. 
Developpers should write code, compatible with the min php version indicated in dolibarr install to avoid this or change the php min version for Dolibarr.
This is a basic code writing rule, but some user who install dolibarr get problems on online servers

**Comment by FHenry** [comment] 2015-10-13 12:02
The syntax $class::method() is normal since PHP 5.3 and this is the right syntax to call static method. 
On the other side with a php 5.4 or 5.5 we have a warning if call static method with $class->method().
And php 5.3 is the minimum version for Dolibarr. I also read the message on the forum and you give the right answer : updagre PHP version

**Comment by rdoursenaud** [comment] 2015-10-15 07:50
Well, the upgrade procedure should check for the minimum required PHP version and prevent any upgrade without the requirements met.
If it does not, it's a serious bug!

Self-reminder: somewhat related to #3179

**Comment by rdoursenaud** [comment] 2015-10-15 07:54
Hum, after thinking a bit more about it, I think the upgrade code itself may use this code and trigger the error.
Supporting a good upgrade path from any version seems reasonable. For this, we must ensure that all code in `htdocs/install` can run even on obsolete PHP versions.

**Comment by FHenry** [comment] 2015-10-15 07:57
Yes your right, but how to solve this,  
$class::method() => crash on bad version
$class->method() => warning on good version 
Should we remove static method from DB class to avoid that ?

**Comment by rdoursenaud** [comment] 2015-10-15 08:45
Hum, there's only one static method in DoliDB: `convertSQLFromMysql()` and it's never statically called, so I don't think that's where the problem lies.
From the bug report, it seems that some install code uses the deprecated `getStaticMember()` which leads to this behavior. But for the life of me, I can't find any code using it since 3.7.

**Comment by rdoursenaud** [comment] 2015-10-15 08:49
Also the "lots of posts" seem a bit inflated. I only found one: http://www.dolibarr.fr/forum/8-mise-a-jour/54023-mise-a-jourimpossible-3-4-0-3-8-0

**Comment by tiaris** [comment] 2015-10-15 13:01
I have encoutered it in some migrations, and updating php (or php settings) resolved problem
I think we should check if server php version is right against dolibarr's php min version in migration script to avoid this to user.

**Comment by eldy** [comment] 2015-10-18 18:45
There is already a test done into first page of install and migration process. Into page "check.php".
@tiaris Don't you get the error message saying php < 5.3 was too old ? You should. What was php version before upgrade ?

**Comment by rdoursenaud** [comment] 2015-10-22 13:52
It's a chicken and eggs problem.
Since `check.php` loads and uses some of our libraries that are PHP 5.3 only the syntax error is issued before our own code gets a chance to warn the user.
To prevent this behavior, we'd have to make sure code contained in the install folder is PHP 4 compatible and is self contained (i.e.: does not include core classes and libraries).
Or maybe redesign the code so that the check is first, mandatory and self contained.

**Comment by eldy** [comment] 2015-11-02 15:20
If fatal php version pb occurs at first page of migration, then migration can't be done, and user will have no choice than upgrading php if he want to migrate or restore files he has overwrite with new version to cancel.
If test is not fatal, the warning should works.

**Comment by rdoursenaud** [comment] 2015-11-02 15:27
@eldy Yes, that's the current behavior.
But less technically inclined users are left wondering because as stated in the first post, the PHP message is cryptic as hell (Thanks PHP devs, makes us look good, really…) and won't even be displayed at all if best practices are observed.

**Comment by simnandez** [comment] 2017-09-28 08:01
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:01 UTC
Labels: Works for me / Can't reproduce, Bug
