### ISSUE TITLE
Allow hiding the left menu (again)

### ISSUE THREAD

**Issue by PlanPc** [Dolibarr/dolibarr#6174] opened 2016-12-15 10:15 UTC
# Bug

## Environment
- **Version**: 4.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.4.45
- **Database**: MySQL 5.5.52-cll-lve
- **URL**: /erp/compta/paiement.php?facid=XXX&action=create&accountid=1

## Report

1. - No more is possible to pay a customer bill, passing the amount with Javascript, as it was before in 3.9.3. Why? It was helpy, it showed a little arrow to copy the amount in the payment field.

2. - Also the vertical menu doesn´t collapse anymore.., also a javascript function, i think. Now the vertical menu is fixed, ever. Also was a help for small screens where users can decide to show it or not averytime a page was load.

More extrange is that option to enable or disable Javascript with Ajax, exist the same thn before in https://dolibarr_folder/admin/ihm.php but seems to do nothing at all.

Thank you

**Comment by rdoursenaud** [comment] 2017-01-16 19:54
Please refrain from mixing multiple issues. This makes it hard for maintainers to track the status.

Anyway,

1. This feature is an unsupported hidden feature: ```INVOICE_AUTO_FILLJS```. See: https://wiki.dolibarr.org/index.php/Setup_Other
That being said, it works for me on the latest Dolibarr 4.0.3 once set to ```true```.

2. Don't remember seeing this feature. Which theme were you using?

3. ?! This still works as intended to me. Yet, we're in 2017 and the whole web is relying on JavaScript more and more, so is Dolibarr. With the move towards HTML5 and EcmaScript being part of the spec, you can expect this to be ancient history in a not-so-distant future ;)

**Comment by PlanPc** [comment] 2017-01-16 20:41
Thank you Raphaël and sorry for the mixing, I thought it was all related to same javascript function with the last version 4, but I take note for next issues, if any.


**1.**  Just added `INVOICE_AUTO_FILLJS` and the little arrow is back again, Thank you.

**2.**  This option was enabled / disabled here: 
Main page of **Dolibarr**, **Configuration** --> **Enviroment**, last block, then 4º line option, translated from Spanish, must be something like "Disable Javascript and Ajax functions (Recommended for blind people or text browsers)". 
My theme is **eldy**, unmodified. Have some third party modules, but tested disabling them all, one by one, and nothing change about this.
When disable this option, (disables javascript), vertical menu was static (and the arrow from point 1 ceased to exist too), when enabled, vertical menu can collapse horizontally hiding to left side of screen pushing a little tab with the mouse or with shortcut: Ctrl + Left Arrow in keyboard.

Since version 4  and after upgrade to 4.0.2, this option does not change how the vertical menu works, is just always there fixed.

**3.**  About that point...,  is the first time I ear _EcmaScript_, I´m getting older, thank you for remind me. You are pushing Dolibarr to next level. In next days update to new 4.0.3 and try again.

Thank you a lot

Best Regards

**Comment by rdoursenaud** [comment] 2017-01-16 21:56
You're welcome.

Yeah, EcmaScript is the fancy name of the standardized/uniformized/cross-platform JavaScript nothing more.  It's been around for a while now. But at the end of the day it's still just JavaScript minus the various vendors' idiosyncrasies. That's why I use and favor learning this more generic term which means better global support ;) Yay for standards !

Regarding point 2, I can't seem to be able to track it down. I've been using and developing for Dolibarr since a few years now but I've never seen this.

**Comment by rdoursenaud** [comment] 2017-01-16 22:02
Ok, I've tracked down the removal at commit 7ce82aaf1616b01be3593c1267f99a776cc4e130.

Upon closer inspection, this code was experimental in Dolibarr 3.9.
The configuration is hidden behind the MAIN_FEATURES_LEVEL in the menu setup > other.
This explains why I never stumbled upon it.
That's what you get for using experimental or unfinished features.
Please keep MAIN_FEATURES_LEVEL at 0 or be prepared to face the consequences!

Now it says in the commit message that it's going to be replaced by a better solution. Any ETA @eldy?

**Comment by rdoursenaud** [comment] 2017-01-16 22:04
The rest of the issues being fixed I'll rename the issue to track the progresses on the left menu hiding feature request. Sounds good?

**Comment by PlanPc** [comment] 2017-01-16 23:32
Sounds pretty good !, good work! 

Can´t remember my first dolibarr, I think it was 3.2.2 but that option (disable javascript) has always be there, now with 4.0.2 still, but not using `MAIN_FEATURES_LEVEL=1`, just zero

Best Regards my friend

**Comment by atm-maxime** [comment] 2018-12-01 15:24
I close this issue as there's a task to work on the look and feel here : #9429

**Closed as completed by atm-maxime** 2018-12-01 15:24 UTC
Labels: Feature request
