### ISSUE TITLE
Bug: supplier invoice modification - SQL error

### ISSUE THREAD

**Issue by vanyolai** [Dolibarr/dolibarr#5112] opened 2016-04-27 10:12 UTC
# Environment
- **Version**: 3.9.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.4.45
- **Database**: MySQL or MariaDB 5.6.29-log
- **URL**: /dolibarr/fourn/facture/card.php?id=16
# Report

Modifying a line in the supplier bill (in this case the price) causes a MySQL error:
`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(HU27), localtax1_tx = 0, localtax2_tx = 0, localtax1_type = '0', localtax2_type' at line 1`

**Comment by aschio** [comment] 2016-06-04 17:19
The bug is caused by code field in llx_c_tva. When you insert a new Vat rate from dictionary page, infact field code is required and it appears into tva combolist.

**Comment by atm-maxime** [comment] 2016-06-04 22:51
This issue has been fixed in latest 3.9. There's still work to do to have Dolibarr compliant with new accountancy module.

**Closed as completed by atm-maxime** 2016-06-04 22:51 UTC
