### ISSUE TITLE
Bug non numeric with PHP 7.1.5

### ISSUE THREAD

**Issue by Bagu** [Dolibarr/dolibarr#6919] opened 2017-05-31 20:00 UTC
# Bug
When using Dolibarr 5.0.2 + PHP 7.1.5, there are many PHP Warning:  A non-numeric value encountered

## Environment
- **Version**: [5.0.2]
- **OS**: [Windows 10 Pro]
- **Web server**: [Apache 2.4.25 x64  + fcgid 2.3.9]
- **PHP**: [PHP 7.1.5 NTS]
- **Database**: [MariaDB 10.1.23]

## Suggested implementation
To correct some of them, i have done some changes : 
\comm\card.php line 69
\compta\bank\index.php, line 60
\compta\resultat\clientfourn.php, line 59
Replace : 
if ($page == -1) { $page = 0; }
By : 
if ($page == -1 OR !is_numeric($page)) { $page = 0; }

\compta\paiement\cheque\card.php, line 56
Replace : 
if ($page < 0) { $page = 0 ; }
By : 
if ($page < 0 OR !is_numeric($page)) { $page = 0 ; }

There are two other error in : 
\societe\class\societe.class.php line 1643
and
\compta\ajaxpayment.php lige 69 

But i don't know how to correct it.

**Comment by SBA18** [comment] 2017-06-08 13:15
I get the same error with Dolibarr v5.0.3 and I just disable the php error display in php.ini (displayError=Off)and no more error.

**Comment by Bagu** [comment] 2017-06-08 13:37
It's not a solution... Let's close our eyes if a wall appear on the middle on the road --'

**Comment by marcosgdf** [comment] 2017-06-10 15:19
Duplicate of #6712

**Comment by eldy** [comment] 2017-09-26 10:39
Closed as duplicate.
Als should be fixed with 6.0.1

**Closed as completed by eldy** 2017-09-26 10:39 UTC

**Comment by ThieBurg** [comment] 2017-10-19 20:39
Hi folks,

I recently updated to 6.0.2 and still facing to the "non numeric" warnings with PHP 7.1 on accountancy_dispatch_customer pages. So returned back to 7.0.
For sure, this is far to be ccritical.

In any case, congratulations to all contributors. You built/are duilding a fantastic ERP/CRM solution that allows me to develop my  business.

Many tks again,
Thierry
