### ISSUE TITLE
Bug: tramission projet depuis liste des modeles

### ISSUE THREAD

**Issue by Smartbe** [Dolibarr/dolibarr#5389] opened 2016-06-23 11:06 UTC
# Environment
- **Version**: 3.9.2
- **OS**: Linux
- **Web server**: Apache/2.4.18 (Ubuntu)
- **PHP**: apache2handler 7.0.4-7ubuntu2.1
- **Database**: MySQL or MariaDB 5.7.12-0ubuntu1
- **URL**: /erp/htdocs/index.php?mainmenu=home
# Report

lors de la création d'une facture depuis un modeles (liste de modeles) , le projet selectionné doit être réencodé sur le document final. De plus, l'écran ne permet plus de voir les barres du dessus.

**Comment by atm-geoffrey** [comment] 2016-06-30 12:42
Hi @Smartbe, i think this is not a bug and not a good idea to keep project link in predefined invoices
that's could be a new option in invoice module, @eldy what do you think about that?

@Smartbe what do you mean by "De plus, l'écran ne permet plus de voir les barres du dessus." ? Can you explain with more details please?

**Comment by eldy** [comment] 2016-07-29 15:06
With 4.0, if a project is defined on a template, then it will be set on generated invoice to same value (should be fixed). We suppose that a template is for a project if it is set, so that every invoice then is for this project too.
If you don't want to have it kept, just do not set the project on template.

**Closed as completed by eldy** 2016-07-29 15:06 UTC
