### ISSUE TITLE
Bug: workflow module doesn't work correctly on linked invoice

### ISSUE THREAD

**Issue by aschio** [Dolibarr/dolibarr#5309] opened 2016-06-05 10:45 UTC
VERSION: 4.0.0-beta (and 3.9.x)
Workflow module is active
"Classify linked source customer order(s) to billed when customer invoice is set to paid" set to ON
1. Create and validate customer order
2. Create invoice linked to my customer order (directly from order)
3. When I do a payment of the invoice, the invoice status become PAID, but customer order status doesn't become BILLED.

**Comment by eldy** [comment] 2016-06-06 11:35
Can't reproduce on current branch of 3.9.
Ca, you confirm on 3.9.2 ?

**Comment by simnandez** [comment] 2017-12-01 22:35
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Closed as completed by simnandez** 2017-12-01 22:35 UTC
