### ISSUE TITLE
PDF generation

### ISSUE THREAD

**Issue by jasch0825** [Dolibarr/dolibarr#12809] opened 2020-01-07 13:47 UTC
If I put a free text in commercial documents under: 
Home->Setup->Modules/Application->Invoices/Proposal etc. then the documents will be look like in example 1 & 2 

What can I do to solve this Problem? 
I use the default templates and Version 10.0.5

## Example 1
![2020-01-07_14-37](https://user-images.githubusercontent.com/56758697/71899264-a21fcf00-315b-11ea-8d96-1871629b4008.png)
## Example 2
![2020-01-07_14-30](https://user-images.githubusercontent.com/56758697/71899351-cbd8f600-315b-11ea-90fe-fbe438e92b39.png)

**Comment by mapiolca** [comment] 2020-02-04 08:22
You can buy this module : [https://www.dolistore.com/fr/modules/1036-CGV---Conditions-G--n--rales-de-vente.html?search_query=CGV&results=16](url)

**Comment by atm-maxime** [comment] 2020-02-04 21:01
Or use the hidden option MAIN_FREETEXT_HEIGHT to have more place for your freetext.

**Comment by dpriskorn** [comment] 2020-08-07 09:28
Not a bug, ask in the forums if further help is needed. Closing

**Closed as completed by dpriskorn** 2020-08-07 09:28 UTC
