### ISSUE TITLE
Bug: Situation invoice blocked by discount

### ISSUE THREAD

**Issue by Taouche** [Dolibarr/dolibarr#7516] opened 2017-09-27 22:13 UTC
# Bug

## Environment
- **Version**: 6.0.1
- **OS**: Linux
- **Web server**: Apache/2.4.10 (Ubuntu)
- **PHP**: fpm-fcgi 7.1.0
- **Database**: MySQL or MariaDB 5.7.17-0ubuntu0.16.04.1
- **URL**: /htdocs/comm/remise.php?id=33

## Report

I have a situation invoice with a credit integrated on this bill.
![image](https://user-images.githubusercontent.com/7584849/30940551-b7fc5d70-a3e1-11e7-893c-99acf18b4fcb.png)

When I try to create the seconde one invoice situation, I have the credit to 100% but when I click to create the draft, I have an error message that tell me "the discount has already been awarded"

![image](https://user-images.githubusercontent.com/7584849/30940587-d6f88d7a-a3e1-11e7-8d28-08b36afb2c13.png)

**Comment by atm-maxime** [comment] 2018-03-09 21:23
Thanks for the feedback. We'll look into it.
But for now, situation invoices are a hidden feature.

**Comment by atm-maxime** [comment] 2019-06-01 15:03
Can you check on recent Dolibarr version ? There have been many improvments on situation invoices. If OK, you can close this issue. Thanks.

**Comment by ksar-ksar** [comment] 2021-02-11 11:05
Have you checked recent versions of Dolibarr ?

Issue have not been updated since a long time => Will be closed.

You can re-open it if the issue is still present in recent Dolibarr versions

**Closed as completed by ksar-ksar** 2021-02-11 11:05 UTC
Labels: Bug
