### ISSUE TITLE
Error on instalation dolibarr 3.9.0 in postgresql

### ISSUE THREAD

**Issue by tiagorodrigues07** [Dolibarr/dolibarr#4926] opened 2016-03-31 17:13 UTC
Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_advtargetemailing FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();    Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_advtargetemailing" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_askpricesupplier FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();     Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_askpricesupplier" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_askpricesupplier_extrafields FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();     Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_askpricesupplier_extrafields" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_askpricesupplierdet_extrafields FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();  Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_askpricesupplierdet_extrafields" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_ecm_documents FOR EACH ROW EXECUTE PROCEDURE update_modified_column_date_u();     Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_ecm_documents" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_printer_ipp FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();  Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_printer_ipp" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_time_basket FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();  Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_time_basket" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_timebasket_counter FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();   Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_timebasket_counter" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

**Comment by marcosgdf** [comment] 2016-04-04 00:55
Duplicate of bug #4756

**Closed as completed** 2016-07-06 13:11 UTC
