### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by johnotoole68** [Dolibarr/dolibarr#6856] opened 2017-05-16 23:42 UTC
# Bug: Bank Account Accounting Account is not recorded.

## Environment
- **Version**: 5.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.0.18
- **Database**: MySQL or MariaDB 5.5.5-10.0.28-MariaDB-wsrep
- **URL**: /htdocs/compta/bank/card.php?action=edit&id=1

## Report
Bank account accounting account is not recorded in llx_bank_account table.

steps to reproduce: 
1. Select an existing Bank account.
2. Press MODIFY.
3. Populate "Accounting account" field with a valid accounting account, and press MODIFY.
4. Note that the Accounting Account is not populated. 
5. Run the following SQL sentence to verify that the account is not recorded:
    SELECT account_number FROM u171263166_devv5.llx_bank_account;

**Comment by simnandez** [comment] 2017-05-26 15:38
Works for me in 5.0.3

**Comment by simnandez** [comment] 2017-09-28 08:41
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:41 UTC
Labels: Works for me / Can't reproduce
