### ISSUE TITLE
Error when make a proposal from intervention

### ISSUE THREAD

**Issue by Solatec** [Dolibarr/dolibarr#9657] opened 2018-10-02 11:06 UTC
# Bug
Error when make a proposal from intervention

## Environment
- **Version**: 8.0.2
- **OS**: Ubuntu 16.04
- **PHP**: 7.0

## Expected and actual behavior
When I make a proposal from intervention cause the following error:

Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20180928211711
Dolibarr: 8.0.2
Level of features: 0
PHP: 7.0.32-0ubuntu0.16.04.1
Server: Apache/2.4.18 (Ubuntu)
OS: Linux correu.solatec.cat 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0

Requested URL: /comm/propal/card.php
Referer: https://192.168.1.1/comm/propal/card.php?action=create&origin=fichinter&originid=167&socid=33
Menu manager: eldy_menu.php

Database type manager: mysqli
Latest database access request error: INSERT INTO llx_element_element (fk_source, sourcetype, fk_target, targettype) VALUES (167, 'fichinter', 233, 'propal')
Return code for latest database access request error: DB_ERROR_RECORD_ALREADY_EXISTS
Information for latest database access request error: Duplicate entry '167-fichinter-233-propal' for key 'idx_element_element_idx1'

Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20180928211711
Dolibarr: 8.0.2
Level of features: 0
PHP: 7.0.32-0ubuntu0.16.04.1
Server: Apache/2.4.18 (Ubuntu)
OS: Linux correu.solatec.cat 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0

Requested URL: /comm/propal/card.php
Referer: https://192.168.1.1/comm/propal/card.php?action=create&origin=fichinter&originid=167&socid=33
Menu manager: eldy_menu.php

Database type manager: mysqli
Latest database access request error: INSERT INTO llx_element_element (fk_source, sourcetype, fk_target, targettype) VALUES (167, 'fichinter', 233, 'propal')
Return code for latest database access request error: DB_ERROR_RECORD_ALREADY_EXISTS
Information for latest database access request error: Duplicate entry '167-fichinter-233-propal' for key 'idx_element_element_idx1'

Warning: Cannot modify header information - headers already sent by (output started at /var/www/clients/client1/web51/web/htdocs/core/lib/functions.lib.php:3923) in /var/www/clients/client1/web51/web/htdocs/comm/propal/card.php on line 590

But the draft proposal was created, despite the error. And I can validate it without problems.

## Steps to reproduce the behavior
Create a proposal from intervention and create draft

**Comment by atm-maxime** [comment] 2018-10-27 09:22
Could not reproduce in 8.0.3, proposal was created correctly.
I think this comes from your installation because the database error points out that the error ocurs when the system tries to link the intervention to the proposal, as if the proposal id has already been used before. If you create a draft proposal from nothing and then try again from your intervention, it should work.

**Comment by Solatec** [comment] 2018-10-27 10:48
Hello atm-maxime

I tested in a clean install Dolibarr 8.0.2.

Only 1 customer, 1 Intervention and when I create proposal, and click Create Draft the error is produced...

------------------------------------------------------------------------------

> Dolibarr has detected a technical error.
> This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
> Date: 20181027124609
> Dolibarr: 8.0.2
> Level of features: 0
> PHP: 7.0.32-0ubuntu0.16.04.1
> Server: Apache/2.4.18 (Ubuntu)
> OS: Linux correu.solatec.cat 4.15.0-38-generic #41~16.04.1-Ubuntu SMP Wed Oct 10 20:16:04 UTC 2018 x86_64
> UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
> 
> Requested URL: /comm/propal/card.php
> Referer: https://dolitest.solatec.cat/comm/propal/card.php?action=create&origin=fichinter&originid=1&socid=1
> Menu manager: eldy_menu.php
> 
> Database type manager: mysqli
> Latest database access request error: INSERT INTO llx_element_element (fk_source, sourcetype, fk_target, targettype) VALUES (1, 'fichinter', 2, 'propal')
> Return code for latest database access request error: DB_ERROR_RECORD_ALREADY_EXISTS
> Information for latest database access request error: Duplicate entry '1-fichinter-2-propal' for key 'idx_element_element_idx1'
> 
> Dolibarr has detected a technical error.
> This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
> Date: 20181027124609
> Dolibarr: 8.0.2
> Level of features: 0
> PHP: 7.0.32-0ubuntu0.16.04.1
> Server: Apache/2.4.18 (Ubuntu)
> OS: Linux correu.solatec.cat 4.15.0-38-generic #41~16.04.1-Ubuntu SMP Wed Oct 10 20:16:04 UTC 2018 x86_64
> UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
> 
> Requested URL: /comm/propal/card.php
> Referer: https://dolitest.solatec.cat/comm/propal/card.php?action=create&origin=fichinter&originid=1&socid=1
> Menu manager: eldy_menu.php
> 
> Database type manager: mysqli
> Latest database access request error: INSERT INTO llx_element_element (fk_source, sourcetype, fk_target, targettype) VALUES (1, 'fichinter', 2, 'propal')
> Return code for latest database access request error: DB_ERROR_RECORD_ALREADY_EXISTS
> Information for latest database access request error: Duplicate entry '1-fichinter-2-propal' for key 'idx_element_element_idx1'
> 
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/clients/client1/web51/web/htdocs/core/lib/functions.lib.php:3923) in /var/www/clients/client1/web51/web/htdocs/comm/propal/card.php on line 590

---------------------------------------------------------------------
But if I go to Comertial proposal list, a draft is correctly created.
Any suggestions?

**Comment by Solatec** [comment] 2018-10-27 11:12
And the same result with Dolibarr 9.0.0 beta...

**Comment by atm-maxime** [comment] 2018-10-27 14:42
Sorry, I did the same on a fresh install, and nothing goes wrong with me. What's odd in your error message is that it's like it's trying to link the intervention and the proposal twice... I also tried on dolibarr official demo and it works...

**Comment by Solatec** [comment] 2018-10-27 14:59
Is it possible to be something of the server?
I use

Ubuntu 16.04.5 LTS
Apache/2.4.18 (Ubuntu) 
PHP 7.0.32-0ubuntu0.16.04.1
mysql  Ver 15.1 Distrib 10.0.36-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Where is 8.0.3 version for download?

Tanks!!!

**Comment by atm-maxime** [comment] 2018-10-27 16:05
Perhaps a trouble while transferring Dolibarr files to your server,  I can't tell... try a fresh install by downloading last stable version, try on a different server, ...
8.0.3 will be out soon.

**Closed as completed by atm-maxime** 2018-10-27 16:05 UTC

**Comment by Solatec** [comment] 2018-10-27 16:19
Ok. 
When I make a fresh install some errors appears:


> Creació de les claus i índexs de la taula llx_bookmark.key Request 342 : ALTER TABLE llx_bookmark ADD UNIQUE uk_bookmark_url   (fk_user, url) | Error de SQL DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> -- | --
> Creació de les claus i índexs de la taula llx_boxes_def.key Request 349 : ALTER TABLE llx_boxes_def ADD UNIQUE INDEX uk_boxes_def (file, entity, note) | Error de SQL DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Creació de les claus i índexs de la taula llx_c_email_senderprofile.key Request 369 : ALTER TABLE llx_c_email_senderprofile ADD UNIQUE INDEX uk_c_email_senderprofile(entity, label, email) | Error de SQL DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Creació de les claus i índexs de la taula llx_contrat.key Request 481 : ALTER TABLE llx_contrat ADD UNIQUE INDEX uk_contrat_ref (ref, entity) | Error de SQL DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Creació de les claus i índexs de la taula llx_default_values.key Request 504 : ALTER TABLE llx_default_values ADD UNIQUE INDEX uk_default_values(type, entity, user_id, page, param) | Error de SQL DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Creació de les claus i índexs de la taula llx_ecm_files.key Request 512 : ALTER TABLE llx_ecm_files ADD UNIQUE INDEX uk_ecm_files (filepath, filename, entity) | Error de SQL DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Creació de les claus i índexs de la taula llx_entrepot.key Request 521 : ALTER TABLE llx_entrepot ADD UNIQUE INDEX uk_entrepot_label (ref, entity) | Error de SQL DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Creació de les claus i índexs de la taula llx_links.key Request 624 : ALTER TABLE llx_links ADD UNIQUE INDEX uk_links (objectid,label) | Error de SQL DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Creació de les claus i índexs de la taula llx_menu.key Request 639 : ALTER TABLE llx_menu ADD UNIQUE INDEX idx_menu_uk_menu (menu_handler, fk_menu, position, url, entity) | Error de SQL DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Creació de les claus i índexs de la taula llx_product_attribute.key Request 683 : ALTER TABLE llx_product_attribute ADD UNIQUE INDEX uk_product_attribute_ref (ref) | Error de SQL DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Creació de les claus i índexs de la taula llx_resource.key Request 751 : ALTER TABLE llx_resource ADD UNIQUE INDEX uk_resource_ref (ref, entity) | Error de SQL DB_ERROR_1071 Specified key was too long; max key length is 767 bytes
> Creació de les claus i índexs de la taula llx_website_page.key Request 826 : ALTER TABLE llx_website_page ADD UNIQUE INDEX uk_website_page_url (fk_website, pageurl) | Error de SQL DB_ERROR_1071 Specified key was too long; max key length is 767 bytes

Dolibarr works but same error is produced...

**Comment by hregis** [comment] 2018-10-27 16:23
@Solatec 
use utf8 instead utf8mb4 for the collation of your database

**Comment by Solatec** [comment] 2018-10-27 16:52
I have made fresh install whit DB utf8_general_ci
No errors on install procedure, but same error in interventions...

**Comment by hregis** [comment] 2018-10-27 16:54
@Solatec 
what is the content of llx_element_element after the fresh install ?

**Comment by Solatec** [comment] 2018-10-27 17:05
No data in table...
