### ISSUE TITLE
Bug: Error in exchange of massive IVA

### ISSUE THREAD

**Issue by JuanBrillo** [Dolibarr/dolibarr#6003] opened 2016-11-17 08:59 UTC
# Bug
Using DoliWamp version 4.0.1 and given that I am getting many new products, updating prices and others, I have updated the IVA (Spanish tax) of new products, which were still at 0 € the price (Like many others that are only quoted on demand since prices are variable and I have to consult the manufacturer) and what is my surprise, that by changing it from 0% to 21% in the massive update of IVA, apart from updating the IVA to the desired amount, does a totally wrong thing, in all products to 0 € puts a price of 15.35 € (do not ask me why) and I am assuming to modify 1 to 1 all the products I had With € 0 of price, what I'm taking more than if I had changed the IVA of the products that I had to put in place of having to change now the price to ALL, those that were already in place and the new ones ...

## Environment
- **Version**: 4.0.1
- **OS**: Windows 10
- **Web server**: Apache/2.4.9 (Win32)
- **PHP**: 5.5.12
- **Database**: MySQL 5.0.45 

Sorry for the grammatical errors, the text has been translated by Google Translate

**Comment by eldy** [comment] 2016-11-22 19:27
Not specific to spain.
A protection should be added to change only if product price is not 0

**Comment by simnandez** [comment] 2016-11-25 22:00
I have tested now with git branch 4.0 and the price 0 is not changed by changing  from 0% to 21% in the massive update of IVA...

**Comment by simnandez** [comment] 2016-12-10 21:14
@JuanBrillo I cant reproduce it, so I close it. Please test it with the new versions if you have the error, open a new PR.

**Closed as completed by simnandez** 2016-12-10 21:14 UTC
Labels: Priority 1 - High / Blocking, Bug
