### ISSUE TITLE
Bug: Extrafield removal

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#5814] opened 2016-09-29 15:32 UTC
# Bug
## Environment
- **Version**: 4.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.5.38
- **Database**: MySQL or MariaDB 5.6.33
- **URL**: /haccp/projet/list.php?leftmenu=projects&search_status=1

**Comment by alimentarius** [comment] 2016-09-29 15:34
This it's what apears when i try to see project list:

O Dolibarr detectou um erro técnico.
This information can be useful for diagnostic:
Data: 20160929153223
Dolibarr: 4.0.0
Nivel de funções: 0
PHP: 5.5.38
Server: Apache
OS: Linux iberweb32a.ibername.com 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 00:57:44 UTC 2016 x86_64
UserAgent: Mozilla/5.0 (Windows NT 6.0; rv:49.0) Gecko/20100101 Firefox/49.0

Url solicitado: /haccp/projet/list.php?leftmenu=projects&search_status=1
Referer: http://alimentarius.pt/haccp/projet/index.php?mainmenu=project&leftmenu=
Gestão do menu: eldy_menu.php

Gestor do tipo de base de dados: mysqli
Latest database access request error: SELECT DISTINCT p.rowid as projectid, p.ref, p.title, p.fk_statut, p.fk_opp_status, p.public, p.fk_user_creat, p.datec as date_creation, p.dateo as date_start, p.datee as date_end, p.opp_amount, p.opp_percent, p.tms as date_update, p.budget_amount, s.nom as name, s.rowid as socid, cls.code as opp_status_code,ef.pr01a as options_pr01a FROM llxqe_projet as p LEFT JOIN llxqe_projet_extrafields as ef on (p.rowid = ef.fk_object) LEFT JOIN llxqe_societe as s on p.fk_soc = s.rowid LEFT JOIN llxqe_c_lead_status as cls on p.fk_opp_status = cls.rowid WHERE p.entity IN (1) AND p.fk_statut = 1 ORDER BY p.ref ASC LIMIT 26
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: Unknown column 'ef.pr01a' in 'field list'

**Comment by eldy** [comment] 2016-10-01 11:25
It seems an extra field on project with field name "pr01a" was created and removed.
Can you check the setup of project module on tab "complementary attributes" ?

**Comment by rdoursenaud** [comment] 2017-01-20 16:40
I don't know if it wise to hijack this issue but I remember having been bitten by this.

The culprit is the lack of code handling extrafields removal.
It's way too easy to remove them on multiple accounts:
- There's no confirmation dialog! Extra risky.
- No data check nor cleanup (lots of leftovers) because we lack private keys references.

**Comment by marcosgdf** [comment] 2017-06-19 16:12
Cannot reproduce...

**Comment by simnandez** [comment] 2017-12-01 22:42
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Closed as completed by simnandez** 2017-12-01 22:42 UTC
Labels: Bug
