### ISSUE TITLE
#Bug? confusion tables categorie_account and bank_class tables

### ISSUE THREAD

**Issue by benlo06** [Dolibarr/dolibarr#6906] opened 2017-05-29 14:46 UTC
Hello,
There is one menu for create Category in compta/bank/index.php?mainmenu=bank.
There is possibility to add categorie in "bank line" (page compta/bank/ligne.php?rowid=1 )
And the is not the good categories too  when we add new "line journal bank" (compta/bank/bankentries.php?action=addline&page=&contextpage=banktransactionlist-2&id=1&account=1)
Maybe categories are not the same ? Is it normal ? I think there is a migration from bank_class to categorie_account but there aren't finished.

But the forgeign key of table for fk_account is in bank table :+1: 
`
CREATE TABLE IF NOT EXISTS 'llx_categorie_account' (
  'fk_categorie' int(11) NOT NULL,
  'fk_account' int(11) NOT NULL,
  'import_key' varchar(14) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE 'llx_categorie_account'
 ADD PRIMARY KEY ('fk_categorie','fk_account'), ADD KEY 'idx_categorie_account_fk_categorie' ('fk_categorie'), ADD KEY 'idx_categorie_account_fk_account' ('fk_account');
`
But I don't see interest to add category in bank account.

I think this is an error, and I thinks all bank pages must be migrate with categorie_account table, and for this : I would like to change this schema with:

`
ALTER TABLE 'llx_categorie_account'
 ADD PRIMARY KEY ('fk_categorie','fk_account'), ADD KEY 'idx_categorie_account_fk_categorie' ('fk_categorie'), ADD KEY 'idx_categorie_account_fk_bank' ('fk_bank'); 
`

What do you think about this ?

Regards,
Benoit

**Comment by eldy** [comment] 2017-06-20 10:06
Which version ?
In last 5.0.* version, the menu suggest 2 types of categories
"New categories for bank account"
and
"New categories for transactions"

This should solve the confusion.

**Comment by simnandez** [comment] 2017-09-28 08:51
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:51 UTC
