### ISSUE TITLE
Bug into hook doPreMassActions of module class ActionsMulticompany

### ISSUE THREAD

**Issue by darthjong** [Dolibarr/dolibarr#24887] opened 2023-05-26 08:23 UTC
### Bug

Products/List still not populating all in my tables even after upgrading it to 17.0.2. Out of 1238, only 4 products are shown in page 1.

Here's the error generate in the logs:

2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error message: DB_ERROR_COLUMN_ALREADY_EXISTS Duplicate column name 'birth'
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error query: ALTER TABLE llx_user ADD COLUMN dateemployment date
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error message: DB_ERROR_COLUMN_ALREADY_EXISTS Duplicate column name 'dateemployment'
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error query: ALTER TABLE llx_user ADD COLUMN dateemploymentend date
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error message: DB_ERROR_COLUMN_ALREADY_EXISTS Duplicate column name 'dateemploymentend'
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error query: ALTER TABLE llx_user ADD COLUMN default_range integer
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error message: DB_ERROR_COLUMN_ALREADY_EXISTS Duplicate column name 'default_range'
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error query: ALTER TABLE llx_user ADD COLUMN default_c_exp_tax_cat integer
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error message: DB_ERROR_COLUMN_ALREADY_EXISTS Duplicate column name 'default_c_exp_tax_cat'
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error query: ALTER TABLE llx_extrafields ADD COLUMN langs varchar(24)
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error message: DB_ERROR_COLUMN_ALREADY_EXISTS Duplicate column name 'langs'
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error query: ALTER TABLE llx_extrafields ADD COLUMN fieldcomputed text
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error message: DB_ERROR_COLUMN_ALREADY_EXISTS Duplicate column name 'fieldcomputed'
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error query: ALTER TABLE llx_extrafields ADD COLUMN fielddefault varchar(255)
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error message: DB_ERROR_COLUMN_ALREADY_EXISTS Duplicate column name 'fielddefault'
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error query: ALTER TABLE llx_extrafields ADD COLUMN enabled varchar(255) DEFAULT '1'
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error message: DB_ERROR_COLUMN_ALREADY_EXISTS Duplicate column name 'enabled'
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error query: ALTER TABLE llx_extrafields ADD COLUMN help text
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error message: DB_ERROR_COLUMN_ALREADY_EXISTS Duplicate column name 'help'
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error query: ALTER TABLE llx_user_rights ADD COLUMN entity integer DEFAULT 1 NOT NULL
2023-05-26 07:35:29 ERR     180.191.100.191 DoliDBMysqli::query SQL Error message: DB_ERROR_COLUMN_ALREADY_EXISTS Duplicate column name 'entity'
2023-05-26 07:36:54 ERR     180.191.100.191 Error: Bug into hook doPreMassActions of module class ActionsMulticompany. Method must not return a string but an int (0=OK, 1=Replace, -1=KO) and set string into ->resprints
2023-05-26 07:50:15 ERR     180.191.100.191 Error: Bug into hook printFieldListFrom of module class ActionsMulticompany. Method must not return a string but an int (0=OK, 1=Replace, -1=KO) and set string into ->resprints
2023-05-26 07:50:15 ERR     180.191.100.191 Error: Bug into hook doPreMassActions of module class ActionsMulticompany. Method must not return a string but an int (0=OK, 1=Replace, -1=KO) and set string into ->resprints
2023-05-26 07:51:40 ERR     180.191.100.191 Error: Bug into hook doPreMassActions of module class ActionsMulticompany. Method must not return a string but an int (0=OK, 1=Replace, -1=KO) and set string into ->resprints
2023-05-26 07:51:43 ERR     180.191.100.191 Error: Bug into hook doPreMassActions of module class ActionsMulticompany. Method must not return a string but an int (0=OK, 1=Replace, -1=KO) and set string into ->resprints
2023-05-26 07:56:04 ERR     180.191.100.191 Error: Bug into hook doPreMassActions of module class ActionsMulticompany. Method must not return a string but an int (0=OK, 1=Replace, -1=KO) and set string into ->resprints
2023-05-26 07:59:20 ERR     180.191.100.191 Error: Bug into hook printFieldListFrom of module class ActionsMulticompany. Method must not return a string but an int (0=OK, 1=Replace, -1=KO) and set string into ->resprints
2023-05-26 07:59:20 ERR     180.191.100.191 Error: Bug into hook doPreMassActions of module class ActionsMulticompany. Method must not return a string but an int (0=OK, 1=Replace, -1=KO) and set string into ->resprints
2023-05-26 08:05:02 ERR     180.191.100.191 Error: Bug into hook doPreMassActions of module class ActionsMulticompany. Method must not return a string but an int (0=OK, 1=Replace, -1=KO) and set string into ->resprints
2023-05-26 08:08:12 ERR     121.58.234.74   Error: Bug into hook doPreMassActions of module class ActionsMulticompany. Method must not return a string but an int (0=OK, 1=Replace, -1=KO) and set string into ->resprints
2023-05-26 08:08:20 ERR     121.58.234.74   Error: Bug into hook doPreMassActions of module class ActionsMulticompany. Method must not return a string but an int (0=OK, 1=Replace, -1=KO) and set string into ->resprints

### Environment Version

17.0.2

### Environment PHP

PHP 8

### Environment URL(s)

/product/list.php?leftmenu=product&type=0

### Attached files

![image](https://github.com/Dolibarr/dolibarr/assets/134275057/f8b6c210-a087-434f-9454-0d287f465d47)

**Comment by ksar-ksar** [comment] 2023-05-29 18:56
Hello,

You have two types of Errors.
The first ones seems to be linked to migration process ? You have anyway something strange in the database.
The last ones are related to hook system and multicompany module => You need to ask multicompany developer ?

**Comment by ksar-ksar** [comment] 2023-05-29 19:18
Duplicate of #24844

**Comment by hregis** [comment] 2023-05-30 08:41
@ksar-ksar @darthjong 
"Error: Bug into hook" are not a blocking error, it's just a warning !!

**Comment by hregis** [comment] 2023-05-30 08:43
@ksar-ksar @darthjong 
Multicompany is not the cause of the error, check you apache/php logs!!!!!!!!!!!!

**Comment by ksar-ksar** [comment] 2023-05-30 08:49
Thanks @hregis

**Closed as completed** 2023-06-10 16:38 UTC
Labels: Bug invalid or external
