### ISSUE TITLE
Division by zero in /compta/prelevement/fiche-stat.php on line 144

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#5378] opened 2016-06-21 06:17 UTC
# Bug

Division by zero in /compta/prelevement/fiche-stat.php on line 144
## Environment
- **Version**: 3.9.2
- **URL(s)**: .../compta/prelevement/fiche-stat.php?id=1

**Comment by marcosgdf** [comment] 2016-06-22 18:59
Duplicate of bug #4447

**Comment by aconits** [comment] 2016-06-30 13:22
Hi Marcos,

Work's for me in 3.9 and 3.8,
I can't reproduce this error, how you make a withdraw request with 0 as amount ?

**Comment by eldy** [comment] 2016-11-22 20:08
Closed as duplicate of #4447

**Closed as completed by eldy** 2016-11-22 20:08 UTC
