### ISSUE TITLE
[ADHERENT] Fail adding or editing welcome email for a type

### ISSUE THREAD

**Issue by squarou** [Dolibarr/dolibarr#8183] opened 2018-02-12 15:48 UTC
# Bug

## Environment
- **Version**: 6.0.5
- **PHP**: 7.1
- **Database**: MySQL
- **URL(s)**: adherents/type.php?action=edit&rowid=3

## Expected and actual behavior
Expected : modifying and saving, the email block would the content.
Actual : modifying and saving, the email block return 1

## Steps to reproduce the behavior
Go to Adhérents > Type > Click a type > Edit
Write something in the text field of the welcome email
Save
See the content is = 1

NB: Putting the content directly in the DB works ==> the welcome email field as the content.

**Comment by laudeco** [comment] 2018-02-12 16:55
This seems to be fixed in 7.0 because I cannot reproduce ...
Could you checkout this version and let me know if the error is still present ?

But I got it on 6.0, I'll fix it right know

Cheer
L.

**Comment by eldy** [comment] 2018-02-15 12:41
This bug seems to be fixed into last recent stable version, so I close the bug

**Closed as completed by eldy** 2018-02-15 12:41 UTC
