### ISSUE TITLE
Margin is incorrect used with POS

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#2591] opened 2015-04-11 16:30 UTC
A forume user reported a bug http://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/52810-module-point-de-vente-marge
Margin is incorrect on invoices generated by the POS Module

**Comment by marcosgdf** [comment] 2015-04-12 19:12
Can you please be more specific like... which version is affected, which is the problem and/or how to reproduce it?

**Comment by fappels** [comment] 2015-04-13 13:48
Already fixed in 3.6.2, commit: b1a4b8e7d0aa8ff376e5dbfcf89260eb6e189d62

**Comment by fappels** [comment] 2015-04-13 14:11
Though a better Fix should be to use latest buying price (Doliforge task #1910 https://doliforge.org/tracker/?func=detail&group_id=144&aid=1910&atid=247)

**Comment by tiaris** [comment] 2015-04-13 14:36
I think best would be to use products pmp (for a product) if it exists, 
or latest buy price. this could be a way to calcultate pmp if it does 
not exist
Caution because in standard Dolibarr uses the best buyprice (minima), 
which is not good.

greetings

**Comment by BebZ** [comment] 2015-04-13 15:15
@fappels now we should use Issues in github to reference tasks or bugs, may I reference this one as a fet. request ? Add find most recent fournisseur price for POS margin and default PU

**Comment by fappels** [comment] 2015-04-13 15:54
@BebZ yes you may, one old Doliforge ticket less, I will close it. Also add the pmp option proposed by tiaris, not a bad idea.

**Comment by fappels** [comment] 2015-05-20 10:08
On which Dolibarr version to be fixed? Needs new method in ProductFournisseur class to get pmp.

**Comment by rdoursenaud** [comment] 2015-05-20 14:24
If it needs a new feature, the target branch is develop AFAIK.

**Comment by BebZ** [comment] 2015-06-07 15:05
New comment referenced on FR forum : 
http://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/52810-module-point-de-vente-marge#60712

--translation by me
--VERSION DOLIBARR 3.7.2, tested, and still problems betwenn modules Margin & POS
Je viens de passer en dolibarr 3.7.2 et le problème de Marge et module point de vente est toujours existant :
--When he goes on the invoice created by POS he has a right calculation of margin : 
sale price - buy price
- En allant sur la facture crée par le module point de vente, j'ai bien la marge réelle qui apparait sur le tableau de marge (prix de vente - prix d'achat)
--When he goes on margin module (/compta) the invoice gives buyprice=0 and margin = sale price.
- En passant par le module marge (compta), la même facture donne prix d'achat=0 et marge = prix de vente.

--also, bug on margin module, choice of a specific product's margin can't be made on every products, some products semm missing on the list of choice.

Au passage, il a un bug au niveau de marge par produit, le choix peut se faire uniquement sur la liste déroulante de x produit. La liste est pas complète.

**Comment by rdoursenaud** [comment] 2015-06-08 11:18
@BebZ We already stated that the target branch for this issue's resolution is develop. This means we can't fix this issue before the 3.8 release.
Please also refrain from mixing different bugs here. We are not on a forum but on the issue tracker. This tool is used by developers to manage their time fixing issues. As much as we appreciate the time you take to report issues from the forum, please be nice to them and open another issue. Thanks!

**Comment by BebZ** [comment] 2015-06-08 13:15
ok other bug reported on https://github.com/Dolibarr/dolibarr/issues/2982

**Comment by eldy** [comment] 2015-09-12 11:12
Some major changes were done into 3.8 to fix a lot of problems with margin calculation.
I think calculcation wit POS is still not supported.
To fix, this a PR for develop branch is welcome but must match the way 3.8 work.
margin is calculated by default on PMP price or on best supplier price, depending on the first option set into margin module setup page.

**Comment by fappels** [comment] 2015-09-12 11:48
Will rewrite PR to use new 3.8 margin calculation.

**Comment by fappels** [comment] 2015-09-18 12:33
@eldy How can I get best supplier price. Margin admin says  'Best supplier price defined on product card', can't find it on product card.
Remark: printObjectLines shows 'buy price' in title bar, shouldn't it be better to show 'margin price' because you can mix buyprice with wap.

**Comment by eldy** [comment] 2015-10-18 20:07
@fappels
You can rename "buy price" into "Buying/Cost price". It is a better name now this field content depends on setup and may contain wap (a wap price is also a buy price, just an average buy price).

To get the margin price when coming from POS, you must:
- If option of margin is "Margin on Best supplier price", use find_min_price_product_fournisseur() to find this price.
- If option of margin is "Margin on Weighted Average Price (WAP)", use the wap price of product and if not defined, user value returned by find_min_price_product_fournisseur()

**Comment by fappels** [comment] 2015-10-19 07:24
@eldy 
I think we should align with getSupplierPrices and use list_product_fournisseur_price($idprod, 'set sort so best price will be first record'); and define a config property in fournisseur.product.class.php so the default (best) price in the commercial forms will be the same as the one for POS.

**Comment by eldy** [comment] 2015-10-19 23:03
getSupplierPrices is not dedicated to find bets supplier price but to provide list to select prices from gui.

There is already another function to get "best supplier price". It is find_min_price_product_fournisseur().
So if everyone use it, we should get same value.

Note that it seems this bug is already nearly fixed. Into file facture.class.php, we have line 3909 of current develop branch
// POS or by external module, take lowest buying price
if (!empty($this->fk_product) && empty($this->fk_fournprice) && empty($this->pa_ht)) {
...

All we have to add now is to add a check in this if, to know if the margin setup and use the wap if option to use wap is set. And if option is off or if wap not define, use current code.

**Closed as completed** 2015-11-02 10:06 UTC
Labels: Priority 1 - High / Blocking, Bug
