### ISSUE TITLE
Create Purchase order from Selling order is using sell prices in Purchase order

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#29224] opened 2024-04-04 09:49 UTC
### Bug

When creating "Purchase order" from "Selling order" (a new function I haven't seen before) the purchase order is using the prices from the selling order, and must be adjusted manually. The Purchase prices should of course be used. Also the discount used in the Selling order is transferred to the Purchase order.

### Dolibarr Version

19.0.1

### Environment PHP

7.4

**Comment by JonBendtsen** [comment] 2024-04-05 16:00
seems to be a duplicate of #28962

**Closed as completed** 2024-04-18 00:50 UTC
Labels: Bug
