### ISSUE TITLE
Bug: Untranslated "LocalTax1IsUsed and LocalTax2IsUsed" in fourn/card.php?socid= 

### ISSUE THREAD

**Issue by braito4** [Dolibarr/dolibarr#2603] opened 2015-04-13 15:31 UTC
Version: 3.7

![screen shot 2015-04-13 at 17 27 08](https://cloud.githubusercontent.com/assets/1913498/7118968/e5ee0be6-e202-11e4-939a-99960a2293c1.png)

**Comment by marcosgdf** [comment] 2015-04-18 08:53
Duplicate of #2598

**Comment by simnandez** [comment] 2015-04-18 08:54
Same #2598

**Closed as completed by simnandez** 2015-04-18 08:54 UTC
