### ISSUE TITLE
Required field is not required with drop/down field

### ISSUE THREAD

**Issue by Max84** [Dolibarr/dolibarr#10601] opened 2019-02-14 09:44 UTC
# Bug
A required extrafield is not required for company

## Environment
- **Version**: 8.0.4

## Expected and actual behavior
Expected : if you edit a company with a required extrafield, you can't save it until you fill the field
Actual behavior : if you edit a company with a required extrafield, you *can* save it until you fill the field

## Steps to reproduce the behavior
 - add an extrafield (drop down field only) to societe, of course set it as required
 - edit a company
 - don't fill the required drop down field
 - save it
 - you'll be able to save without error (you should have an error).

Best regards,

**Comment by eldy** [comment] 2019-08-01 13:52
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by atm-maxime** [comment] 2019-11-30 15:20
Confirmed, can't reproduce in 8.0.7

**Closed as completed** 2019-11-30 15:20 UTC
Labels: Bug
