### ISSUE TITLE
Bug: Changing PDF document model margin makes Crabe model to overlap some elements in generated documents

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#6822] opened 2017-05-10 10:48 UTC
# Bug
Changing PDF document model margin makes Crabe model to overlap some elements in generated documents

* MAIN_PDF_MARGIN_LEFT = 15
* MAIN_PDF_MARGIN_RIGHT = 15
* MAIN_PDF_MARGIN_TOP = 10

Makes the following result:

![captura de pantalla 2017-05-10 a las 12 45 48](https://cloud.githubusercontent.com/assets/168744/25895136/f2585b9e-357e-11e7-83f9-078695e59510.png)

## Environment
- **Version**: 4.0.6

**Comment by simnandez** [comment] 2017-05-26 15:55
I think this is not a bug. If you change margins, you should also change the sizes of columns for adjust to new margins....

**Comment by simnandez** [comment] 2017-09-28 08:57
I close this issue, as it will not be implemented

**Closed as completed by simnandez** 2017-09-28 08:57 UTC
Labels: Won't be fixed/implemented
