### ISSUE TITLE
propal

### ISSUE THREAD

**Issue by 2dig4it** [Dolibarr/dolibarr#13000] opened 2020-02-02 16:35 UTC
# Background
Dolibarr 10.0.6 / stable release | --> seems to be still the case in "devel" git release? (I did only a quick check)

# Brief description
Example: I have a commercial proposal, project support is enabled. I can select one of the available projects. It is correctly saved for the proposal.
BUG/ISSUE: when afterwards modifying via "MODIFY" in the list I can not select anything else, only the original project or nothing. Permissions are correct. 

For me this is also in other modules an issue (i.e., I want to change an entry in the agenda). 

Source code link: [dolibarr/htdocs/comm/propal/card.php/](https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/comm/propal/card.php#L1990) 

#This is the current situation
In version 10.X (and also current devel branch in GIT): user can not select any other project, if no project is selected (i.e., accident) he/she can not change anything (only remove a project, by selecting NONE):

>... $formproject->select_projects($object->socid, $object->fk_project, 'projectid', $maxlength, 0, 1, 0, 1, 0, 0, '', 1); 

Shouldn't it be (or something similar): 
>... $formproject->select_projects( -1, ... 	

so a list of projects is returned, from which another project can be selected
> ... $formproject->select_projects(-1, $object->fk_project, 'projectid', $maxlength, 0, 1, 0, 1, 0, 0, '', 1); 

Issue is in source code:
![screenshot](https://user-images.githubusercontent.com/60577290/73611334-3b1dfa80-45e1-11ea-983f-5a3e31d378a6.JPG)

# What I really don't understand
In an online shared testing environment: 
* https://www.dolibarr.org/onlinedemo 
it is no issue ?!? 

In this installation: for an existing proposal the associated project can be modified - a list is returned from which another option can be selected. Do they have their own version of Dolibarr?

**Comment by eldy** [comment] 2020-02-03 01:07
Duplicate of #12974

**Closed as completed by eldy** 2020-02-03 01:07 UTC
Labels: Bug
