### ISSUE TITLE
Virtual stock problem on partial delivery

### ISSUE THREAD

**Issue by ukwn12** [Dolibarr/dolibarr#18634] opened 2021-09-06 21:30 UTC
# Bug
On a partial delivery of X products out of Y. virtual stock, which was equal to Y, is incremented by X while it should stay at Y. Physical stock is incremented by X which is correct.

## Environment
- **Version**: 14.0.1
- **OS**: Linux Mint 20.2 Virtualbox VM, UserAgent: Firefox 91.0
- **Web server**: Apache/2.4.41 (Ubuntu)
- **PHP**: 7.4.3
- **Database**: MariaDB 10.3.31
- **URL**: dolibarr/product/list.php

## Expected and actual behavior
- Expectations : correct virtual stock
- Actual : the virtual stock is doubled up

## Steps to reproduce the behavior
1) Create a supplier order with a product quantity=10 ==> Physical stock = 0, Virtual stock = 10 <== OK
2) Create a partial delivery of 5 items ==> Physical stock = 5, Virtual stock = 15 <== Problem here
3) Complete the delivery ==> Physical stock = 10, Virtual stock = 10 <== OK

## Potential solution ?
Potential solution seems available on Dolibarr FR forum (https://www.dolibarr.fr/forum/t/anomalie-dans-la-gestion-stock-virtuel/35965)

**Comment by PyroShape** [comment] 2021-10-11 13:28
Can't reproduce today on branch 14.0

**Comment by ukwn12** [comment] 2021-10-11 19:24
Just reproduced it on 14.0.2. Here below some snaps (sorry, in FR) :
1) Initial stock : physical stock = 0, virtual stock = 0
![01 (initial stock)](https://user-images.githubusercontent.com/90219017/136844570-4507622e-3142-4068-952c-aeb6c025a449.jpg)
2) Created a PO for 10 products : physical stock = 0, virtual stock = 10
![02 (stock after validated PO)](https://user-images.githubusercontent.com/90219017/136844591-7be78a56-0e40-481e-baee-5dafc212643d.jpg)
3) Created a partial delivery of 6 products : physical stock = 6, virtual stock = 16 (should be virtual stock = 10)
![03 (apres partial delivery 1)](https://user-images.githubusercontent.com/90219017/136844956-7bf0b606-63fa-4507-aa00-1ff4f237b703.jpg)
4) Created another partial delivery of the remaining 4 products : physical stock = 10, virtual stock = 20 (should still be virtual stock = 10)
![04 (apres partial delivery 2)](https://user-images.githubusercontent.com/90219017/136844967-d40d53f1-1916-4076-aa44-fc035b961065.jpg)
5) Mark the delivery as completed : physical stock = 10, virtual stock = 10 (all good here)
![05 (delivery completed)](https://user-images.githubusercontent.com/90219017/136844777-2bbed0f6-5a8d-4475-8281-24fb0271a4df.jpg)

**Comment by PyroShape** [comment] 2021-10-12 09:21
Could you show us what is your config of stock module please ?
In french "Règle de gestion des incrémentations de stock".

**Comment by ukwn12** [comment] 2021-10-12 18:32
Please find below the config (in FR). Also, the partial deliveries have been created using delivery module which is active.
![Config stock](https://user-images.githubusercontent.com/90219017/137009312-e3a46eac-b32a-4f58-bd52-d12eaae75481.jpg)

**Comment by PyroShape** [comment] 2021-10-14 06:47
Ok now I can reproduce it. It seems to come from the delivery module because if you use the tab delivery inside the supplier order to dispatch your products it works fine.
I will try to fix the issue with the delivery module.

**Comment by dolibarr95** [comment] 2022-01-05 15:56
Hello
Same problem for me. The virutal stock is always wrong in product stock card.

I've put the patch but always the bug "virtual stock is wrong and does not cout partial reception"

Tks for your help.

**Comment by ukwn12** [comment] 2022-01-22 14:14
Hi,

I've tried on Dolibarr 14.0.5 and it works like a charm, be it in the product list or in the product stock card.

Created a 20 products order
![1b](https://user-images.githubusercontent.com/90219017/150641856-c6d1695e-dccc-47ed-9ed2-0ed73a48be51.png)
Partial reception of 9
![2b](https://user-images.githubusercontent.com/90219017/150641857-5ce65b84-c936-4390-a403-599786eeb713.png)
Partial reception of 6
![3b](https://user-images.githubusercontent.com/90219017/150641858-caf9a6af-2bd3-4a72-812e-2002b4b81af5.png)
Completed reception
![4b](https://user-images.githubusercontent.com/90219017/150641859-fbe95fc9-f5c8-4281-9f71-810b80437d60.png)

**Comment by pcbleu** [comment] 2022-01-26 07:54
Hey

I got same problems on version 14.0.5 - partial reception are not counted
in product/class/product.class.php, I found that when reception module is activated, $stock_reception_fournisseur will always be zero !!!
changing line 5284 as this is the answer
![image](https://user-images.githubusercontent.com/29097943/151123887-4024151e-21b2-45c8-b743-277186fe47a5.png)

Good continuation

**Comment by PyroShape** [comment] 2022-01-27 09:59
Hi,

That was this line that I change and merged for fixing the issue. If you remove it you will be in the same situation as september 2021.
The problem come from the delivery module that do not implement a method for virtual stock and try to manage it like in the reception tab that already exist in dolibarr.

**Closed as completed** 2022-02-04 14:41 UTC
Labels: Bug
