### ISSUE TITLE
facture.php return white page

### ISSUE THREAD

**Issue by br750** [Dolibarr/dolibarr#6840] opened 2017-05-11 15:18 UTC
# Instructions
a white page appear after invoice validation 

# Bug
a white page appear after invoice validation , i need to use browser back button to see new page correctly. the invoice is correctly recorded in database and correctly show in list etc ... it's just after validation. 

## Environment
- **Version**:5.0.0
- **OS**: [*Linux vps359380.ovh.net 3.2.0-4-amd64 #1 SMP Debian 3.2.82-1 x86_64*]
- **Web server**: [apache 2]
- **PHP**: [*	5.4.45-0+deb7u6*]
- **Database**: [*MySQL or MariaDB 5.5.53-0+deb7u1]
- **URL(s)**: [*/dolibarr/htdocs/compta/facture.php?id=1106#add*]

## Expected and actual behavior
when a click add "ajouter" in invoice creation , a white page appear. the invoice is correctly recorded in database. the message in FF debug is 
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

thank

**Comment by simnandez** [comment] 2017-05-26 15:45
It works for me in 5.0.3. if select a product/service and add it is added, if not, a message with code "ErrorChooseBetweenFreeAntryOrPredefinedProduct" appears

**Comment by simnandez** [comment] 2017-09-28 08:40
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:40 UTC
Labels: Works for me / Can't reproduce
