### ISSUE TITLE
BUG 3.8.3 I loose images when changing reference of a product

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#4652] opened 2016-02-18 15:53 UTC
if you change reference of a product which has images (and probably also added files), Images are no more diplayed on Product card  
On attached file tab I get 
filesize(): stat failed for /home/jean/projets/debug/interne/doli38/documents/produit/LP0012/00-0001-BW-M3.jpg 
Image is no more displayed
A file copy/move problem ?

New folder (with new reference) has bad rights for a folder dwr-wr-wr  instead of dwrxwrxwrx

**Comment by eldy** [comment] 2016-02-21 18:41
I can't reproduce with current version of branch 3.8 (3.8.4).

**Comment by simnandez** [comment] 2017-12-01 22:20
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Closed as completed by simnandez** 2017-12-01 22:20 UTC
