### ISSUE TITLE
Bug:  The requested URL /dolibarr/htdocs/accountancy/journal/variousjournal.php was not found on this server.

### ISSUE THREAD

**Issue by com4WEB** [Dolibarr/dolibarr#9981] opened 2018-11-09 08:31 UTC
# Bug

## Environment
- **Version**: 7.0.4
- **OS**: Linux
- **Web server**: Apache/2.4.25 (Debian)
- **PHP**: apache2handler 5.6.36-0+deb8u1
- **Database**: MySQL or MariaDB 5.5.5-10.1.26-MariaDB-0+deb9u1
- **URL**: /dolibarr/htdocs/accountancy/index.php?mainmenu=accountancy&leftmenu=

**Comment by com4WEB** [comment] 2018-11-09 08:33
I am at   dolibarr/htdocs/accountancy/index.php?mainmenu=accountancy&leftmenu=
and click on  'Assets Management'  (Link:  dolibarr/htdocs/accountancy/journal/variousjournal.php?mainmenu=accountancy&leftmenu=accountancy_journal&id_journal=7 )

**Comment by aspangaro** [comment] 2018-11-11 10:38
Hi,

It's not a bug. This page don't exist. Please move to dolibarr v8.0.x or modify your constant MAIN_FEATURES_LEVEL to level 0.

**Comment by atm-maxime** [comment] 2019-05-18 13:21
No news, I close the issue

**Closed as completed by atm-maxime** 2019-05-18 13:21 UTC
