### ISSUE TITLE
Dolibarr 12.0.0 Final Release - Hide buttons for non-admin

### ISSUE THREAD

**Issue by truefriend-cz** [Dolibarr/dolibarr#14113] opened 2020-06-24 03:03 UTC
## Bug
Function "Hide buttons for non-admin" is not changed after switched (bug is: icons is show always (for others restricted users)).

## Environment
- **Version**: Dolibarr 12.0.0 Final Release - (downloaded from sourceforge)

**Comment by eldy** [comment] 2020-06-26 18:02
I can't reproduce.
Can you provide a screenshot with example of menu entries that is still greyed once the option is set.

**Comment by truefriend-cz** [comment] 2020-06-26 22:47
## Steps to reproduce the behavior
1. Login Dolibarr as SuperAdmin
2. I going to Setup -> Display and item "Hide buttons for non-admin users for unauthorized actions instead of showing greyed disabled buttons" and switched to "Yes".
3. I Create new User (Users & Groups -> New user) with Last name, login name (testuser) and password, it's all.
4. I Create group (Users & Groups -> New group) with name "testgroup".
5. I going to List users and open user "testuser" and select from list (List of groups for this user -> testgroup) and click button "Add".

All permissions of user and group is in default settings.

3. Logout SuperAdmin and loged as testuser.
4. All icons on top toolbar is showed as grayed. And icon Home and Tools is showed normally.

I want hide grayed icons definitely.
![SuperAdmin2](https://user-images.githubusercontent.com/7845691/85906957-3a943380-b810-11ea-8d1f-e8d153b274c7.png)

![User2](https://user-images.githubusercontent.com/7845691/85906960-3d8f2400-b810-11ea-9571-8c0a8cef7fdf.png)

If you are interested, I can send you a backup of Dolibarr fro your testing. The problem also affects the clean installation of Dolibarr after restoring from backup. Neither the operating system nor the PHP version affects this. There is a problem with any supported OS and version of PHP.

**Comment by atm-maxime** [comment] 2020-06-27 06:50
Hi !
Thanks for these detail. So it's not an issue, because the option you're mentioning is just about action buttons. There's a similar option regarding the menus. Go to setup > menu and find the tab where the option can be set.
Close the issue if that's ok for you.

**Comment by truefriend-cz** [comment] 2020-06-27 10:50
@atm-maxime Step 2. from start thread is not for this?

... Setup -> Display and item "Hide buttons for non-admin users for unauthorized actions instead of showing greyed disabled buttons" and switched to "Yes".

**Comment by atm-maxime** [comment] 2020-06-27 18:50
The option you're talking about is to hide action buttons. To hide unauthorized menus, it's in setup / menus.

**Comment by truefriend-cz** [comment] 2020-06-28 06:33
@atm-maxime than you very much! It is solution! Sorry it's my wrong.

And @eldy do you can please reopen my other ticket?..: https://github.com/Dolibarr/dolibarr/issues/14112

**Comment by atm-maxime** [comment] 2020-06-28 08:16
No problem. You can close / reopen your issues yourself, so close this one and reopen the other.

**Closed as completed** 2020-06-28 14:00 UTC
Labels: Works for me / Can't reproduce, Bug

**Comment by truefriend-cz** [comment] 2020-06-28 14:02
@atm-maxime The problem is that if I didn't close the ticket, I can't even reopen it but just comment.
