### ISSUE TITLE
Error in migration script from 19 to 20 on adding constraint

### ISSUE THREAD

**Issue by ofaurax** [Dolibarr/dolibarr#32127] opened 2024-11-28 10:18 UTC
### Bug

While migration from 16 to 20, I encountered a bug in migration from 19 to 20.0.2:
```
Choose migration script	19.0.0-20.0.0.sql
Error DB_ERROR_42830 (Req 221): ALTER TABLE llx_societe_commerciaux ADD CONSTRAINT fk_societe_commerciaux_fk_c_type_contact_code FOREIGN KEY (fk_c_type_contact_code) REFERENCES llx_c_type_contact(code);
ERROR: 42830: there is no unique constraint matching given keys for referenced table "llx_c_type_contact" LOCATION: transformFkeyCheckAttrs, tablecmds.c:6544
```

### Dolibarr Version

19.0

### Environment PHP

8.0

### Environment Database

postgresql

### Steps to reproduce the behavior and expected behavior

Migrate from 19 to 20 ?

### Attached files

![Screenshot 2024-11-28 at 11-16-10 Dolibarr install or upgrade](https://github.com/user-attachments/assets/952b462c-41ec-4d98-aa83-0c82cb4e2513)

**Comment by sonikf** [comment] 2024-11-28 10:27
Hi @ofaurax
Please search before opening a bug and close this.
Duplicate of https://github.com/Dolibarr/dolibarr/issues/30995

**Closed as completed** 2024-11-28 11:24 UTC
Labels: Bug
