### ISSUE TITLE
V14.x : Cannot add a combination of product/service

### ISSUE THREAD

**Issue by ludovicandrieux** [Dolibarr/dolibarr#19357] opened 2021-11-11 17:48 UTC
# Bug
Cannot add a combination in tab "variants" of one product or one service

## Environment
- **Version**: 14.0.3
- **OS**: Debian 10.10
- **Web server**: nginx 1.21.3
- **PHP**: 7.3.29
- **Database**: PostgreSQL 11.13
- **URL(s)**: /variants/combinations.php?id=18&action=add

## Expected and actual behavior
- **Expected**: When an user select an attribute of variant the second list with values appears to select one.
- **Actual**: The list of values is always empty and there is a JS error

## Steps to reproduce the behavior
- Create a variant
- Add a value to this variant
- Create a product or service
- Go to tab 'variants' of this product or service
- Click on button "add combination"
- Choose an attribute
- Try to choose a value => List is empty & an error JS is visible in chrome tools

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![image](https://user-images.githubusercontent.com/11213740/141344704-cbf3702f-fd0f-44f4-b80d-11dc254c9285.png)

**Comment by N3miroff** [comment] 2021-11-22 14:07
Hello,
I do confirm exactly the same problem with 14.03 and 14.04 Dolibarr versions.

**Comment by daxitsolutions** [comment] 2021-12-02 19:49
This issue is produce an a 14.0.3 instance with Postgres database.
![variant_postgres](https://user-images.githubusercontent.com/26635105/144492283-75a3b895-d2a4-448d-90e0-40480187ea11.png)

When trying the same operation with an instance 14.0.3 with MySql database, the issue is significantly different 
Value of a variant can be selected BUT when trying to save the variant an error occurs 
"Field 'rowid' doesn't have a default value"

![variant_2](https://user-images.githubusercontent.com/26635105/144492691-b754442c-0d48-4655-9a06-98f0397a8b47.png)

**Comment by daxitsolutions** [comment] 2021-12-06 22:25
Tested with a version 13.0.2, same behaviour on Postgres but working with a MySql instance

**Comment by daxitsolutions** [comment] 2021-12-14 21:08
@ksar-ksar & @eldy FYI : this is a major regression

**Comment by Extarys** [comment] 2022-10-06 17:59
This is still happening with Dolibarr v16.0.0. Backend is Postgres.
I've added a test variant with some values but I cannot add them to the product. The Value field is empty and I also get 
```
Uncaught SyntaxError: expected expression, got ';'
```

![image](https://user-images.githubusercontent.com/11581433/194386002-f3cdec46-1f5f-4f9b-b476-210f6565af96.png)

**Comment by ksar-ksar** [comment] 2022-10-06 19:21
Hello,

We would need the dolibarr.log to progress, because in my tests instances with MYSQL it's working : 
V16 ; 
![image](https://user-images.githubusercontent.com/35605507/194400138-dc3d5e8a-0207-4fef-94f3-5eaf1e53fa6e.png)
![image](https://user-images.githubusercontent.com/35605507/194400196-f4e657c8-b39a-4025-8397-b9a70ed3d2fa.png)

V15.0.3 : 
![image](https://user-images.githubusercontent.com/35605507/194400336-0a0c623c-a38a-415b-bab8-36c02313ee4e.png)
![image](https://user-images.githubusercontent.com/35605507/194400384-e351671f-3bbe-4096-8773-334f729d70da.png)

V14.0.5 : 
![image](https://user-images.githubusercontent.com/35605507/194400560-a1ff38da-39eb-4c3f-940c-1b5ad7e8fa69.png)
![image](https://user-images.githubusercontent.com/35605507/194400608-f93a4322-caff-49aa-91e2-5780af6ef0cf.png)

**Comment by Extarys** [comment] 2022-10-06 22:49
Is there a way to see the logs inside Dolibarr? I will be happy to provide logs if I can find the file :smile: 

I'm using [this docker image](https://hub.docker.com/r/upshift/dolibarr) and the `dolibarr.log` file should be in `/var/www/documents` if I understand the file structure correctly, but there is no log file (all permissions seems ok)

![image](https://user-images.githubusercontent.com/11581433/194432440-374033f0-e48a-4705-a71d-a75c15056dfc.png)

**Comment by daxitsolutions** [comment] 2022-10-07 06:28
@Extarys 
https://XXXXX/htdocs/admin/syslog.php
![Configuration_du_module_Journaux_et_traces](https://user-images.githubusercontent.com/26635105/194482049-f9646acf-703a-4ede-8e2d-eb756e3851ce.jpg)

**Comment by hregis** [comment] 2022-10-07 06:56
@ludovicandrieux @Extarys @daxitsolutions @ksar-ksar 

Fixed with this PR https://github.com/Dolibarr/dolibarr/pull/22518

**Closed as completed** 2022-10-18 08:55 UTC
Labels: Bug
