### ISSUE TITLE
salaries/write permission not available.

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#5532] opened 2016-07-23 16:02 UTC
# Bug

Impossible to add salary payments because the right was not available in the  llx_rights_def
## Environment
- **Version**: 3.9.3 (and earlier)
## Expected and actual behavior

It should be possible to add new salary payments and to do so it must be possible to enable the right for a user.
## Steps to reproduce the behavior

I have been using Dolibarr since a long time and upgraded it several times already.  It may be that the upgrade is not functionnal.
I have disabled and enabled the salaries module, but the rights were not updated
## Suggested implementation

I have added "Create/modify salaries    salaries    1   write    NULL   w" directly to the  llx_rights_def table and after that the functionnality was available.

To fix this, the rights defined in the tables should be checked when enabling the module (for example) and be (re)created as needed.

**Comment by aspangaro** [comment] 2016-07-25 04:21
Sorry, I can't reproduce in 4.0rc clearly installed

**Comment by eldy** [comment] 2016-07-27 16:53
@mdeweerd Can you disable an enable back the module salaries ?

**Comment by mdeweerd** [comment] 2016-07-27 16:56
I did disable and enable back the module multiple times without success.
I had to manually add the line to the database.

Possibly to reproduce the problem one should remove the right from the database and check if disable/enable works.  In my case when it was not in the database, the disable/enable did not work.

**Comment by eldy** [comment] 2016-07-29 14:37
You probably have already another line with id 512 into table llx_rights_def so when enabling module, the insert of the line fails. Can you check this ?

**Comment by mdeweerd** [comment] 2016-07-29 15:05
Yes, indeed.

It reads this:
id - libelle - module - entity - perms - type - bydefault
512 - Supprimer les documents clients   - document -    1   - supprimer - NULL  - d - 0

**Comment by eldy** [comment] 2016-07-29 15:31
Do you have an external module called "document" installed ? If not this line is probably a result of very old version. You should remove the line.

**Comment by mdeweerd** [comment] 2016-07-29 16:19
In my "dolibarrdocs' directory where I have the 'install.lock' there is a directory dating from May 29 2013 called 'document' - I suppose that this is related.

I'll remove all references to 'document' in the rights table.  Do consider this kind of issue more generally though (possibly checking that the right in the database is the same as the one being added and notify if there is an issue).

**Comment by mdeweerd** [comment] 2016-07-29 16:20
I have these entries for the module document:
511 Lire les documents  document    1   lire    NULL    r   0
512 Supprimer les documents clients document    1   supprimer   NULL    d   0
1511    Lire les documents  document    1   lire    NULL    r   0
1512    Supprimer les documents clients document    1   supprimer   NULL    d   0

**Comment by simnandez** [comment] 2017-09-28 08:13
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:13 UTC
Labels: Works for me / Can't reproduce
