### ISSUE TITLE
Bug : update error on a discount on a line

### ISSUE THREAD

**Issue by philazerty** [Dolibarr/dolibarr#5197] opened 2016-05-12 12:04 UTC
# Bug

When correcting a discount on a validated line, the calculation is reversed.
Example: 110 - 10% give 122.22 and the final price is still 110
## Environment
- **Version**: 3.8.4
  [_Files_]

![erreur_sur_remise](https://cloud.githubusercontent.com/assets/3629675/15213925/5c6a5800-184a-11e6-81d3-5e7b54b57ce1.png)

**Comment by marcosgdf** [comment] 2016-05-12 14:03
Of which object? invoice, customer order…

**Comment by philazerty** [comment] 2016-05-12 14:10
Sorry, 
all customer documents.
proposal, order and invoice

**Comment by BebZ** [comment] 2016-05-12 15:21
3.8.3 version also.
Ouh yeah, very embarassing ;) i always read and remember the price without discount before modifying it, if for example i want to change the discount... i have to re encode twice the price, or remove the discount, to display an already discounted base price.

**Comment by philippe-opendsi** [comment] 2016-05-23 12:47
Hello
Same issue for me on 3.8.4. I didn't reproduce it on a clean install... 
I made some debug and the wrong value is returned (for me) by 
`$pu_ht = GETPOST('price_ht');`
in /comm/propal.php line 953
There's something which calculate the pu_ht from the total price using the discount... Didn't find where...

**Comment by altairis-tof** [comment] 2016-05-23 13:07
corrected here : https://github.com/Dolibarr/dolibarr/pull/4908

**Comment by philippe-opendsi** [comment] 2016-05-23 14:34
@altatof Many thanks. 
In objectline_edit.tpl.php in 3.8 branche all is commented with a note : 

```
        /* Add rules to reset price_ht from margin info */
        <?php
        if (! empty($conf->global->DISPLAY_MARGIN_RATES) && !empty($conf->global->MARGIN_RESET_HT_FROM_MARGIN_FIELD))
        {
        ?>
            /* Disabled. We must be able to click on button 'cancel'. Check must be done only on button 'save'.
            $("input[name='np_marginRate']:first").blur(function(e) {
                return checkEditLine(e, "np_marginRate");
            });*/
        <?php
        }
        if (! empty($conf->global->DISPLAY_MARK_RATES) && !empty($conf->global->MARGIN_RESET_HT_FROM_MARGIN_FIELD))
        {
        ?>
            /* Disabled. We must be able to click on button 'cancel'. Check must be done only on button 'save'.
            $("input[name='np_markRate']:first").blur(function(e) {
                return checkEditLine(e, "np_markRate");
            });*/
        <?php
        }
```

Seems to be different for your fix. Witch is right ?

I made some test with the version of objectline_edit.tpl.php from 3.8 repository, seems to work. I think it has been change next the release of 3.8.4.

**Comment by simnandez** [comment] 2017-12-01 22:33
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Closed as completed by simnandez** 2017-12-01 22:33 UTC
