### ISSUE TITLE
When an OF is returned to draft and modified, the quantities produced/consumed shouldn't be returned to 0

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#17692] opened 2021-05-20 17:09 UTC
# Bug
When a Fabrication Order is returned to draft, then modified (I've modified only the 'Libellé' of the OF), the quantities produced and consumed are returned to 0.

## Environment
- **Version**: 13.0.0
- **OS**: Linux dolionline 5.4.106-1-pve #1 SMP PVE 5.4.106-1 (Fri, 19 Mar 2021 11:08:47 +0100) x86_64
- **Web server**: Apache
- **PHP**: 7.0.33-0+deb9u10
- **Database**: MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0+deb9u2
- **URL(s)**: /mrp/mo_card.php?id=1&save_lastsearch_values=1

## Expected and actual behaviour
As the quantities haven't been changed, as this OF has been already processed, the production reported in this page shouldn't be 0.

## Steps to reproduce the behaviour
Open an used OF, return it to draft, then modify its 'Libellé'.

## [Attached files]
![image](https://user-images.githubusercontent.com/3815422/119020548-0802a480-b9a7-11eb-9d8e-6407ecace002.png)

**Comment by syrinx75** [comment] 2022-05-23 10:25
Still not OK in Doli 15.

**Comment by IC-Ilies** [comment] 2022-11-25 23:35
Hello, can't reproduce this bug in both versions, after Fabrication Order is set to draft the quantity consumed remains the same. (Tried in 15.0.3)

**Comment by syrinx75** [comment] 2022-12-05 19:27
> Hello, can't reproduce this bug in both versions, after Fabrication Order is set to draft the quantity consumed remains the same. (Tried in 15.0.3)

Probably because you didn't modify the 'libellé" of this OF. I just tested it with the version 15.0.3: modify the "libellé", the quantity produced went back to 0.

**Comment by ksar-ksar** [comment] 2023-10-18 18:08
Hello,

Is it still the case in V18 ?

**Comment by ksar-ksar** [comment] 2023-11-14 21:00
Hello,

I'm closing the issue for now, if needed, we can re-open it

**Closed as completed by ksar-ksar** 2023-11-14 21:00 UTC
Labels: Works for me / Can't reproduce, Bug
