### ISSUE TITLE
BUG : Dropdown of supplier prices no select possible

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#4516] opened 2016-01-28 11:25 UTC
![image](https://cloud.githubusercontent.com/assets/3694135/12643069/2c22c2c8-c5ba-11e5-91d0-e7eee2aa1489.png)

It is just simply not possible to select the correct supplier price... it selects the last entry in DB, not calculating unitprice... I am on demo.dolibarr.org, feel free to test more...

http://demo.dolibarr.org/commande/card.php?id=35&action=editline&lineid=46#line_46

http://demo.dolibarr.org/product/fournisseurs.php?id=20

@eldy 

This supplier price dropdown selection appears in replenishment : 
http://demo.dolibarr.org/product/stock/replenish.php

![image](https://cloud.githubusercontent.com/assets/3694135/12643403/39477226-c5bc-11e5-9104-300259a3c30b.png)

It would be nice to re-appear on proposals, orders, invoices... don't you think ?

**Comment by BebZ** [comment] 2016-01-28 11:30
On demo there is no margin module or i dont have user rights, so I can't create the bug report for margin modifications related to prices input...

**Comment by Gilles-Lengy** [comment] 2016-02-01 13:41
I'll try to fix that !

**Comment by Gilles-Lengy** [comment] 2016-02-02 14:09
![dolibarr-yadlapomme-3-9-0-beta-custumer-order-160202](https://cloud.githubusercontent.com/assets/15241447/12751635/766e35bc-c9be-11e5-9c6b-061f6988d1da.png)

It seems ok on the version 3.9.0 beta I download yesterday and installed on our server this morning...

May be the demo version of dolibarr is not up to date....

**Comment by eldy** [comment] 2016-02-02 23:30
Seems to be fixedfixed with last version

**Comment by BebZ** [comment] 2016-02-02 23:32
And what if you try to update price on the line when validated. Please look at my screenshots

**Comment by eldy** [comment] 2016-02-02 23:33
Seems ok to with last version

**Comment by BebZ** [comment] 2016-02-02 23:33
I'll try last version.

**Comment by BebZ** [comment] 2016-02-03 10:12
![image](https://cloud.githubusercontent.com/assets/3694135/12779170/dc21bc78-ca66-11e5-9b1d-26f53a640551.png)
 you can also display dropdown box on the line of the product ? 
For me this box disappears on 3.8.2
can you confirm this bug will be backported ?

**Comment by simnandez** [comment] 2017-09-28 08:04
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:05 UTC
Labels: Works for me / Can't reproduce

**Comment by BebZ** [comment] 2017-09-30 13:21
Come on guys send me a screenshot where you have a dropdown of product price fourisseur after adding a line on a propal, order or invoice, you will see that when you want to edit the line it doesn't propose it ! 
see my screenshots you have to add the line and the open to edit and dropdwon selector of supplier price is not here, tested and missing on 6.0 beta as well
