### ISSUE TITLE
Bug:  __REFCLIENT__ not working in supplier order email template

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#7036] opened 2017-06-19 11:14 UTC
# Bug
 __REFCLIENT__ not being substituted or shown in the e-mail (just shows blank space) when sending supplier order.

## Environment
- **Version**: 5.0.3

**Comment by marcosgdf** [comment] 2017-06-19 15:57
That is because there is no customer, only a supplier. You should use `__REFSUPPLIER__`

**Comment by aljawaid** [comment] 2017-06-20 10:24
![image](https://user-images.githubusercontent.com/10233708/27328700-eeae138e-55aa-11e7-9dbb-73ddf0552837.png)

I tried `__REFSUPPLIER__` but it does not work.  It is not shown in the available substitutes either.

**Comment by marcosgdf** [comment] 2017-07-22 10:39
You should not trust those hints, `__REFSUPPLIER__` should work. Where are you testing this template?

**Comment by simnandez** [comment] 2017-09-28 08:42
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:42 UTC
Labels: Works for me / Can't reproduce
