### ISSUE TITLE
Bug: Bouton "déconnexion"

### ISSUE THREAD

**Issue by optistea** [Dolibarr/dolibarr#14297] opened 2020-07-27 08:40 UTC
Bonjour,

je viens de télécharger la nouvelle version 12.0 de Dolibarr. Le bouton déconnexion a disparu lorsque le thème d'affichage est md. 

# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 12.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.4.8
- **Database**: MySQL or MariaDB 10.3.23-MariaDB
- **URL(s)**: /finance/index.php?mainmenu=home

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by ksar-ksar** [comment] 2020-07-29 10:20
Hi,

Could you please write in english ?
Also could you search if bug exist before creating a new one ?

https://github.com/Dolibarr/dolibarr/issues/14076

**Comment by eldy** [comment] 2020-07-29 10:27
Duplicate of #14076

**Closed as completed by eldy** 2020-07-29 10:27 UTC
Labels: Bug
