### ISSUE TITLE
Problem with stock in 3.7 (check in 3.8, 3.9 also)

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#4358] opened 2016-01-08 08:35 UTC
Users posted an issue on French Forum for a stock issue after migrating Dolibarr 3.7.1 to 3.7.2
May be we should check this point http://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/54624-probleme-stock-insuffisant-pour-livraison

**Comment by eldy** [comment] 2016-01-08 14:28
Can't reproduce. Seems to come from an old bug.
Note that by calling page   /install/repair.php
there is a command that fix this automatically. This fix was introduced the 2012-10-17 so i suppose the bug was in a version before 2012-10-17 and is now fixed

**Closed as completed** 2016-01-08 14:29 UTC
