### ISSUE TITLE
Bug: Cannot open linked files from the "Event card" tab in the agenda

### ISSUE THREAD

**Issue by Xebax** [Dolibarr/dolibarr#5881] opened 2016-10-16 10:17 UTC
# Bug

In an event in the agenda, the linked files cannot be opened from the "Event card" tab while they can be opened from the "Linked files" tab (the same file can be opened from one tab but not from the other one).
## Environment
- **Version**: 4.0.0
- **URL(s)**: /comm/action/card.php?id=xxx

**Comment by eldy** [comment] 2016-11-03 09:30
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by eldy** [comment] 2016-12-10 11:21
It seems this PR was set with "Discussion" or "PR to fix" tag, but no answer nor correction was provided since a long time. So request is automatically closed.
Please reopened and add a comment if you think this is an error.

**Closed as completed by eldy** 2016-12-10 11:21 UTC

**Comment by ryecoder** [comment] 2017-08-25 07:01
Hi I am encountering this error
