### ISSUE TITLE
Language issue email for sending propale

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#9763] opened 2018-10-16 10:11 UTC
# Bug
Standard email in other.lang for sending a propal to customer has a __PREF__ tag instead of __REF__ so substitution does not work

## Environment
- **Version**: 7.0
- **OS**: all
- **Web server**: all
- **PHP**: all
- **Database**: all
- **URL(s)**: all

## Expected and actual behavior
All language other.lang files in v 7.0 affected
in dolibarr 8.0 only es_ES/other.lang is affected

## Steps to reproduce the behavior
just open the send email form on a proposal

**Comment by atm-maxime** [comment] 2018-10-27 09:04
It's not a bug, it's a translation issue as it's in .langs files...
I saw that in 7.0 about 40 other.langs file still have __PREF__ instead of __REF__. But it must be fixed in transifex and as you say, it has been fixed in 8.0...

**Closed as completed by atm-maxime** 2018-10-27 09:04 UTC
