### ISSUE TITLE
Bug: Price not displayed in the Service list

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#31302] opened 2024-10-07 13:30 UTC
### Bug

version 20.0.0

Hello,
I imported a service like this (you can also create it).
`BanqueFraisCC280,Frais de tenue de compte courant Ma Banque,1,0,1,Frais de tenue de compte courant prix standard.,,customs code,FR,,,,62704,,,,,,kg,,m,,m,,m,,m2,,m3,,,2.8,2.8,2.8,2.8,HT,0,2024-06-09,`

When I display the price of this service I see the sale's price. All the prices are set correctly
![image](https://github.com/user-attachments/assets/41d4e23d-45a9-4733-b669-7cdf56ab6988)

But when I list the services the price is not displayed in the column
![image](https://github.com/user-attachments/assets/bb141615-291a-4d79-bd52-8e843383375f)

### Dolibarr Version

20.0.0

**Comment by IC-Mathieu** [comment] 2024-11-15 13:10
I checked in version 21.0.0-beta the problem is not present

**Closed as completed by IC-Mathieu** 2024-11-15 13:10 UTC
Labels: Bug, Event: Devcamp 2024 Nancy
