### ISSUE TITLE
V17.0.0 "Nested" Tags / Categories do not work correctly in Products and Projects.

### ISSUE THREAD

**Issue by JoAnMaFe** [Dolibarr/dolibarr#24188] opened 2023-03-11 10:00 UTC
### Bug

V17.0.0 After upgrading from v16.04 to v17 the "nested" Tags / Categories do not work properly. 
In previous versions, categories were nested in such a way that a product or a project could have the final characteristic applied to it and it would be assigned to all the previous ones.
Now this function has disappeared and each characteristic is unique, requiring more steps to filter products and projects. It also forces us to re-label all our products and re-categorise all our projects. 
It is such an important loss of features that forces us to rethink the use of dolibarr.
We go back to 16.04 version. 

### Environment Version

Versión actual 17.0.0

### Environment OS

W10 (Win64)

### Environment Web server

Apache/2.4.48 (Win64)

### Environment PHP

PHP/7.4.23

### Environment Database

MariaDB 5.5.5-10.10.2-MariaDB

### Environment URL(s)

localhost

### Expected and actual behavior

Tags and categories should again allow for nesting.

**Comment by priojk** [comment] 2023-04-01 08:13
Cannot reproduce your problem. If I define categories like Level1 >> Level2 >> Level3, it depends on the settings of the categories module, how the assignment to a product is handled.

If I selected to also include the higher level categories and I assign level3, the products get assigned categories Level1, Level1 >> Level2 and Level1 >> Level2 >> Level3.

Alternatively, the module can be configured to only assign the selected category and not the higher level ones.

**Comment by JoAnMaFe** [comment] 2023-05-07 17:27
new update on the problem V17.0.0 "Nested" Tags / Categories do not work correctly in Products and Projects. #24188
Gracias por seguir.

**Comment by AurelienBISOTTI** [comment] 2023-06-11 09:57
This issue is a duplicate of https://github.com/Dolibarr/dolibarr/issues/24707

**Closed as completed by AurelienBISOTTI** 2023-06-11 09:57 UTC
Labels: Bug, Event: DevCamp 2023 Bordeaux
