### ISSUE TITLE
Error updating from 3.8.0 to develop

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3940] opened 2015-11-07 15:40 UTC
Error DB_ERROR_1072: ALTER TABLE llx_budget_lines ADD UNIQUE INDEX uk_budget_lines (fk_budget, fk_project);
Key column 'fk_project' doesn't exist in table

Error DB_ERROR_1072: ALTER TABLE llx_budget_lines ADD INDEX idx_budget_lines (fk_project);
Key column 'fk_project' doesn't exist in table

**Comment by rdoursenaud** [comment] 2015-11-19 11:35
Can't reproduce…
Looks like it's been fixed by @eldy at fa8863d2eac449b2105419f610afae5c84ef9d66

**Closed as completed by rdoursenaud** 2015-11-19 11:35 UTC
Labels: Works for me / Can't reproduce
