### ISSUE TITLE
Extrafields facture fournisseur

### ISSUE THREAD

**Issue by dieperie** [Dolibarr/dolibarr#9641] opened 2018-09-30 09:28 UTC
# Bug
"Date" type extra field not working properly.

## Environment
- **Version**: 8.0.2

## Expected and actual behavior
When entering a date, the date is reset to 01/01/1970. This is since version 8.0.0

**Comment by atm-maxime** [comment] 2018-10-14 14:50
Seems to be fixed in 8.0.3, I can't reproduce. Please check when you can and tell us

**Comment by dieperie** [comment] 2018-10-15 14:15
8.0.3 is not yet released. Will try when published.

**Comment by atm-maxime** [comment] 2019-03-11 20:33
Fixed in #10803 but not in 8.0 branch yet

**Comment by atm-maxime** [comment] 2019-03-16 08:06
Coud you confirm it's fixed please ?

**Closed as completed** 2019-03-26 14:33 UTC
