### ISSUE TITLE
Problem with clients and companies photos

### ISSUE THREAD

**Issue by PDMeira** [Dolibarr/dolibarr#5063] opened 2016-04-21 19:58 UTC
# Bug

I'am loading user photos and company logos. Apparently no error, but images are not visible, just a question mark. When I click it says Fatal error: Call to a member function trans() on a non-object in /home/imperc/lat40research/site01/dolibarr/user/class/user.class.php on line 259
## Environment
- **Version**: [3.9.0]
- **OS**: [Linux]
- **Web server**: [Apache cpsrvd 11.54.0.21]
- **PHP**: [5.4]
- **Database**: [5.5.48-cll - MySQL Community Server (GPL) ]
- **URL(s)**: [/home/imperc/lat40research/site01/dolibarr/user/class/user.class.php]

**Comment by DHPM** [comment] 2016-04-26 16:09
Hello,
In /user/class/user.class.php comment line 259 
and in  viewimage.php, comment line:
if (! defined('NOREQUIRETRAN')) define('NOREQUIRETRAN','1');
becomes
//if (! defined('NOREQUIRETRAN')) define('NOREQUIRETRAN','1');

**Comment by PDMeira** [comment] 2016-04-26 18:51
Hello, thanks for your input. I changed both lines in class.php and viewimage.php. Whatever photo I load in user or company profile, it substitutes by a male or female avatar. Unfortunately still no photos or company logos.

**Comment by aconits** [comment] 2016-06-04 23:54
Hi,
I tried in 3.9.2 version and it's work.
Probably fixed since you submit this issue can you confirm by migrating on latest version of 3.9 Dolibarr ?

**Comment by simnandez** [comment] 2017-09-28 08:05
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:05 UTC
Labels: Works for me / Can't reproduce
