### ISSUE TITLE
[14.0.5] Uncaught mysqli_sql_exception: Table 'llx_onlinesignature' already exists

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#20156] opened 2022-02-23 08:07 UTC
### Bug

Can't do a fresh install

### Environment Version

14.0.5

### Environment OS

Windows 10

### Environment Web server

Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.1.2

### Environment PHP

8.1.2

### Environment Database

5.5.5-10.4.22-MariaDB

### Environment URL(s)

http://localhost/dolibarr/install/step2.php

### Expected and actual behavior

Actual behavior:
Fatal error: Uncaught mysqli_sql_exception: Table 'llx_onlinesignature' already exists in D:\xampp\htdocs\dolibarr\core\db\mysqli.class.php:285 Stack trace: #0 D:\xampp\htdocs\dolibarr\core\db\mysqli.class.php(285): mysqli->query('create table ll...') #1 D:\xampp\htdocs\dolibarr\install\step2.php(215): DoliDBMysqli->query('create table ll...', 0, 'dml') #2 {main} thrown in D:\xampp\htdocs\dolibarr\core\db\mysqli.class.php on line 285

Expected behavior:
Install without error

### Steps to reproduce the behavior

1. Create empty database (via HeidiSQL)
2. Fresh install

### Attached files

![2022-02-23 08_57_13-Dolibarr install or upgrade — LibreWolf](https://user-images.githubusercontent.com/17874713/155281197-38fd2da2-89f2-47d7-b196-639ba9df9c8e.png)

**Comment by cbrunet** [comment] 2022-02-24 02:52
Duplicate of #19974

**Closed as completed** 2022-02-28 10:57 UTC
Labels: Bug
