### ISSUE TITLE
Finding Products

### ISSUE THREAD

**Issue by jbarc128** [Dolibarr/dolibarr#18155] opened 2021-07-15 17:10 UTC
In some combobox, like BOM product adding or Stock Masive transfer, Dolibarr can't find items. It seems that it only finds the first 250 items if it start with the same character.

There is no issues with other combobox like List of BOM.

Environment
- Version: 13.0.4
- PHP: 7.4.20
- Database: mysql 8.0.25

Problem adding product on BOM

![image](https://user-images.githubusercontent.com/68402255/125826252-31bd3c75-c6ef-4fd9-862f-1eb096af8b5c.png)

Working on List of BOM

![image](https://user-images.githubusercontent.com/68402255/125826405-6641022b-0c3c-44c3-b59b-b6030b3899ee.png)

**Comment by erikvanberkum** [comment] 2021-07-15 23:55
jbarc128, I am having the same issue with the BOM list in 13.0.2, but I am able to get a list of exactly 1000 items. If you get a list of 250 items, there must be a setting different in your and my setup where it's getting the max 250 or 1000 items from.

**Comment by erikvanberkum** [comment] 2021-07-16 00:34
There is a limit in the following query that causes the issue

```
SELECT  p.rowid, p.ref, p.label, p.description, p.barcode, p.fk_country, p.fk_product_type, p.price, p.price_ttc, p.price_base_type, p.tva_tx, p.duration, p.fk_price_expression, IF(p.stock IS NULL,0,p.stock) AS stock, pl.label as label_translated FROM llx_product as p LEFT JOIN llx_product_lang as pl ON pl.fk_product = p.rowid AND pl.lang='en_US' WHERE p.entity IN (1) ORDER BY p.ref ASC LIMIT 1000 
```

**Comment by erikvanberkum** [comment] 2021-07-25 06:34
This issue still persists in version 14.0.0

**Comment by erikvanberkum** [comment] 2021-07-25 07:48
A temporary workaround to get a full list again is to modify /htdocs/bom/tpl/objectline_create.tpl.php

around line 101-106

change 2 times `$conf->product->limit_size` to `$conf->product->limit_size=0`


```
	if (!empty($conf->global->ENTREPOT_EXTRA_STATUS)) {
		// hide products in closed warehouse, but show products for internal transfer  after filtertype 
		$form->select_produits(GETPOST('idprod', 'int'), 'idprod', $filtertype, $conf->product->limit_size=0, $buyer->price_level, $statustoshow, 2, '', 1, array(), $buyer->id, '1', 0, 'maxwidth500', 0, 'warehouseopen,warehouseinternal', GETPOST('combinations', 'array'));
	} else {
		$form->select_produits(GETPOST('idprod', 'int'), 'idprod', $filtertype, $conf->product->limit_size=0, $buyer->price_level, $statustoshow, 2, '', 1, array(), $buyer->id, '1', 0, 'maxwidth500', 0, '', GETPOST('combinations', 'array'));
	}
```

**Comment by DaisEdel** [comment] 2021-07-25 15:38
> A temporary workaround to get a full list again is to modify /htdocs/bom/tpl/objectline_create.tpl.php
> 
> around line 101-106
> 
> change 2 times `$conf->product->limit_size` to `$conf->product->limit_size=0`
> 
> ```
> 	if (!empty($conf->global->ENTREPOT_EXTRA_STATUS)) {
> 		// hide products in closed warehouse, but show products for internal transfer  after filtertype 
> 		$form->select_produits(GETPOST('idprod', 'int'), 'idprod', $filtertype, $conf->product->limit_size=0, $buyer->price_level, $statustoshow, 2, '', 1, array(), $buyer->id, '1', 0, 'maxwidth500', 0, 'warehouseopen,warehouseinternal', GETPOST('combinations', 'array'));
> 	} else {
> 		$form->select_produits(GETPOST('idprod', 'int'), 'idprod', $filtertype, $conf->product->limit_size=0, $buyer->price_level, $statustoshow, 2, '', 1, array(), $buyer->id, '1', 0, 'maxwidth500', 0, '', GETPOST('combinations', 'array'));
> 	}
> ```

Thank you for your solution. I'm no specialist, just a user of Dolibarr. I tried the modification (also for proposals) but speed was a big issue. Any workaround to achieve an acceptable loading speed? (database size: 55'000 product items). Cheers.

**Comment by erikvanberkum** [comment] 2021-07-28 00:52
I think that the BOM field should be an obligatory field. 
Indeed, when you create a Manufacturing Order without BOM than products will be consumed but nothing is produced.

**Comment by cfoellmann** [comment] 2021-08-30 21:05
Have you Switched over to the Ajax search or is this maybe not implemented for the field you are talking about?

**Comment by erikvanberkum** [comment] 2021-09-03 01:40
Not a bug wrong setting in the product admin now its working:

![image](https://user-images.githubusercontent.com/7335299/131937601-9443dff4-5d97-49bb-8b96-da4bc9f63e5d.png)

**Comment by cfoellmann** [comment] 2021-09-03 06:35
@erikvanberkum please close the issue.

**Comment by erikvanberkum** [comment] 2021-09-03 09:28
@jbarc128 please close issue

**Comment by jbarc128** [comment] 2021-09-03 18:57
Thanks you :)

**Closed as completed** 2021-09-03 18:57 UTC
Labels: Bug
