### ISSUE TITLE
[Bug] Wrong owner on provisional propale

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#9802] opened 2018-10-18 06:58 UTC
# Bug
Provisional document (PROV217) has been generated with user rights instead of apache ones. Thus, updating the document is no more possible.
Deleting the document allow to go further.

## Environment
- **Version**: 7.0.2
- **OS**: Linux Mageia 6
- **Web server**: apache-2.4.27
- **PHP**: 5.6.38
- **Database**: mariadb
- **URL(s)**: http://localhost/dolibarr/htdocs/comm/propal/card.php?id=267#line_1036

## Expected and actual behavior
The PDF document should be renewed, and registered with apache owner. However, when editing a line (not the first one), the owner has become the user of the computer (client and server installed on the same machine).

## Steps to reproduce the behavior
Not surely reproducible.
Create a propale with some lines. Edit one of them. Get error "TCPDF Unable to create the document" (not sure of the exact message).

**Comment by ksar-ksar** [comment] 2018-10-18 12:30
This seems to be unlikely
If dolibarr create a file it will be create by php that runs from apache so impossible that php create a pdf owned by a user.
Excepte if you launch php by a contrab from the user.

**Comment by papoteur-mga** [comment] 2018-10-18 12:58
As you, I think that is incredible.
However that's TRUE.
I didn't nothing else than updating the lines of my propale at that moment.
The only thing that can be said is that the dolibarr directory is owned by the user.

**Comment by atm-maxime** [comment] 2018-10-27 08:35
This is not an issue regarding the software but your individual installation. Might be a copy/paste in the documents folder made manually. If your facing the trouble on only one proposal, it most likely is a manual error.

**Comment by papoteur-mga** [comment] 2018-10-27 08:51
Hi Maxime,
The document was already created, and I was editing several lines. First lines I edited was successful. Then the error occurred by editing another line. I wonder which kind of manual error it could be.

**Comment by atm-maxime** [comment] 2018-10-27 14:49
No clue, but as it's not reproducible I suggest you delete the document and regenerate it. I'll close this issue.

**Closed as completed** 2018-11-30 22:38 UTC
