### ISSUE TITLE
Bug: Customer invoices Fusion PDF feature does not merge abonement invoices

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5157] opened 2016-05-02 12:59 UTC
Version: 3.8.3

Reported by a dolibarr.es forum user http://www.dolibarr.es/foro/viewtopic.php?f=18&t=2692&p=9828#p9828

**Comment by eldy** [comment] 2016-06-03 23:54
Tested with 3.9 and can't reproduce the trouble.

**Comment by marcosgdf** [comment] 2016-07-08 09:56
Tested with 3.9 and **can** reproduce the problem. Please check again.

**Comment by simnandez** [comment] 2017-09-28 08:06
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:06 UTC
Labels: Works for me / Can't reproduce
