### ISSUE TITLE
Bug: error on customer invoice/facture

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#5060] opened 2016-04-21 07:23 UTC
# Environment
- **Version**: 3.9.0
- **OS**: Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.0.5
- **Database**: MySQL or MariaDB 5.5.47-0+deb7u1-log
- **URL**: /compta/facture.php?facid=244
# Report

on header of browser show this error:
Warning: Declaration of FactureRec::create($user, $facid) should be compatible with Facture::create($user, $notrigger = 0, $forceduedate = 0) in /homepages/39/d616817840/htdocs/erp/compta/facture/class/facture-rec.class.php on line 641

Warning: Declaration of FactureRec::addline($desc, $pu_ht, $qty, $txtva, $fk_product = 0, $remise_percent = 0, $price_base_type = 'HT', $info_bits = 0, $fk_remise_except = '', $pu_ttc = 0, $type = 0, $rang = -1, $special_code = 0, $label = '', $fk_unit = NULL) should be compatible with Facture::addline($desc, $pu_ht, $qty, $txtva, $txlocaltax1 = 0, $txlocaltax2 = 0, $fk_product = 0, $remise_percent = 0, $date_start = '', $date_end = '', $ventil = 0, $info_bits = 0, $fk_remise_except = '', $price_base_type = 'HT', $pu_ttc = 0, $type = self::TYPE_STANDARD, $rang = -1, $special_code = 0, $origin = '', $origin_id = 0, $fk_parent_line = 0, $fk_fournprice = NULL, $pa_ht = 0, $label = '', $array_options = 0, $situation_percent = 100, $fk_prev_id = '', $fk_unit = NULL) in /homepages/39/d616817840/htdocs/erp/compta/facture/class/facture-rec.class.php on line 641

Warning: Cannot modify header information - headers already sent by (output started at /homepages/39/d616817840/htdocs/erp/compta/facture/class/facture-rec.class.php:641) in /homepages/39/d616817840/htdocs/erp/main.inc.php on line 954

**Comment by centoasa** [comment] 2016-04-21 07:25
when try to send email with invoice, error:
Warning: Declaration of FactureRec::create($user, $facid) should be compatible with Facture::create($user, $notrigger = 0, $forceduedate = 0) in /homepages/39/d616817840/htdocs/erp/compta/facture/class/facture-rec.class.php on line 641

Warning: Declaration of FactureRec::addline($desc, $pu_ht, $qty, $txtva, $fk_product = 0, $remise_percent = 0, $price_base_type = 'HT', $info_bits = 0, $fk_remise_except = '', $pu_ttc = 0, $type = 0, $rang = -1, $special_code = 0, $label = '', $fk_unit = NULL) should be compatible with Facture::addline($desc, $pu_ht, $qty, $txtva, $txlocaltax1 = 0, $txlocaltax2 = 0, $fk_product = 0, $remise_percent = 0, $date_start = '', $date_end = '', $ventil = 0, $info_bits = 0, $fk_remise_except = '', $price_base_type = 'HT', $pu_ttc = 0, $type = self::TYPE_STANDARD, $rang = -1, $special_code = 0, $origin = '', $origin_id = 0, $fk_parent_line = 0, $fk_fournprice = NULL, $pa_ht = 0, $label = '', $array_options = 0, $situation_percent = 100, $fk_prev_id = '', $fk_unit = NULL) in /homepages/39/d616817840/htdocs/erp/compta/facture/class/facture-rec.class.php on line 641

Warning: Cannot modify header information - headers already sent by (output started at /homepages/39/d616817840/htdocs/erp/compta/facture/class/facture-rec.class.php:641) in /homepages/39/d616817840/htdocs/erp/core/actions_sendmails.inc.php on line 331

**Comment by aschio** [comment] 2016-06-04 00:01
Cannot reproduce in 4.0.0-beta

**Comment by simnandez** [comment] 2017-12-01 22:32
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Closed as completed by simnandez** 2017-12-01 22:32 UTC
