### ISSUE TITLE
PHP warnings during upgrade from 8.0.6 to 9.0.4

### ISSUE THREAD

**Issue by jpyrat** [Dolibarr/dolibarr#11488] opened 2019-07-11 14:49 UTC
# Bug
[*Short description*]

## Environment
- **Version**: 9.0.4
- **OS**: Debian 9
- **Web server**: Apache
- **PHP**: 7.0.33-0+deb9u3
- **Database**: MariaDB 5.5.5-10.1.38-MariaDB-0+deb9u1
- **URL(s)**: NA

## Expected and actual behavior
Expected : No PHP warnings

Actual behavior
```
PHP Notice:  Undefined offset: 1 in /var/www/htdocs/core/modules/modAgenda.class.php on line 421
PHP Stack trace:
PHP   1. {main}() /var/www/htdocs/install/upgrade2.php:0
PHP   2. migrate_reload_modules() /var/www/htdocs/install/upgrade2.php:482
PHP   3. modAgenda->__construct() /var/www/htdocs/install/upgrade2.php:4564
PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/htdocs/core/db/mysqli.class.php on line 401
PHP Stack trace:
PHP   1. {main}() /var/www/htdocs/install/upgrade2.php:0
PHP   2. migrate_delete_old_files() /var/www/htdocs/install/upgrade2.php:556
PHP   3. dol_delete_file() /var/www/htdocs/install/upgrade2.php:4481
PHP   4. EcmFiles->fetch() /var/www/htdocs/core/lib/files.lib.php:1208
PHP   5. DoliDBMysqli->escape() /var/www/htdocs/ecm/class/ecmfiles.class.php:356
PHP   6. mysqli->real_escape_string() /var/www/htdocs/core/db/mysqli.class.php:401
PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/htdocs/core/db/mysqli.class.php on line 401
PHP Stack trace:
PHP   1. {main}() /var/www/htdocs/install/upgrade2.php:0
PHP   2. migrate_delete_old_files() /var/www/htdocs/install/upgrade2.php:556
PHP   3. dol_delete_file() /var/www/htdocs/install/upgrade2.php:4481
PHP   4. EcmFiles->fetch() /var/www/htdocs/core/lib/files.lib.php:1208
PHP   5. DoliDBMysqli->escape() /var/www/htdocs/ecm/class/ecmfiles.class.php:356
PHP   6. mysqli->real_escape_string() /var/www/htdocs/core/db/mysqli.class.php:401
PHP Warning:  mysqli::query(): Couldn't fetch mysqli in /var/www/htdocs/core/db/mysqli.class.php on line 268
PHP Stack trace:
PHP   1. {main}() /var/www/htdocs/install/upgrade2.php:0
PHP   2. migrate_delete_old_files() /var/www/htdocs/install/upgrade2.php:556
PHP   3. dol_delete_file() /var/www/htdocs/install/upgrade2.php:4481
PHP   4. EcmFiles->fetch() /var/www/htdocs/core/lib/files.lib.php:1208
PHP   5. DoliDBMysqli->query() /var/www/htdocs/ecm/class/ecmfiles.class.php:384
PHP   6. mysqli->query() /var/www/htdocs/core/db/mysqli.class.php:268
PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/htdocs/core/db/mysqli.class.php on line 401
PHP Stack trace:
PHP   1. {main}() /var/www/htdocs/install/upgrade2.php:0
PHP   2. migrate_delete_old_files() /var/www/htdocs/install/upgrade2.php:556
PHP   3. dol_delete_file() /var/www/htdocs/install/upgrade2.php:4481
PHP   4. EcmFiles->fetch() /var/www/htdocs/core/lib/files.lib.php:1208
PHP   5. DoliDBMysqli->escape() /var/www/htdocs/ecm/class/ecmfiles.class.php:356
PHP   6. mysqli->real_escape_string() /var/www/htdocs/core/db/mysqli.class.php:401
PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/htdocs/core/db/mysqli.class.php on line 401
PHP Stack trace:
PHP   1. {main}() /var/www/htdocs/install/upgrade2.php:0
PHP   2. migrate_delete_old_files() /var/www/htdocs/install/upgrade2.php:556
PHP   3. dol_delete_file() /var/www/htdocs/install/upgrade2.php:4481
PHP   4. EcmFiles->fetch() /var/www/htdocs/core/lib/files.lib.php:1208
PHP   5. DoliDBMysqli->escape() /var/www/htdocs/ecm/class/ecmfiles.class.php:356
PHP   6. mysqli->real_escape_string() /var/www/htdocs/core/db/mysqli.class.php:401
PHP Warning:  mysqli::query(): Couldn't fetch mysqli in /var/www/htdocs/core/db/mysqli.class.php on line 268
PHP Stack trace:
PHP   1. {main}() /var/www/htdocs/install/upgrade2.php:0
PHP   2. migrate_delete_old_files() /var/www/htdocs/install/upgrade2.php:556
PHP   3. dol_delete_file() /var/www/htdocs/install/upgrade2.php:4481
PHP   4. EcmFiles->fetch() /var/www/htdocs/core/lib/files.lib.php:1208
PHP   5. DoliDBMysqli->query() /var/www/htdocs/ecm/class/ecmfiles.class.php:384
PHP   6. mysqli->query() /var/www/htdocs/core/db/mysqli.class.php:268

```

## Steps to reproduce the behavior
```
mv /var/www/htdocs/documents/install.lock /var/www/htdocs/documents/_install.lock
cd htdocs/install
php upgrade.php 8.0.0 9.0.0 > output.html
php upgrade2.php 8.0.0 9.0.0 > output2.html
php step5.php 8.0.0 9.0.0 > output3.html
mv /var/www/htdocs/documents/_install.lock /var/www/htdocs/documents/install.lock

```

**Comment by jpyrat** [comment] 2019-07-12 12:51
To solve this isue, I've restaured my backup of 8.0.6

**Comment by eldy** [comment] 2019-07-19 17:33
I think the warning occurs only when migration is done from command line.
They can be ignored.

**Comment by jpyrat** [comment] 2019-07-19 20:26
I've also tried the same migration with a local copy, and I've got the same PHP warnings...

So, it's not a command line problem.

**Comment by eldy** [comment] 2019-11-07 14:04
I can't reproduce. Do you still have trouble when migration to v10 ? Can you provide a screenshot ?

**Comment by simnandez** [comment] 2020-08-07 16:21
No user response and it is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Closed as completed by simnandez** 2020-08-07 16:21 UTC
Labels: Bug
