### ISSUE TITLE
Attached file not shown in mail event

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#11706] opened 2019-08-20 11:52 UTC
# Bug
Attachement is not shown in event view, while it is a mail event to show.

## Environment
- **Version**: 9.0.4 & 10.0.1
- **OS**: Ubuntu 18.04 LTS (latest stable Ubuntu 18.04)
- **Web server**: Apache2 (latest stable Ubuntu 18.04)
- **PHP**: 7.2 (latest stable Ubuntu 18.04)
- **Database**: MariaDB (latest stable Ubuntu 18.04)
- **URL(s)**: http://belgrand-01.service-informatique.bzh:9080/comm/action/document.php?id=481

## Expected and actual behavior
The mail event is not showing the attached file. Wile the mail is pretty good crafted WITH the attachement.

## Steps to reproduce the behavior
Send a mail to a customer, attach a file, upload the file, send the mail, and watch your event. Attached file is empty, while the file has been attached well.

## Use case
When you want to see if an email, told to be with attachement has been well crafted by the user. id est, not with the forgettable attachement.

**Comment by matDOTviguier** [comment] 2019-09-10 13:01
UP !
Joint document is well shown in description of the event, but cannot be shown in joint files of the event. It is probably a feature.

But, I wonder if we have to force to join a file in the customer view, or if a joint element of a mail sent to a customer has to be shown in customer view. ...

**Comment by atm-maxime** [comment] 2019-09-15 08:38
I think this is expected behavior. That's not because you send an email with attachments that you want these attachments automatically stored in Dolibarr.
When you send an invoice by email for example, the invoice PDF is already stored on the invoice card. If you send your invoice 3 times this will mean that the same PDF would be stored 4 times in Dolibarr...
This said you can change your issue to a feature request, an option to develop to have attachments stored on email send events.

**Comment by matDOTviguier** [comment] 2019-09-16 11:42
Yes, I think the main "problem", is that you can attach a file to an event.
When I saw the "mail sent" in the adhoc event, I realized that the object is not the mail sent, but the expedition of the email. Shall we attach the attachement to the expedition or let the mail be stored elsewhere ...

I do not understand the interest to store the body of the mail witouth the attachement. But, it's kind of a choice. Perhaps, a new feature like a boolean like "Do you want to join attached files in email to the client" and store the objects linked in the client db ? I do not know ...

**Comment by matDOTviguier** [comment] 2019-09-16 11:43
Let the community adress the feature request or let die this issue well ...

**Comment by dpriskorn** [comment] 2020-08-07 09:50
Won't fix. Closed.

**Closed as completed by dpriskorn** 2020-08-07 09:50 UTC
Labels: Won't be fixed/implemented
