### ISSUE TITLE
Ticket message notifications: Can send an email when a new message is added from public interface

### ISSUE THREAD

**Issue by Nicofol** [Dolibarr/dolibarr#12181] opened 2019-10-19 16:05 UTC
In Dolibarr 10.0.2, when an end user open a ticket in public interface, and then add a message in the ticket box, there's not any notification (mail?) to assigned agent regarding the new message.

**Comment by eldy** [comment] 2019-11-05 12:35
Can you try with 10.0.3 ?

**Comment by Nicofol** [comment] 2019-11-13 20:45
The same

**Comment by dseichter** [comment] 2019-12-11 18:55
the same in 10.0.4

**Comment by Nicofol** [comment] 2019-12-14 21:37
Is it possible to integrate the TicketSup Module available here? https://code.librethic.io/Dolibarr/modules
It's very nice, complete and ready....or there are some problems with copyright?

**Comment by scarcamo-eyg** [comment] 2020-01-22 12:44
The module ticketsup looks like was integrated or attached to the official dolibarr version, 
but with some different features, I've tried that feature you posted and it works.
I'm using 10.0.6 right now.

**Comment by gma69** [comment] 2020-01-23 12:54
the same in 10.0.6

**Comment by scarcamo-eyg** [comment] 2020-01-29 20:10
> The module ticketsup looks like was integrated or attached to the official dolibarr version,
> but with some different features, I've tried that feature you posted and it works.
> I'm using 10.0.6 right now.

I've rechecked that and I was wrong, in my production installation of Dolibarr is not working, Also I've did the same test on the Development Version (12.X.X) and it is working properly.

**Comment by scarcamo-eyg** [comment] 2020-01-31 15:31
I've studied that reading the wiki and documentation, Also I've tried different version, like, 10.0.6, 11 recently released (31-Jan-2020) and also de develop version number 12.
The email notification when creating, assignation, and messaging from backoffice it is working.
But when messaging from public notification is not. Looks like this is not a feature. Sadly I couldn't find any info of this trough the official documentation.
Regards.

**Comment by gma69** [comment] 2020-01-31 15:46
same problem/issues also for me, checked on these following versions/conf. 
V1) D = "original" 10.0.6
V2) D = 11 "updated" from 10.0.6
V3) D = 10.0.6 "updated" from 5.0.3 + multicompany
V4) D = 10.0.6 "updated" from 6.0.4 + multicompany

**Comment by scarcamo-eyg** [comment] 2020-01-31 15:47
Ok, as I said before, looks like the messaging with email notification from public interface looks like it is not a feature of Dolibarr.

**Comment by Nicofol** [comment] 2020-01-31 20:33
The TicketSup external module that I'm using in version 10.0.6 (https://code.librethic.io/Dolibarr/modules) is working very well from even from public interface. If you add a message in the public box, an email notification will be sent to the assign agent and a message notification will appear in the backend dashboard. Is it possible geat ideas from that 3part module and upgade the official ticket dolibarr module? I haven't tried in the 11 version at the moment but I think will be the same.

**Comment by scarcamo-eyg** [comment] 2020-01-31 20:37
oh, good to know that, hopefully they will consider the full features from external modules to get into the official version.
in the past, I had some integration issues with ticketsup and dolibarr core, so I waited to the official module.
Probably we could extract some lines of codes to add that feature to our installed version.
Regards.

**Comment by scarcamo-eyg** [comment] 2020-02-04 00:31
sadly I've updated to the official 11 version, and it is not working. :(

**Comment by Nicofol** [comment] 2020-02-06 21:06
Yes I confirm, with 11 version the problem remain...not any mail or notification are sent when a new message is added via public interface box. The feature should be very important for backend operators and assigned agents.

**Comment by philazerty** [comment] 2020-04-10 09:02
The problem persists in Dolibarr 11.0.3. If a user posts a message from the public interface, there is no email notification to ticket contacts. It's blocking

**Comment by Nicofol** [comment] 2020-04-13 19:26
Yes I confirm the problem. I'd like to ask to developers to implement pls as soon as possible an e-mail notification system from messages posted through the public interface. The module now is not very usable. Generally, all ticketing systems include this functionality. Thank you.

**Comment by eldy** [comment] 2020-04-14 19:26
What do you have in setup "Always disable emails when a ticket is created from public interface" into setup of module Ticket, in tab "Public interface" ? Is it on or off ?

**Comment by Nicofol** [comment] 2020-04-15 06:53
Off course, is always OFF. I've tried to switch ON, Save, Switch OFF again, but the problem remain. See attach.
![Annotazione 2020-04-15 085217](https://user-images.githubusercontent.com/56766857/79307091-a3009380-7ef6-11ea-8f9a-cdd70509a8cc.png)

**Comment by eldy** [comment] 2020-04-15 10:33
I can't reproduce. Did you set the email you want notification sent to into the tab "Settings" ?

**Comment by Nicofol** [comment] 2020-04-15 12:20
Yes I think so. I can share my test environment and you can check/change anything you prefere in order to find the problem/solution (changing the mail address to)... How can I send you the userid e pdw?

**Comment by philazerty** [comment] 2020-04-20 08:31
The problem is not with the creation of the ticket but when a customer adds a message from the public interface to a ticket opened.

**Comment by eldy** [comment] 2020-04-23 12:59
This feature can be implemented this way:
Add option for pubic interface "Send email(s) when a new message is added from public interface"
The email should be sent to 
- assigned people if ticket is already assigned
- to another parameter "Notifications email to (update)" to add if ticket not assigned

**Comment by wolflouis** [comment] 2020-04-26 09:18
I'd actually like to see fully customizable templates as I cant make these for the ticketing area.
It only allows me to change the start and the end of the email. I'd rather make my own template with use of tags. For:
-When a client submits a ticket, they get a confirmation email and the assignee
-When a reply is given an for any other status change

**Comment by wolflouis** [comment] 2020-04-26 09:21
I'd actually like to see fully customisable templates as I can't make these for the ticketing area in the email template section.
It only allows me to change the start and the end of the email (in the module settings). I'd rather make my own template with use of tags. For:
-When a client submits a ticket, they get a confirmation email and the assignee
-When a reply is given an for any other status change (like you can in TOPdesk for example)

**Comment by Nicofol** [comment] 2020-05-18 20:39
In any case should be important receive some notification when a customer add a new message in the public ticket box. Now, the assigend agent and/or the admin, don't know when a new msg has been added in the ticket public interface (no mail, no message notification, no alerts, etc.).

**Comment by Nicofol** [comment] 2020-07-11 20:32
Hello, any news pls about this feature request? tks in advance.

**Comment by philippe-opendsi** [comment] 2020-07-12 14:48
Hi 
This has been merged in develop branch. Will be available on next version of Dolibarr
Not sure it has been pushed in v12 before the release of this version.

**Comment by Nicofol** [comment] 2020-09-06 19:42
Hello, in Dolibarr 12.0.2 the solutions is still unavailable. Have you got any update pls?

**Comment by philippe-opendsi** [comment] 2020-09-07 12:49
Hi,
This feature has been merged in the develop branch. So will be available in v13.

**Comment by ksar-ksar** [comment] 2021-02-19 10:20
Hello,

Normally fixed in V13, can you confirm ?

**Comment by Nicofol** [comment] 2021-02-20 21:17
Yes, now with v13 it works.

**Closed as completed** 2021-02-20 21:19 UTC
Labels: Feature request
