### ISSUE TITLE
proposal convalid button not enalbled

### ISSUE THREAD

**Issue by mariamanc28** [Dolibarr/dolibarr#4336] opened 2016-01-05 15:22 UTC
hi, from 3.8.1 version i cannot reach to add proposal, i cannot press convalid(save) button because is enabled, and i don't think why, nothing message apper. that is image
![cattura](https://cloud.githubusercontent.com/assets/12257498/12118755/80f14e54-b3c8-11e5-82c7-44f788711318.JPG)

**Comment by marcosgdf** [comment] 2016-01-06 12:05
Can you please update to latest version 3.8.3 and try again?

**Comment by mariamanc28** [comment] 2016-01-07 09:12
ihave already updated to 3.8.3 version, and this apear again to this. Perhaps there are something that i not make good? i don't think, because i have created propal before passed to 3.8.2 version.

**Comment by mariamanc28** [comment] 2016-01-07 11:07
the problem is that href of button convalid, that is disabled is # not something like comm/propal.php?id=30&action=valid

**Comment by marcosgdf** [comment] 2016-01-09 12:17
I think this is a duplicate of bug #3538. Please try the trick I posted in that page and tell us if that works for you

**Closed as completed** 2017-12-01 22:06 UTC
