### ISSUE TITLE
Ticket permissions for different user assignment

### ISSUE THREAD

**Issue by Nicofol** [Dolibarr/dolibarr#12180] opened 2019-10-19 15:57 UTC
In Dolibarr 10.0.2 version, when you create a new internal user and add specific permissions for ticket view and manage, the user see all tickets of all users and not only the own specific.

**Comment by atm-maxime** [comment] 2019-10-22 13:30
I guess this is not a bug because there's no permission saying "view tickets assigned to user". The permissions are regarding all tickets. Only specific permission is to allow viewing tickets related to thirdparties the user is affected to. Please close if you're ok with this or add a feature request to ask for more rights.

**Closed as completed** 2019-10-22 16:50 UTC
Labels: Works for me / Can't reproduce, Bug
