### ISSUE TITLE
Bug: SQL error when creating a new customer order

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5201] opened 2016-05-13 09:04 UTC
# Bug

Version: 3.8.4

```
2016-05-13 09:03:03 ERR     192.168.42.1    DoliDBMysqli::query SQL Error query: SELECT SUM(rc.amount_ttc) as amount FROM llx_s
ociete_remise_except as rc WHERE (rc.fk_facture IS NULL AND rc.fk_facture_line IS NULL) AND rc.fk_soc =
2016-05-13 09:03:03 ERR     192.168.42.1    DoliDBMysqli::query SQL Error message: DB_ERROR_SYNTAX You have an error in your SQ
L syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
```

Page: http://dolibarr.local/commande/card.php?action=create&leftmenu=orders

**Comment by eldy** [comment] 2016-05-29 10:08
Can't reproduce. Does this opened any time ?
What is option to thirdparty module combo list (autocompletion on or full list) ?

**Comment by atm-maxime** [comment] 2016-06-17 13:20
@eldy 
Because of line 1437 : $absolute_discount=$soc->getAvailableDiscounts();
It's called and when clicking on "New Order" from the left menu, there's no socid, so $soc is not initialized. The function should test if a rowid of $soc is > 0 before trying to execute the SQL request.

**Comment by marcosgdf** [comment] 2016-06-17 14:34
I do not think the function should do so, I think there should not be a Societe call there if there is no a complete Societe object. But the function should not trigger a SQL error

**Comment by simnandez** [comment] 2017-12-01 22:34
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Closed as completed by simnandez** 2017-12-01 22:34 UTC
