### ISSUE TITLE
[Bug]Adding menu left in accountancy, suppliers_bills with eldy_menu

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#6074] opened 2016-12-01 11:26 UTC
# Bug
Adding menu left element in accountancy, suppliers_bills and doesn't display in right place (using eldy_menu).

## Environment
- **Version**: 4.0.0
- **OS**: Linux otos.planethoster.net
- **Web server**: LiteSpeed
- **PHP**: 5.6.28
- **Database**: MySQL or MariaDB 10.1.19-MariaDB
- **URL(s)**: /compta/index.php

## Expected and actual behavior
I create a module in custom directory everything works fine. I try to add a menu left entry in the module descriptor and not works really well in a unique case.
The module works well (number of module, rights, config, pages, translations, class, lib, js, css...) no error message or error_log.

## Steps to reproduce the behavior
Here are the line i've added in my module descriptor
```php
	$this->menu = array();			// List of menus to add
	$r=0;	
	$this->menu[$r]=array(	'fk_menu'=>'fk_mainmenu=accountancy,fk_leftmenu=suppliers_bills',
					'type'=>'left',
					'titre'=>'mynewmodulename',
					'mainmenu'=>'accountancy',
					'leftmenu'=>'suppliers_bills',
					'url'=>'/mynewmodule/index.php',
					'langs'=>'mynewmodule@mynewmodule',
					'position'=>100,
					'enabled'=>'1',
					'perms'=>'1',
					'target'=>'',
					'user'=>2);	
	$r++;	
```
The link 'mynewmodulename' displays as a submenu element :

Suppliers invoices
- New invoices
- List
  - Draft
    - mynewmodulename
  - Not paid
  - Paid
- Payments
- Statistics

instead of as last element :

Suppliers invoices
- New invoices
- List
  - Draft
  - Not paid
  - Paid
- Payments
- Statistics
- mynewmodulename

If i try to add the link  'mynewmodulename' in an other mainmenu,leftmenu (or even topmenu) everything works perfect (product, commercial...)

Thanks for reading ;)

**Comment by dolibarr95** [comment] 2016-12-07 07:41
Hello

I've just check the table `llx_menu` (duplicates, errors etc) everything seems to be correct.
I've tried with an other external module from an other editor (not me) by adding in `$this->menu ` the elements i want to display.

But nothing changes, the display bug's still there.

Does it works for you ?

Thanks for reading ;)

**Comment by dolibarr95** [comment] 2016-12-07 07:45
closed by error

**Comment by rdoursenaud** [comment] 2017-01-16 21:15
Confirmed for a lot of entries in eldy system.
Introduced in 3.8 cycle because of an ill defined API.
Spreaded by copy and paste cancer since then.

Fix incoming.

**Comment by dolibarr95** [comment] 2017-01-17 07:37
tks all lot for this feedback!
;-)

**Comment by dolibarr95** [comment] 2017-09-20 07:25
Hi
I've test this with Dolibarr 6.
The menu displays well but but it lacks the folder 'custom' in the url.

So instead of : 
```php
'url'=>'myModule/page.php',
```
I must write :
```php
'url'=>'custom/myModule/page.php',
```
In the module descriptor.

_Note: this bug is only in Financial module works very well with product..._

Tks

**Comment by simnandez** [comment] 2017-12-01 22:50
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Closed as completed by simnandez** 2017-12-01 22:50 UTC
Labels: Bug
