### ISSUE TITLE
Commande or Shipments extrafields does not move to invoice.

### ISSUE THREAD

**Issue by nach41710** [Dolibarr/dolibarr#22407] opened 2022-09-25 21:22 UTC
### Bug

When I move from commande or shipment to an invoice approving them, the extrafields dissapears.
You can create a shipment with extrafields, try to create an invoice  and the extrafields does not appears in the invoice.

### Environment Version

16.0

### Expected and actual behavior

Epected, and working in version 15:
I move shipment to an invoice approving them, same extrafield values are available in the invoice.

Actual behaviour:
I create the invoice from shipment  and the extrafields are empty.

### Steps to reproduce the behavior

Create same extrafields in Shipment and invoice.
Fill in extrafields in Shipment or commande.
Create the invoice.
The extrafields will be empty in the invoice.

**Comment by priojk** [comment] 2022-09-26 14:51
Cannot reproduce this bug.

Did you create the extrafield **for all the objects** (i.e. for the order and the invoice and other required objects like shipment) **separately** in each module setup, always using the exact same reference ID? 

I just checked in v16, created an order with a value set in this extrafield, created an invoice based on the order and the contents of the extrafield of the order was correctly present in the invoice.

**Comment by eldy** [comment] 2022-09-26 21:38
@priojk May be trouble is when creating invoice from shipment only and not from order.

**Comment by priojk** [comment] 2022-09-27 06:54
I just tested all kinds of variants of transitions between proposals, orders, shipments and invoices. All worked fine for me, the extrafield got always copied. Used a per document extrafield of type string, not per line extrafields.

If the problem persists although the extrafields are all defined for the involved objects, more input would be helpful like exact definition of the missing extrafield (type etc.) and whether additional external modules are in use, which could interfere.

**Comment by nach41710** [comment] 2022-09-28 12:51
@priojk I am using per line extrafields, no order extrafields.

I attach my extrafield definition.

![extrafield definition](https://user-images.githubusercontent.com/12851949/192782927-932e88c4-8871-4e30-9479-295dbc7795a5.jpg)

**Comment by priojk** [comment] 2022-09-28 13:30
Ok, tested it with extrafields for positions in shipments AND extrafields for positions in invoices (for sake of simplicity just with text fileds). Worked as expected.

You showed the definition of your extrafiels for shipment positions. Can you please also make a screenshot of the extrafield definitions for the invoice positions. Maybe the attribute code (I think it's "Codigo" in your screenshot) has a typo or the field types differ?

**Comment by ksar-ksar** [comment] 2022-10-10 21:02
Hello,

Without your inputs, we can't investigate on this Bug.
I close it for now.
You can always re-open it.

**Closed as completed by ksar-ksar** 2022-10-10 21:02 UTC
Labels: Bug or PR need more information
