### ISSUE TITLE
jQuery TreeView not maintained anymore

### ISSUE THREAD

**Issue by altairis-tof** [Dolibarr/dolibarr#6531] opened 2017-03-16 08:44 UTC
The jquery TreeView plugin is not maintained anymore (https://github.com/jzaefferer/jquery-treeview).
Maybe we should go to the great jsTree plugin ? (https://www.jstree.com/)

**Comment by altairis-tof** [comment] 2017-03-16 08:49
if we look at the "official" website for this plugin (http://bassistance.de/jquery-plugins/jquery-plugin-treeview), they advice to go to jstree : 

> Note as of April 2010: While the plugin still works as it is, it has some shortcomings, and not maintained anymore. There are now plenty of alternative jQuery tree plugins, like jsTree.

**Comment by braito4** [comment] 2017-03-16 09:09
https://github.com/Dolibarr/dolibarr/issues/5590

**Comment by atm-maxime** [comment] 2019-05-18 23:58
Duplicate of #5590

**Closed as completed by atm-maxime** 2019-05-18 23:58 UTC
