### ISSUE TITLE
Native dark mode theme

### ISSUE THREAD

**Issue by gillerby** [Dolibarr/dolibarr#18111] opened 2021-07-08 14:48 UTC
# Feature Request
A native dark mode theme, already bundled with Dolibarr.

Currently all dark mode themes are addons which need extra installation, and all are paid.

**Comment by atm-maxime** [comment] 2021-07-08 20:36
Development is in progress, try it with the hidden setup THEME_DARKMODEENABLED

**Comment by daraelmin** [comment] 2021-07-08 21:05
Duplicate of #13132

**Closed as completed** 2021-07-09 21:49 UTC
Labels: Feature request

**Comment by alsoft10** [comment] 2021-12-23 08:03
Is dark mode theme is still in development progress status? When the development will be finished @atm-maxime ?
