### ISSUE TITLE
Empty page

### ISSUE THREAD

**Issue by fred-gb** [Dolibarr/dolibarr#24894] opened 2023-05-26 13:24 UTC
### Bug

Hi,

Following this post:
https://www.dolibarr.fr/forum/t/impossible-dafficher-comptabilite-avancee/43105

What I can do?
Thanks

### Environment Version

16.0.5

### Environment OS

Ubuntu

### Environment Web server

Apache2

### Environment PHP

php8

### Environment Database

mariadb

### Expected and actual behavior

actual:
<img width="1439" alt="Capture d’écran 2023-05-26 à 14 48 33" src="https://github.com/Dolibarr/dolibarr/assets/17061623/a234ff19-2919-4888-930b-07a77c44df1e">

### Steps to reproduce the behavior

I try in dev environnement/install to upgrade from 15.0.0 to 16.0.5 (not 17.0.1, because not compatible with cyberoffice plugin)

I try a step to 15.0.2, same error.

This test environnement uses: https://hub.docker.com/r/upshift/dolibarr

I disable all cores modules and externals modules. Empty cache. Remove custom folder. 

### Attached files

For most of pages, this type of error:

```
[Fri May 26 12:45:41.086258 2023] [php:error] [pid 39] [client 127.0.0.1:37716] PHP Fatal error:  Uncaught Error: Object of class stdClass could not be converted to string in /var/www/html/core/menus/standard/eldy.lib.php:962\nStack trace:\n#0 /var/www/html/core/menus/standard/eldy_menu.php(150): print_left_eldy_menu()\n#1 /var/www/html/main.inc.php(2870): MenuManager->showmenu()\n#2 /var/www/html/main.inc.php(1387): left_menu()\n#3 /var/www/html/societe/index.php(78): llxHeader()\n#4 {main}\n  thrown in /var/www/html/core/menus/standard/eldy.lib.php on line 962, referer: https://dolibarr-FQDN.com/comm/index.php?mainmenu=commercial&leftmenu=
```

And:

```
Fri May 26 12:55:45.744856 2023] [php:warn] [pid 38] [client 127.0.0.1:48716] PHP Warning:  is_dir(): open_basedir restriction in effect. File(/var/www/html/..) is not within the allowed path(s): (/var/www/localhost/htdocs:/var/www/documents:/var/www/run:/tmp) in /var/www/html/core/lib/functions2.lib.php on line 100, referer: https://dolibarr-FQDN.com/admin/index.php?mainmenu=home&leftmenu=setup
```

**Comment by Daviid-P** [comment] 2023-05-26 14:11
This one
`Fri May 26 12:55:45.744856 2023] [php:warn] [pid 38] [client 127.0.0.1:48716] PHP Warning:  is_dir(): open_basedir restriction in effect. File(/var/www/html/..) is not within the allowed path(s): (/var/www/localhost/htdocs:/var/www/documents:/var/www/run:/tmp) in /var/www/html/core/lib/functions2.lib.php on line 100, referer: https://dolibarr-FQDN.com/admin/index.php?mainmenu=home&leftmenu=setup` 

might be because of a wrong path on `htdocs\conf\conf.php`
or because of the PHP config variable `open_basedir`, are you hosting on a server?

**Comment by fred-gb** [comment] 2023-05-26 14:36
Thanks,

Since your answer, I found something new.

When I change menu like that:
<img width="1424" alt="Capture d’écran 2023-05-26 à 16 31 14" src="https://github.com/Dolibarr/dolibarr/assets/17061623/2ebc8470-cbc2-43e2-ab27-23c98b9e1edc">

With `auguria_menu`

Menus appears, but not look good:
<img width="810" alt="Capture d’écran 2023-05-26 à 16 33 57" src="https://github.com/Dolibarr/dolibarr/assets/17061623/be00c444-cb29-4425-ab52-b62c62471c1e">
<img width="235" alt="Capture d’écran 2023-05-26 à 16 34 18" src="https://github.com/Dolibarr/dolibarr/assets/17061623/ca4d2842-3dea-4181-b3e4-4f3af3f1adb7">

`NULL` everywhere

It's better, but not solution I'm thinking.

An idea?

Thanks

**Comment by AurelienBISOTTI** [comment] 2023-06-10 16:49
Seems linked to your environment and not to Dolibarr.

You might need to check PHP logs and Dolibarr Logs

![Capture d’écran du 2023-06-10 18-40-11](https://github.com/Dolibarr/dolibarr/assets/12530585/985aa5e5-c32a-4431-83ca-d0be832b2996)


![Capture d’écran du 2023-06-10 18-39-58](https://github.com/Dolibarr/dolibarr/assets/12530585/f33fa4fc-a6a4-48ad-bd73-cf805ac94c32)

**Comment by AurelienBISOTTI** [comment] 2023-06-10 16:50
Also, I think Dolibarr v16 should be used with PHP7 and not PHP8

Try switching to PHP7 or updating Dolibarr to v17

**Comment by fred-gb** [comment] 2023-06-12 07:17
Hello,
Thanks, since initial post. I upgraded to Dolibarr 16.0.5 and let to PHP7, same problem.
I let on `agura_menu` for the production, with little glitch.
Thanks

**Comment by eldy** [comment] 2023-12-28 12:52
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

Also did you try to disable ALL external modules if you have some ?

**Comment by eldy** [comment] 2024-06-09 14:07
No answer received, so i close tocket.

**Closed as not planned** 2024-06-09 14:08 UTC
Labels: Bug, Event: DevCamp 2023 Bordeaux
