### ISSUE TITLE
combo ajax issue

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4260] opened 2015-12-18 12:23 UTC
Product combo ajax don't add product to customers order when change qty or price on the row. Instead on supplier order add with no problem, also changing qty

**Comment by eldy** [comment] 2015-12-19 17:04
Which version of dolibarr do you experience this ?

**Comment by centoasa** [comment] 2015-12-19 17:29
3.8.2

**Comment by marcosgdf** [comment] 2015-12-27 12:30
Cannot reproduce. Can you please tell us which browser are you using and if you see any error in the javascript console?

**Comment by centoasa** [comment] 2015-12-27 14:48
chrome browser, plese see this video:
https://youtu.be/VXgkUk9_8GE

**Comment by eldy** [comment] 2015-12-27 17:08
Can't reproduce with last version into 3.8 branch.
Can you reproduce on demo.dolibarr.org ?

**Comment by centoasa** [comment] 2015-12-27 17:19
why on release I using I've 
https://www.evernote.com/shard/s272/sh/5615e7b9-f771-4238-821d-ee2226bd997d/136229c81e48bc7882edea1548626f16
with vat, unit price net, etc as in image, instead on demo there are only qty, discount, buy price for defualt sell products? on demo when I add product that have vat, the row show 0% vat.
Where I change this? Or where I wrong settings?
Maybe I've setup 2 level prices for customers?

**Comment by centoasa** [comment] 2016-01-03 10:53
on 3.8.3 release still remain the issue
see my video to explain:
https://youtu.be/07JVHto204Q

**Comment by marcosgdf** [comment] 2016-01-03 11:37
I'll repeat my question: Can you please tell us which browser are you using and if you see any error in the javascript console?

**Comment by centoasa** [comment] 2016-01-03 15:17
latest release chrome
when select order I've Uncaught SyntaxError: Unexpected token .
card.php?id=71:628
then when add product with default qty 
ajax_autocompleter new value selected, we trigger change card.php?id=71:512 
when add product with personal qty:
Uncaught SyntaxError: Unexpected token .card.php?id=71:662

**Comment by centoasa** [comment] 2016-01-05 05:48
same happen on this demo site http://dolibarr.atm-consulting.fr/commande/card.php?id=6

**Comment by marcosgdf** [comment] 2016-01-06 09:30
The demo site is http://demo.dolibarr.org/public/demo/index.php. That site is throwing PHP errors

Also, we may need an extract of the code the errors are referring to, as the page changes depending on many variables (modules, language…). Can you please record on a video the errors of the JS console and an extract of the lines the errors are referring to?

**Comment by centoasa** [comment] 2016-01-12 22:12
The demo site I'm talking about is http://dolibarr.atm-consulting.fr/commande/card.php?id=6 and have same issue to mine

**Comment by marcosgdf** [comment] 2017-04-09 11:32
3.8 version is not supported anymore. Can you please confirm it is working with latest version and close this bug if it is? Thanks

**Closed as completed** 2017-12-01 22:03 UTC
