### ISSUE TITLE
Proposals that have passed the validity date show up in comm/index.php

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14322] opened 2020-07-31 08:37 UTC
# Bug
I think that its a bug because it clutters the interface. These should be excluded from the overview IMO.

## Environment
- **Version**: 12
- **URL(s)**: http://dolibarr.localhost/comm/index.php?mainmenu=commercial&leftmenu=

## Expected and actual behavior
Only valid proposals should show up.

**Comment by atm-lena** [comment] 2021-01-06 15:31
It's not a bug. It's a normal behavior. If a propal has a passed validity date it is necessary to close it.
It's very important to close propals because it generates several consequences.

**Comment by dpriskorn** [comment] 2021-01-07 08:33
In 12.0.2 close does not exist. After marking it not signed I only get the options: reopen, clone and delete

**Comment by atm-maxime** [comment] 2021-01-07 08:48
By "close" she meant "signed" or "not signed". While a proposal is still in status "validated", it's considered as open, whatever is the validity date. Perhaps you are looking for a feature request that will close "not signed" automatically a proposal when the validity date is reached ? But not everyone wants it.

**Comment by dpriskorn** [comment] 2021-01-07 08:52
Yes, a button that does that would be nice. I don't want it done in the background though. 
I'm still trying to understand the UI 😅

**Comment by atm-maxime** [comment] 2021-01-07 09:01
There's a mass action on the proposal list called "close". So you can select all your outdated proposals and then close them "not signed" at once

**Comment by dpriskorn** [comment] 2021-01-07 15:43
Closing this as it is now clear how to "close" proposals

**Closed as completed** 2021-01-07 15:43 UTC
Labels: Bug
