### ISSUE TITLE
Bug 3.8.2 : Broken Pictures on Proposals

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#4012] opened 2015-11-16 18:30 UTC
I was on a 3.7, could make proposals with picture
Moved on 3.8.2 cannot anymore
Can you reproduce ?

I tried making MAIN_GENERATE_PROPOSALS_WITH_PICTURE to 0 then 1 
it didn't change.

maybe regression to MAIN_GENERATE_DOCUMENTS_WITH_PICTURE ? or anything ?

**Comment by marcosgdf** [comment] 2015-12-27 14:03
Cannot reproduce

![captura de pantalla 2015-12-27 a las 15 03 16](https://cloud.githubusercontent.com/assets/168744/12010543/fdada624-acaa-11e5-9f6c-0a53dc980005.png)

**Comment by simnandez** [comment] 2017-12-01 21:52
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Closed as completed by simnandez** 2017-12-01 21:52 UTC
