### ISSUE TITLE
Bug: price for qty

### ISSUE THREAD

**Issue by centoasa** [Dolibarr/dolibarr#4454] opened 2016-01-18 15:20 UTC
# Environment
- **Version**: 4.0.0-beta
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.16
- **Database**: MySQL or MariaDB 5.5.47-cll-lve
- **URL**: /product/price.php?action=delete&id=227&lineid=660
# Report

delete row price for qty, show error:
Cannot delete or update a parent row: a foreign key constraint fails (`admin_dollibar`.`llx_product_price_by_qty`, CONSTRAINT `fk_product_price_by_qty_fk_product_price` FOREIGN KEY (`fk_product_price`) REFERENCES `llx_product_price` (`rowid`))

**Comment by ghost** [comment] 2016-06-30 14:45
Hi,

unable to reproduce it into the last dev version,

Regards

**Comment by simnandez** [comment] 2017-12-01 22:12
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Closed as completed by simnandez** 2017-12-01 22:12 UTC
