### ISSUE TITLE
"Validate" function is unavailable under proposal module

### ISSUE THREAD

**Issue by wankwaiwing** [Dolibarr/dolibarr#3538] opened 2015-09-17 02:34 UTC
Dolibarr version is v3.8.0.
How to enable the "validate" function under proposal module?
Thank you very much!

**Comment by wankwaiwing** [comment] 2015-09-17 03:21
MAIN_USE_ADVANCED_PERMS => null

**Comment by rdoursenaud** [comment] 2015-09-18 07:46
Can't reproduce on demo.dolibarr.org.

**Comment by marcosgdf** [comment] 2015-10-06 08:45
An user has contacted me communicating that he is also facing this problem:

Because MAIN_USE_ADVANCED_PERMS equals to null, they are not able to see the validate button. If they create the constant in Config > Misc with a value of 0 or 1, they can.

**Comment by accett** [comment] 2015-10-06 11:23
Is the proposal module active?

It happened to me in a update one time and then I realized my module it
wasn't active by default.

**Comment by marcosgdf** [comment] 2015-11-16 23:54
This is happening in latest 3.8 branch code.

I've updated a DB from 3.5 to latest 3.8 and the validate button is not available! Even with admin permissions.

I had to set the constant to 1 and then remove it so that I could validate quotes

**Comment by Leeto2** [comment] 2015-12-16 18:56
Had the same issue after migrating from 3.7.0 to 3.8.2. 
Fixed by adding MAIN_USE_ADVANCED_PERMS = 0 (thank you markosgdf) to  Home --> Setup -->Other Setup

**Comment by mariamanc28** [comment] 2016-01-07 15:15
for me instead "Validate" button  is disabled under proposal module, i have 3.8.3 version

**Comment by mariamanc28** [comment] 2016-01-11 09:25
i have resolved problem, i have deactivate and reactivate the module

**Comment by rdoursenaud** [comment] 2016-01-25 15:57
Thanks for the report @mariamanc28. I'll close this issue.

**Closed as completed by rdoursenaud** 2016-01-25 15:57 UTC
Labels: Bug
