### ISSUE TITLE
3.9.4 : DB error and php 7 issues

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#6337] opened 2017-01-26 09:59 UTC
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Bug" or "Feature Request" section*
- *replace the bracket enclosed texts with meaningful informations*
- *remove any unused sub-section*

# Bug
PHP7 issue with facture récurrentes

## Environment
- **Version**: 3.9.4
- **OS**: LINUX
- **Web server**: Apache
- **PHP**: 7.0.14
- **Database**: mysql
- **URL(s)**: htdocs/compta/facture.php

## Expected and actual behavior
Php warnings and database eror
DELETE from llx_facture_extrafields where rowid = 
(no rowid provided)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![bugdoli20160126](https://cloud.githubusercontent.com/assets/919513/22327222/65032338-e3b6-11e6-9872-16d66e8f749b.png)

**Comment by eldy** [comment] 2017-02-02 01:50
Support of PHP 7 is available from Dolibarr 5.0 only.

**Comment by eldy** [comment] 2017-02-02 02:09
Dolibarr 3.9 is not supported with PHP 7.
PHP 7 was released after. So it should works and be supported with Dolibarr 4+

**Comment by laudeco** [comment] 2017-02-02 14:28
Shouldn't you close this issue, as soon as it's fixed ?

**Comment by simnandez** [comment] 2017-09-28 08:51
I close this issue, because is not reproducible in maintened versions

**Closed as completed by simnandez** 2017-09-28 08:51 UTC
