### ISSUE TITLE
Can edit the percentage discount of lines in one shot

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr#20653] opened 2022-04-15 09:15 UTC
### Feature Request

Currently when editing an invoice, we can set the vat of all lines in one action using the picto "edit" on the title of the line.
![image](https://user-images.githubusercontent.com/883887/163552164-1acab2a4-06bf-41a9-a20e-5352acfb2371.png)

The request is to be able to do the same for the discount % on lines (the column after the column qty) on the screenshot.

**Comment by Nexyll** [comment] 2022-04-20 20:54
Maybe a duplicate of #19915 ?

**Closed as completed** 2022-05-03 23:20 UTC
Labels: Feature request
