### ISSUE TITLE
Unable to create delivery note

### ISSUE THREAD

**Issue by LEROYLR** [Dolibarr/dolibarr#12858] opened 2020-01-16 06:08 UTC
Initial installation version:
Latest updated version: 11.0.0-alpha
Program version: 11.0.0-alpha
Hosting: Linux, Cloud OVH.

Hello,

I can no longer create a delivery note from the "Customer order" screen.

I come across a blank page with no messages.
No message either in the “documents / dolibarr.log” log file…
I do not use EXTRA FIELD for the "shipping" module.

Thanks for your help.

Loïck

——

Solution :

**In the PHP log file:: /var/log/apache2/error.log**

I found the error:

_PHP Fatal error: Uncaught Error: Access to undeclared static property: OrderLine :: $ table_element in htdocs / expedition / card.php: 95 \ nStack trace: \ n # 0 {main} \ n thrown in / xxxxx / htdocs / expedition / card.php on line 95, referer: https: //xxxxxxxxxx/expedition/shipment.php? id = 387_

In the file: "**/htdocs/expedition/card.php**" I commented on Line 95:

// $ extrafields-> fetch_name_optionals_label (OrderLine :: $ table_element);

it works again.
++
L.

**Comment by dpriskorn** [comment] 2020-08-07 09:25
Can you update to v12 and see if the problem is fixed there?

**Comment by ksar-ksar** [comment] 2021-02-19 12:58
Hello,

No update since last question.

I close the issue, if it persists you can re-open it.

**Closed as completed by ksar-ksar** 2021-02-19 12:58 UTC
Labels: Bug
