### ISSUE TITLE
Bug: Unicode not supported with WYSIWYG module in 3.7

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3632] opened 2015-10-01 10:34 UTC
Version: 3.7.2

![captura de pantalla 2015-10-01 a las 12 34 30](https://cloud.githubusercontent.com/assets/168744/10218655/ccf61888-6838-11e5-95af-a6fb5569c60a.png)

If I click edit:
![captura de pantalla 2015-10-01 a las 12 34 33](https://cloud.githubusercontent.com/assets/168744/10218654/cb332bda-6838-11e5-88af-79a10f0a3440.png)

**Comment by eldy** [comment] 2015-10-01 12:42
I can't reproduce. I use it with a lot of special char adn nothing is wrong on my side.
Exemple:
éàçèéù

What do you see if you show "source" of wysiwyg editor ?
Can you paste the text with utf8 chars you want ot enter ?

**Comment by marcosgdf** [comment] 2015-10-01 13:18
Try to use an emoji

**Comment by ndrosis** [comment] 2015-10-01 13:53
The database is utf8_general_ci

**Comment by rdoursenaud** [comment] 2015-10-01 15:25
Can't reproduce either.
![capture d ecran de 2015-10-01 17-25-02](https://cloud.githubusercontent.com/assets/1210367/10225087/629d70a2-6861-11e5-9563-42c86a420055.png)

**Comment by rdoursenaud** [comment] 2015-10-01 15:26
It may very well be a database issue. What backend and encoding are you using?

**Comment by rdoursenaud** [comment] 2015-10-01 15:30
Finally been able to reproduce it with this kind of character: 😾

**Comment by rdoursenaud** [comment] 2015-10-01 15:33
It definitely isn't a WYSIWYG issue but rather a backend problem. The behavior is the same with the WYSIWYG module disabled.

**Comment by rdoursenaud** [comment] 2015-10-01 15:37
OK, it's a MySQL issue with 4 byte unicode characters:
https://stackoverflow.com/questions/19224119/unicode-characters-emoticons-in-mysql-with-4-bytes
The solution is to switch to utf8mb4 encoding rather than utf8.
This should be the default if we want full i18n support at the database level.

Yet PHP is still lagging with its unicode support unless using PHP 6 so frontend will stay hard!

**Comment by rdoursenaud** [comment] 2015-10-01 15:38
I suggest closing this issue and creating a feature request for utf8mb4 in Dolibarr 3.9. Are you OK with that?

**Comment by eldy** [comment] 2015-10-01 20:21
Using default value utf8mb4 require mysql 5.5.3
But a lot of server hosting dolibarr are still using a lower version.
Someone know a way to know the part of mysql versions running on server in
the world ?

2015-10-01 17:38 GMT+02:00 Raphaël Doursenaud notifications@github.com:

> I suggest closing this issue and creating a feature request for utf8mb4 in
> Dolibarr 3.9. Are you OK with that?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/issues/3632#issuecomment-144765431.

## 

EMail: eldy@destailleur.fr

## Web: http://www.destailleur.fr

Google+: https://plus.google.com/+LaurentDestailleur/
Facebook: https://www.facebook.com/Destailleur.Laurent

## Twitter: http://www.twitter.com/eldy10
- Dolibarr (Project leader): http://www.dolibarr.org (make a donation for
  Dolibarr project via Paypal: contact@destailleur.fr)
- AWStats (Author) : http://awstats.sourceforge.net (make a donation for
  AWStats project via Paypal: contact@destailleur.fr)
- AWBot (Author) : http://awbot.sourceforge.net
- CVSChangeLogBuilder (Author) : http://cvschangelogb.sourceforge.net

**Comment by rdoursenaud** [comment] 2015-10-02 09:06
@eldy It's easy to detect the version and act accordingly with a warning to those using the obsolete encoding.
The main issues are resizing the indexes so that data fits and offering a migration path.
For versions statistics, I don't think there is such a thing since it's backend technology so there's no mean of measurement.

**Comment by rdoursenaud** [comment] 2015-10-02 17:45
Ok, opened #3647 for more in depth discussion and prototyping.
I'll close this one, so please add any discussion there.

**Closed as completed by rdoursenaud** 2015-10-02 17:45 UTC
Labels: Bug
