### ISSUE TITLE
V16 - bug - CRM - Emailing to customers using 'group Tag' does not find any record

### ISSUE THREAD

**Issue by daxitsolutions** [Dolibarr/dolibarr#23299] opened 2022-12-21 14:04 UTC
### Bug

When trying to add recipient to a mailing list from the tag, the system does not find any record

### Environment Version

16.0.0

### Environment OS

CentOS

### Environment Web server

Apache2

### Environment PHP

7.3

### Environment Database

MySQL

### Environment URL(s)

https://xxx.com/htdocs/comm/mailing/cibles.php?action=add&token=ABC&id=5&module=thirdparties

### Expected and actual behavior

1. Add a tag/group to a thirdparty
2. select this tag from the emailing module
3. add the customer related to this tag

### Steps to reproduce the behavior

1. Create a new tag "hosting"
2. Add a tag/group "hosting" to a thirdparty
3. Make sure the thirdparty has an email
4. select this tag from the emailing module
5. add the customer related to this tag

### Attached files

Step 1 add tag to a customer 
![La_Villa_Lorraine_-_Fiche](https://user-images.githubusercontent.com/26635105/208923340-db9a2db7-a16e-48ed-8202-a430a3975d6a.jpg)

Step 2 select tag from emailing

![Emailing](https://user-images.githubusercontent.com/26635105/208922891-58851998-03d1-48a8-b3d4-519bda194481.jpg)

**Comment by ksar-ksar** [comment] 2022-12-22 16:03
Duplicate of #23238

**Closed as completed** 2023-06-10 20:01 UTC
Labels: Bug, Event: DevCamp 2023 Bordeaux
